// Question Bank — Part III: laboratory practical scenarios (original questions
// in the style of lab-based exam sections). Each is a short experimental
// situation requiring technique knowledge or error-direction reasoning.

import type { BankMC } from './bankPart1';

export const PART3: BankMC[] = [
  // ---- titration technique ----
  { id: 'p3-acids-001', topic: 'acids', q: 'During a titration you overshoot the endpoint by several drops before noticing. The calculated analyte concentration will be…', opts: ['too low', 'too high', 'unaffected', 'random'], a: 1, why: 'Extra titrant is recorded as "needed" → moles of analyte calculated too high. If it happens, the honest fixes are: discard the trial, or back-titrate.' },
  { id: 'p3-acids-002', tier: 3, topic: 'acids', q: 'A buret is rinsed with distilled water but NOT with the NaOH titrant before filling. The reported acid concentration will be…', opts: ['too high', 'too low', 'unaffected', 'exactly halved'], a: 0, why: 'Residual water dilutes the NaOH → more volume needed to deliver the same moles → V reads high → calculated acid concentration too high.' , misconception: 'A wet burette is not harmless "because water is only the solvent" — it dilutes the titrant it delivers, so more volume is needed for the same moles of NaOH, and the inflated titre feeds straight into a high acid concentration. The glassware where a water rinse genuinely does cancel is the conical flask: extra water there changes the volume but not the moles of analyte already measured into it.' },
  { id: 'p3-acids-003', tier: 3, topic: 'acids', q: 'NaOH is standardized against KHP that absorbed moisture before weighing. The NaOH concentration determined will be…', opts: ['zero', 'too low', 'unaffected', 'too high'], a: 3, why: 'Part of the weighed "KHP" is water → true moles of KHP are LESS than calculated, so less NaOH is used (small V). C = n(assumed)/V(small) → overestimated.' , misconception: 'Absorbed moisture adds mass but no moles, and it is the moles that are mis-stated: the calculation credits water as though it were KHP, so n is overestimated while the volume delivered still reflects the smaller real amount. Reasoning "the sample is heavier, so more NaOH is used, so the concentration comes out low" treats mass as if it were moles — the titre actually falls short of what the assumed n demands.' },
  { id: 'p3-acids-004', tier: 3, topic: 'acids', skill: 'acids/indicators', q: 'For a weak-acid/strong-base titration, methyl orange (range 3.1–4.4) is used by mistake. The endpoint will appear…', opts: ['late, after true equivalence', 'exactly at the equivalence point', 'early, before true equivalence', 'never appear at all'], a: 2, why: 'The curve passes pH 3–4.4 long before the steep jump (equivalence is ~8.7). The indicator changes while acid is still mostly untitrated → endpoint far too early.' , misconception: 'An indicator changes at ITS OWN pH range; it has no way of knowing where the equivalence point is. Methyl orange flips at pH 3.1–4.4, which the curve crosses while most of the weak acid is still untitrated, so the colour arrives early and the titre reads low — the belief that an indicator errs only slightly whichever one you grab is what makes "late" look plausible.' },

  // ---- gravimetric analysis ----
  { id: 'p3-stoich-001', topic: 'stoich', q: 'In a gravimetric chloride analysis, the AgCl precipitate is weighed while still slightly damp. The reported %Cl will be…', opts: ['too low', 'too high', 'unaffected', 'negative'], a: 1, why: 'Water adds mass attributed to AgCl → moles of Cl calculated high. "Heat to constant mass" exists exactly to kill this error.' },
  { id: 'p3-stoich-002', topic: 'stoich', q: 'A precipitate is washed with very large volumes of pure water. The main risk is…', opts: ['dissolving away some product', 'contaminating the precipitate', 'drying the solid excessively', 'nothing — more washing is always better'], a: 0, why: 'Even "insoluble" salts have finite Ksp; unlimited washing steadily dissolves product → results biased low. Wash with small portions (sometimes with a common-ion solution).' },
  { id: 'p3-stoich-003', topic: 'stoich', q: 'The filtrate from a gravimetric analysis still gives a precipitate when more reagent is added. This means…', opts: ['the analysis is perfectly fine', 'Ksp had been exceeded already', 'the precipitate was badly contaminated', 'precipitation was incomplete, so results run low'], a: 3, why: 'Analyte remained in solution → the collected mass undercounts it. Always test the filtrate for completeness of precipitation.' },

  // ---- calorimetry ----
  { id: 'p3-thermo-001', tier: 3, topic: 'thermo', q: 'A coffee-cup calorimetry experiment ignores heat absorbed by the cup and thermometer. The measured |ΔH| will be…', opts: ['too large', 'unaffected', 'too small', 'doubled'], a: 2, why: 'Some heat warms the apparatus instead of the water → ΔT of the water is smaller than it "should" be → computed |q| and |ΔH| too small. Fix: determine the calorimeter constant.' , misconception: 'Ignoring a heat sink does not inflate the answer — it deflates it. The cup and thermometer soak up part of the heat released, so the water warms less than it otherwise would, and a smaller ΔT gives a smaller q and a smaller |ΔH|. Expecting "a neglected term means an overestimate" gets the direction of every calorimetry bias backwards; ask instead where the missing joules went.' },
  { id: 'p3-thermo-002', topic: 'thermo', q: 'In measuring the heat of a slow reaction in a simple calorimeter, the biggest systematic problem is…', opts: ['stirring the mixture too much', 'using far too much water', 'misreading the balance display', 'heat exchange with the room'], a: 3, why: 'The longer the run, the more heat leaks to (or from) the surroundings. Extrapolating the temperature-time curve back to mixing time is the standard correction.' },

  // ---- spectrophotometry ----
  { id: 'p3-lab-001', tier: 3, topic: 'lab', skill: 'lab/error-analysis', q: 'A fingerprint on the cuvette scatters light during an absorbance reading. The measured concentration will be…', opts: ['too high', 'too low', 'unaffected', 'exactly right if λmax is used'], a: 0, why: 'Scattered light never reaches the detector → instrument reads it as absorption → A high → c = A/εb overestimated. Wipe with lint-free tissue, handle by the frosted sides.' , misconception: 'A spectrophotometer measures transmitted light and cannot tell absorption from scattering — anything that stops photons reaching the detector is recorded as absorbance. So the smudge does not "block the beam and lower the reading": less light through means a HIGHER A, and c = A/εb comes out too high. Reading a lost signal as a low result confuses transmittance with absorbance.' },
  { id: 'p3-lab-002', tier: 3, topic: 'lab', q: 'Your unknown reads A = 1.9 while your standards span 0.1–0.8. Best procedure?', opts: ['report the value off the fitted line', 'dilute quantitatively and re-measure', 'extrapolate the calibration line', 'switch to another wavelength'], a: 1, why: 'A = 1.9 means ~1% transmittance — noise-dominated and outside the calibrated (and linear) range. Dilute by a known factor, re-measure, multiply back.' , misconception: 'Beer’s law is treated as if it held to any absorbance, so extending the fitted line a little past the standards feels safe. At A = 1.9 only about 1% of the light is getting through, where stray light and detector noise dominate and the response has already bent — extrapolation there is arithmetic, not a measurement. Bring the sample into the calibrated range instead and scale the answer back up.' },
  { id: 'p3-lab-003', topic: 'lab', q: 'The blank used to zero a spectrophotometer should contain…', opts: ['distilled water only, in every case', 'the most concentrated standard used', 'everything but the analyte', 'nothing at all — an empty holder'], a: 2, why: 'Matrix, solvent and cuvette all absorb a little; only a matched blank subtracts them cleanly, isolating the analyte\'s absorbance.' },

  // ---- kinetics experiments ----
  { id: 'p3-kinetics-001', tier: 3, topic: 'kinetics', q: 'In an iodine clock experiment, the measured time-to-color is used as a rate proxy because…', opts: ['rate = k·t directly', 'rate ∝ 1/t, a fixed extent per trial', 't equals the half-life', 'the colour is proportional to k'], a: 1, why: 'Each trial consumes the same small fixed amount of thiosulfate before the color snaps in → rate ≈ (fixed Δ[X])/t → rate ∝ 1/t. Doubling of 1/t reveals reaction orders.' , misconception: 'Time and rate run in OPPOSITE directions: a faster reaction takes less time to reach the colour change, so t cannot be a rate. The clock works only because each trial consumes the same fixed amount of thiosulfate first, making rate ≈ (fixed Δ[X])/t, i.e. proportional to 1/t. Plotting t rather than 1/t against concentration inverts every reaction order you extract.' },
  { id: 'p3-kinetics-002', tier: 3, topic: 'kinetics', q: 'A kinetics run is done in a water bath that slowly warms by 3 °C during the experiment. The measured rate constant will be…', opts: ['biased high late in the run', 'a clean average of the two', 'unaffected, since k is a constant', 'biased low late in the run'], a: 0, why: 'k grows exponentially with T (Arrhenius); the data collected later reflect a faster reaction → curvature in the linear plots and an inflated k. Thermostat quality is everything in kinetics.' , misconception: 'The "constant" in rate constant means constant with respect to concentration and time — not with respect to temperature, which it depends on exponentially through the Arrhenius factor. A bath that drifts up by 3 °C makes the later data genuinely faster, bending the linear plots and inflating the fitted k rather than averaging out.' },

  // ---- electrochemistry experiments ----
  { id: 'p3-redox-001', tier: 3, topic: 'redox', skill: 'redox/electrolysis', q: 'In an electroplating experiment, plotting mass deposited against total charge gives a straight line whose slope equals…', opts: ['nF/M, straight from Faraday\'s law', 'I·t, the charge', 'F/M, no n', 'M/(nF), from Faraday'], a: 3, why: 'm = (M/nF)·Q — Faraday\'s law. From the slope you can extract n (or M), a favorite lab-data question.' , misconception: 'Faraday’s law is m = (M/nF)·Q, so a plot of m against Q has slope M/nF; quoting nF/M is the reciprocal — the slope you would get from plotting Q against m. The units settle it without any recall: a slope of mass over charge must come out in grams per coulomb, which M/nF does and nF/M does not.' },
  { id: 'p3-redox-002', topic: 'redox', q: 'A student builds a galvanic cell but forgets the salt bridge. The voltmeter shows…', opts: ['the full E° indefinitely', 'double the expected voltage', 'a brief reading, collapsing to 0', 'reversed polarity throughout'], a: 2, why: 'Charge builds up in each half-cell within moments — without ion flow to neutralize it, the reaction (and current) stops. The bridge completes the circuit ionically.' },

  // ---- qualitative analysis ----
  { id: 'p3-descriptive-001', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'Every flame test in the lab shows a yellow tinge. The most likely cause and remedy are…', opts: ['potassium contamination; take new samples', 'sodium everywhere; use cobalt-blue glass', 'a faulty burner; turn up the gas', 'the wire is simply far too hot'], a: 1, why: 'Traces of Na⁺ are everywhere (skin, glass, dust) and its emission is intense. Cobalt glass filters the yellow D-line so other colors (like K⁺ lilac) show through.' },
  { id: 'p3-descriptive-002', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'A white chloride precipitate dissolves when the mixture is heated, and re-forms on cooling. The cation is…', opts: ['Pb²⁺', 'Ag⁺', 'Hg₂²⁺', 'Ba²⁺'], a: 0, why: 'PbCl₂ is distinctly more soluble hot — the classic separation of Pb²⁺ from Ag⁺/Hg₂²⁺ within the chloride group.' },
  { id: 'p3-descriptive-003', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'To confirm NH₄⁺ in a solid, the standard test is…', opts: ['a flame test on the solid', 'add BaCl₂ solution to it', 'add AgNO₃ solution to it', 'warm with NaOH, test with damp red litmus'], a: 3, why: 'NH₄⁺ + OH⁻ → NH₃(g) on warming; ammonia turns damp red litmus blue (and has an unmistakable odor).' },
  { id: 'p3-descriptive-004', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'Adding dilute acid to an unknown solid produces a gas that pops with a lit splint. The gas — and a plausible solid — are…', opts: ['CO₂; a metal carbonate', 'O₂; a metal peroxide', 'H₂; an active metal', 'NH₃; an ammonium salt'], a: 2, why: 'The squeaky pop is hydrogen\'s signature (CO₂ extinguishes; O₂ relights a glowing splint; NH₃ needs base, not acid).' },

  // ---- organic technique ----
  { id: 'p3-organic-001', topic: 'organic', q: 'An impure organic solid melts at 118–124 °C while the pure compound melts sharply at 133 °C. This pattern is…', opts: ['simply impossible', 'a clear sign of decomposition', 'typical — impurities lower and broaden it', 'evidence only of a different compound entirely'], a: 2, why: 'Impurities disrupt the lattice (freezing-point depression) and melt unevenly → depressed, broadened range. A sharp mp at the literature value is the purity check.' },
  { id: 'p3-organic-002', topic: 'organic', q: 'A good recrystallization solvent dissolves the compound…', opts: ['well hot and well cold too', 'only with vigorous stirring', 'poorly both hot and cold', 'well hot, poorly cold'], a: 3, why: 'Dissolve everything hot; on slow cooling the pure compound crystallizes while impurities (present in small amounts) stay dissolved. Then wash with ice-cold solvent.' },
  { id: 'p3-organic-003', topic: 'organic', q: 'In a simple distillation, the thermometer bulb must sit…', opts: ['level with the side-arm, in the vapour', 'dipped down in the boiling liquid', 'well above the condenser', 'anywhere convenient'], a: 0, why: 'You want the temperature of the vapor actually leaving to the condenser — that\'s the boiling point of what you\'re collecting. In the liquid it reads the pot, not the distillate.' },

  // ---- separations & chromatography ----
  { id: 'p3-lab-004', topic: 'lab', skill: 'lab/separation', q: 'On a TLC plate the solvent front travels 5.0 cm and a spot travels 2.0 cm. Its Rf is…', opts: ['10', '2.5', '0.20', '0.40'], a: 3, why: 'Rf = spot distance / solvent-front distance = 2.0/5.0 = 0.40. Rf is characteristic of a compound in a fixed TLC system.' },
  { id: 'p3-lab-005', topic: 'lab', skill: 'lab/separation', q: 'On normal-phase silica TLC, a more POLAR compound generally has…', opts: ['a lower Rf', 'a higher Rf value', 'the same Rf value', 'no visible spot'], a: 0, why: 'Polar solutes adsorb strongly to polar silica and travel less, giving a lower Rf. Switching to a more polar eluent raises Rf.' },
  { id: 'p3-lab-006', topic: 'lab', skill: 'lab/separation', q: 'Gas chromatography separates a mixture primarily by differences in…', opts: ['ionic charge', 'volatility', 'visible colour', 'molar mass alone'], a: 1, why: 'In GC the more volatile components spend more time in the mobile gas phase and elute first (shorter retention time). HPLC/TLC separate by polarity instead.' },
  { id: 'p3-lab-007', tier: 3, topic: 'lab', skill: 'lab/separation', q: 'To extract a solute (K_D = 4 favouring the organic phase) most completely from water, it is best to use…', opts: ['one single large portion', 'a more dilute aqueous solution', 'several small portions', 'one single wash with more water'], a: 2, why: 'Repeated small extractions remove more total solute than one large extraction of the same total volume — a standard quantitative result from the partition equilibrium.' , misconception: 'Extraction is multiplicative, not additive: each contact with fresh solvent leaves the same FRACTION of solute behind, so n small portions leave that fraction to the nth power, while one large portion applies it only once. Assuming "the same total volume of solvent must remove the same total solute" is what makes the single big wash look equivalent — it is measurably worse.' },
  { id: 'p3-lab-008', topic: 'lab', q: 'A pH electrode is an example of a potentiometric sensor whose measured voltage varies…', opts: ['linearly with [H⁺] itself', 'randomly with time', 'with the temperature alone', 'linearly with pH, by Nernst'], a: 3, why: 'Ion-selective/pH electrodes are Nernstian: E ∝ log(activity), so E is linear in pH. Calibrate with buffers before use.' },

  // ---- measurement & uncertainty ----
  { id: 'p3-lab-009', topic: 'lab', skill: 'lab/measurement', q: 'You must add "about 20 mL" of a wash solvent (volume not critical) and separately "25.00 mL" of standard solution. Best glassware pair?', opts: ['cylinder for the wash, pipet for the standard', 'a buret for the wash and a graduated cylinder for the standard', 'two graduated beakers', 'a volumetric flask for both of them'], a: 0, why: 'Match precision to need: rough volume → cylinder (fast, ±0.5 mL); analytical volume → volumetric pipet (±0.03 mL). Using precise glassware for rough jobs wastes time; the reverse wrecks data.' },
  { id: 'p3-lab-010', topic: 'lab', q: 'A GHS pictogram showing a flame indicates the chemical is…', opts: ['corrosive', 'oxidizing', 'flammable', 'toxic'], a: 2, why: 'The flame pictogram = flammable; the flame-over-circle = oxidizer; skull = acute toxicity; the test-tubes-on-hand/surface = corrosive. Reading GHS/MSDS hazards is examinable lab safety.' },
  { id: 'p3-lab-011', tier: 3, topic: 'lab', skill: 'lab/error-analysis', q: 'A result depends on: mass 2.5000 g (±0.0002), volume 25.00 mL (±0.03), and titre 12.55 mL (±0.04). Which measurement limits the precision?', opts: ['the mass', 'the 12.55 mL titre', 'the 25.00 mL pipet', 'they are equal'], a: 1, why: 'Compare RELATIVE uncertainties: mass 0.008%, pipet 0.12%, titre 0.32%. The titre dominates — improving anything else is wasted effort. Percent uncertainties add for ×/÷.' , misconception: 'For a result built by multiplication and division it is the RELATIVE uncertainties that add, so comparing the raw ± figures picks the wrong culprit. The mass has the smallest absolute uncertainty (±0.0002 g) yet the best relative one, 0.008%, while the titre’s ±0.04 mL on 12.55 mL is 0.32% — forty times worse, and the only measurement worth improving.' },
];
