// Question Bank — Part I: multiple choice in CCC Part A / USNCO Part I style.
// All questions are original, written to match the format and difficulty of
// those exams. 10 per topic across 11 topics.

export interface BankMC {
  id: string;        // explicit and permanent — see QuizQ in framework.ts
  topic: string;     // an ExamTopicId (the coarse 12), not a ModuleId
  skill?: string | readonly string[];   // `<examTopic>/<skill>` from content/skills.ts; see QuizQ.skill
  tier?: 1 | 2 | 3 | 4;   // optional override; see tierOf() in content/registry.ts
  comps?: readonly ('ccc' | 'usnco' | 'cco' | 'icho')[];   // optional override
  q: string;
  opts: string[];
  a: number;
  why: string;
  /** Wrong-answer mental-model correction — shown below `why` when the student misses. See QuizQ. */
  misconception?: string;
  /** Second, handwritten explanation from another angle — the "Explain it differently" button. See QuizQ. */
  why2?: string;
}

export const PART1: BankMC[] = [
  // ================= STOICHIOMETRY =================
  { id: 'p1-stoich-001', topic: 'stoich', skill: 'stoich/percent-composition', q: 'What mass of oxygen is contained in 0.50 mol of CaCO₃?', opts: ['8 g', '16 g', '48 g', '24 g'], a: 3, why: '0.50 mol × 3 O per formula × 16 g/mol = 24 g.' },
  { id: 'p1-stoich-002', topic: 'stoich', q: '5.6 L of H₂ at STP (22.4 L/mol) reacts with excess N₂. Moles of NH₃ produced?', opts: ['0.25', '0.38', '0.17', '0.50'], a: 2, why: '5.6/22.4 = 0.25 mol H₂; ratio 2NH₃ : 3H₂ → 0.25 × 2/3 = 0.167 mol.' },
  { id: 'p1-stoich-003', topic: 'stoich', skill: 'stoich/percent-composition', q: 'Mass percent of water in MgSO₄·7H₂O (M = 246.5)?', opts: ['28%', '51%', '39%', '63%'], a: 1, why: '7 × 18.02 = 126.1 g of water per mole → 126.1/246.5 = 51%.' },
  { id: 'p1-stoich-004', topic: 'stoich', q: '25.0 mL of 0.200 M AgNO₃ is treated with excess NaCl. Mass of AgCl (M = 143.3) formed?', opts: ['0.72 g', '0.36 g', '1.43 g', '0.14 g'], a: 0, why: '0.0250 L × 0.200 M = 5.00×10⁻³ mol Ag⁺ → same moles AgCl → 0.717 g.' },
  { id: 'p1-stoich-005', tier: 3, topic: 'stoich', skill: 'stoich/empirical-formula', q: 'Complete combustion of a hydrocarbon gives 0.44 g CO₂ and 0.18 g H₂O. Its empirical formula is…', opts: ['CH', 'C₂H₃', 'CH₃', 'CH₂'], a: 3, why: '0.44/44 = 0.010 mol C; 0.18/18 = 0.010 mol H₂O → 0.020 mol H. C:H = 1:2 → CH₂.', misconception: 'Each mole of H₂O carries TWO moles of hydrogen; reading 0.010 mol H₂O as 0.010 mol H gives a 1:1 ratio and the answer CH. Note also that the oxygen in the products came from the O₂, not from the compound, so it never enters the empirical formula of a hydrocarbon.' },
  { id: 'p1-stoich-006', tier: 3, topic: 'stoich', skill: 'stoich/solution-conc', q: 'Concentrated HCl is 37% by mass with density 1.19 g/mL. Its molarity is about…', opts: ['6 M', '10 M', '12 M', '18 M'], a: 2, why: 'Per liter: 1190 g × 0.37 = 440 g HCl → 440/36.5 ≈ 12.1 mol.', misconception: 'Answering 10 M means taking 1000 g of solution per litre and ignoring the density: a litre of this acid weighs 1190 g, and the 37% is a fraction of that mass. A mass percent can never become a molarity without the density — that is the whole job the density does.' },
  { id: 'p1-stoich-007', tier: 3, topic: 'stoich', q: 'In acidic solution, one mole of Cr₂O₇²⁻ oxidizes how many moles of Fe²⁺?', opts: ['2', '6', '3', '1'], a: 1, why: 'Each Cr goes +6 → +3 (3 e⁻) × 2 Cr = 6 e⁻ gained; each Fe²⁺ gives 1 e⁻ → 6 Fe²⁺.', misconception: '3 is the electron change per chromium and 2 is the number of chromiums; the answer needs both. Balancing the half-equation for the whole Cr₂O₇²⁻ ion rather than for a single Cr atom is what keeps the factor of two, giving 6 e⁻ and therefore 6 Fe²⁺.' },
  { id: 'p1-stoich-008', topic: 'stoich', q: 'Which sample contains the same number of molecules as 16 g of O₂?', opts: ['22 g CO₂', '28 g N₂', '4.0 g H₂', '8.0 g SO₂'], a: 0, why: '16 g O₂ = 0.50 mol. CO₂: 22/44 = 0.50 mol ✓. (N₂ 1.0, H₂ 2.0, SO₂ 0.125 mol.)' },
  { id: 'p1-stoich-009', tier: 3, topic: 'stoich', skill: 'stoich/limiting-reagent', q: '10.0 g Al (27.0) reacts with 30.0 g Cl₂ (70.9) via 2Al + 3Cl₂ → 2AlCl₃. Mass of AlCl₃ (133.3) formed?', opts: ['56.4 g', '49.4 g', '28.2 g', '37.6 g'], a: 3, why: 'Al: 0.370/2 = 0.185; Cl₂: 0.423/3 = 0.141 → Cl₂ limiting. AlCl₃ = 0.423 × 2/3 = 0.282 mol × 133.3 = 37.6 g.', misconception: '49.4 g comes from assuming aluminium is limiting because it is the smaller number of moles. The comparison is moles divided by stoichiometric coefficient — 0.370/2 = 0.185 against 0.423/3 = 0.141 — so chlorine runs out first despite being present in greater molar amount.' },
  { id: 'p1-stoich-010', topic: 'stoich', skill: 'stoich/solution-conc', q: 'Drinking water contains 40 ppm Ca²⁺ (40.1 g/mol). Its molar concentration is about…', opts: ['4×10⁻² M', '1×10⁻³ M', '1×10⁻⁴ M', '4×10⁻⁵ M'], a: 1, why: '40 ppm ≈ 40 mg/L → 0.040 g ÷ 40.1 g/mol ≈ 1.0×10⁻³ mol/L.' },

  // ================= STATES OF MATTER & GASES =================
  { id: 'p1-states-001', topic: 'states', skill: 'states/real-gases', q: 'A real gas deviates most from ideal behavior at…', opts: ['high T, low P', 'low T, high P', 'high T, high P', 'low T, low P'], a: 1, why: 'Molecules close together (high P) and slow (low T): attractions and molecular volume both matter — the conditions approaching liquefaction.' },
  { id: 'p1-states-002', topic: 'states', skill: 'states/kmt', q: 'At the same temperature, He and SO₂ gases have the same…', opts: ['average kinetic energy', 'root-mean-square speed', 'density at that T', 'rate of effusion'], a: 0, why: 'Average translational KE = (3/2)kT depends only on T. Lighter He compensates with higher speed.' },
  { id: 'p1-states-003', topic: 'states', skill: 'states/gas-laws', q: 'A 2.0 L balloon at 300 K is heated to 600 K at constant pressure. New volume?', opts: ['1.0 L', '2.0 L', '8.0 L', '4.0 L'], a: 3, why: 'Charles\'s law: V ∝ T(K) → doubling T doubles V.' },
  { id: 'p1-states-004', topic: 'states', skill: 'states/gas-laws', q: 'Which gas is densest at STP?', opts: ['N₂', 'O₂', 'CO₂', 'CH₄'], a: 2, why: 'Same molar volume for all ideal gases → density tracks molar mass: CO₂ (44) wins.' },
  { id: 'p1-states-005', topic: 'states', skill: 'states/gas-laws', q: '2.0 mol He and 2.0 mol Ne exert 4.0 atm total. The partial pressure of He is…', opts: ['1.0 atm', '2.0 atm', '3.0 atm', '4.0 atm'], a: 1, why: 'Mole fraction ½ × 4.0 atm = 2.0 atm.' },
  { id: 'p1-states-006', topic: 'states', skill: 'states/kmt', q: 'An unknown gas effuses half as fast as He. Its molar mass is…', opts: ['16 g/mol', '8 g/mol', '2 g/mol', '32 g/mol'], a: 0, why: 'Graham: rate ∝ 1/√M → half the rate = 4× the mass = 16 g/mol.' },
  { id: 'p1-states-007', topic: 'states', skill: 'states/imf', q: 'Which molecule CANNOT act as a hydrogen-bond donor?', opts: ['CH₃OH', 'NH₃ gas', 'HF liquid', 'CH₃OCH₃'], a: 3, why: 'Dimethyl ether has no H bonded to N/O/F — it can accept H-bonds through its O but never donate.' },
  { id: 'p1-states-008', topic: 'states', skill: 'states/imf', q: 'Glycerol is far more viscous than ethanol chiefly because it…', opts: ['has the higher molar mass', 'is markedly denser', 'has three –OH groups to H-bond', 'is far more polarisable'], a: 2, why: 'Three hydroxyls per molecule create a 3-D hydrogen-bond network that resists flow.' },
  { id: 'p1-states-009', topic: 'states', skill: 'states/phase-behaviour', q: 'A solid is heated at a constant pressure BELOW its triple-point pressure. It will…', opts: ['melt, and then boil', 'sublime directly', 'remain solid throughout', 'become a supercritical fluid'], a: 1, why: 'Below the triple point pressure the liquid field is never crossed — solid converts directly to vapor (like CO₂ at 1 atm).' },
  { id: 'p1-states-010', topic: 'states', skill: 'states/real-gases', q: 'The measured pressure of a real gas is slightly LOWER than the ideal prediction because…', opts: ['the molecules occupy volume', 'the temperature quietly falls', 'the collisions are inelastic ones', 'attractions soften wall impacts'], a: 3, why: 'Molecules being pulled back by neighbors strike the walls less hard — the "a" correction in van der Waals.' },

  // ================= THERMODYNAMICS =================
  { id: 'p1-thermo-001', topic: 'thermo', skill: 'thermo/enthalpy', q: 'A reaction with ΔH > 0…', opts: ['absorbs heat', 'releases heat', 'is never spontaneous', 'has negative ΔS'], a: 0, why: 'Positive ΔH = endothermic. Spontaneity still depends on TΔS.' },
  { id: 'p1-thermo-002', topic: 'thermo', skill: 'thermo/enthalpy', q: 'On a heating curve, during the flat segment at the melting point the added energy goes into…', opts: ['the kinetic energy of the molecules', 'potential energy, breaking the lattice', 'raising the pressure of the system', 'nothing at all — it is simply lost'], a: 1, why: 'Temperature (average KE) is constant; energy is spent disrupting intermolecular attractions.' },
  { id: 'p1-thermo-003', topic: 'thermo', skill: 'thermo/state-functions', q: 'A gas absorbs 300 J of heat and does 100 J of work on the surroundings. ΔU = ?', opts: ['+400 J', '−200 J', '+200 J', '+300 J'], a: 2, why: 'ΔU = q + w = +300 + (−100) = +200 J. Work done BY the system is negative w.' },
  { id: 'p1-thermo-004', tier: 3, topic: 'thermo', skill: 'thermo/hess', q: 'ΔH°f: SO₂ = −296.8, SO₃ = −395.7 kJ/mol. ΔH° for 2SO₂ + O₂ → 2SO₃?', opts: ['−98.9 kJ', '+197.8 kJ', '−692.5 kJ', '−197.8 kJ'], a: 3, why: '2(−395.7) − 2(−296.8) = −791.4 + 593.6 = −197.8 kJ.', misconception: '−98.9 kJ is the value per mole of SO₃; the equation as written makes two, so the ΔH°f difference has to be multiplied by the coefficients. Every Hess-cycle answer is "per equation as written", and the coefficients are part of that equation.' },
  { id: 'p1-thermo-005', topic: 'thermo', skill: 'thermo/entropy', q: 'Which process has ΔS < 0?', opts: ['dissolving O₂ in water', 'evaporating diethyl ether', 'melting a block of ice', 'heating nitrogen gas up'], a: 0, why: 'A free gas becomes caged among water molecules — fewer accessible microstates. Gas dissolution is entropy-negative.' },
  { id: 'p1-thermo-006', topic: 'thermo', skill: 'thermo/gibbs', q: 'ΔH(vap) = 40.7 kJ/mol and ΔS(vap) = 109 J/mol·K for water. The boiling point is about…', opts: ['298 K', '373 K', '340 K', '410 K'], a: 1, why: 'At the transition ΔG = 0 → T = ΔH/ΔS = 40700/109 ≈ 373 K.' },
  { id: 'p1-thermo-007', tier: 3, topic: 'thermo', skill: 'thermo/bond-energies', q: 'Bond energies: H–I 299, H–H 436, I–I 151 kJ/mol. ΔH for 2HI → H₂ + I₂?', opts: ['−11 kJ', '+288 kJ', '+11 kJ', '−288 kJ'], a: 2, why: 'Break 2(299) = 598; form 436 + 151 = 587 → ΔH = 598 − 587 = +11 kJ (slightly endothermic).', misconception: 'ΔH = (bonds broken) − (bonds formed), and swapping the two gives −11 kJ — the same magnitude, so the arithmetic offers no warning. Breaking costs energy and forming releases it; check the sign against that, not against an expectation that reactions "ought" to be exothermic.' },
  { id: 'p1-thermo-008', tier: 3, topic: 'thermo', skill: 'thermo/enthalpy', q: '50 mL of 1.0 M HCl + 50 mL of 1.0 M NaOH raises the mixture (100 g, c = 4.18) by 6.8 °C. ΔH(neutralization) ≈ ?', opts: ['−28 kJ/mol', '−6.8 kJ/mol', '−114 kJ/mol', '−57 kJ/mol'], a: 3, why: 'q = 100 × 4.18 × 6.8 = 2.84 kJ for 0.050 mol H₂O formed → 56.9 kJ/mol released.', misconception: '0.050 mol of acid plus 0.050 mol of base makes 0.050 mol of water, not 0.100 — adding the two amounts together halves the answer to −28 kJ/mol. The 100 g is the thing being warmed and belongs only in q = mcΔT; the division at the end is by moles of reaction.' },
  { id: 'p1-thermo-009', topic: 'thermo', skill: 'thermo/state-functions', q: 'Which is NOT a state function?', opts: ['heat q', 'entropy', 'enthalpy', 'internal energy'], a: 0, why: 'q (and w) depend on the path taken; H, S, U, G depend only on the state. That path-dependence is why calorimetry needs controlled conditions.' },
  { id: 'p1-thermo-010', tier: 3, topic: 'thermo', skill: 'thermo/state-functions', q: 'An ideal gas expands into a vacuum (free expansion). Which is TRUE?', opts: ['q > 0 overall', 'w < 0 overall', 'ΔU = 0, ΔS > 0', 'ΔS = 0 exactly'], a: 2, why: 'No external pressure → w = 0; insulated → q = 0 → ΔU = 0 (T constant for ideal gas). But the volume increased: ΔS = nR ln(V₂/V₁) > 0. Entropy-driven.', misconception: 'q = 0 does not imply ΔS = 0. Clausius uses the <em>reversible</em> heat, dS = δq_rev/T, and free expansion is irreversible, so no heat crosses the boundary yet the entropy still rises by nR ln(V₂/V₁). The other trap is calling the work negative because the gas expanded — w = −P_extΔV, and expanding into a vacuum means P_ext = 0, so no work is done at all.' },

  // ================= KINETICS =================
  { id: 'p1-kinetics-001', topic: 'kinetics', q: 'In N₂ + 3H₂ → 2NH₃, H₂ is consumed at 0.30 M/s. NH₃ forms at…', opts: ['0.30 M/s', '0.10 M/s', '0.45 M/s', '0.20 M/s'], a: 3, why: 'Divide by coefficients: rate = 0.30/3 = 0.10 → NH₃ = 2 × 0.10 = 0.20 M/s.' },
  { id: 'p1-kinetics-002', topic: 'kinetics', skill: 'kinetics/rate-laws', q: 'Doubling [A] doubles the rate; doubling [B] changes nothing. The rate law is…', opts: ['k[A][B]', 'k[A]²', 'k[A]', 'k[B]'], a: 2, why: 'First order in A, zero order in B → rate = k[A]. Orders come from experiment, not the balanced equation.' },
  { id: 'p1-kinetics-003', topic: 'kinetics', skill: 'kinetics/rate-laws', q: 'Units of k for a second-order reaction (rate in M/s)?', opts: ['s⁻¹', 'M⁻¹s⁻¹', 'M·s⁻¹', 'M⁻²s⁻¹'], a: 1, why: 'rate = k[A]² → k = rate/[A]² = (M/s)/M² = M⁻¹s⁻¹. Order is readable from k\'s units.' },
  { id: 'p1-kinetics-004', topic: 'kinetics', skill: 'kinetics/integrated-rate', q: 'A first-order reactant falls to 12.5% of its initial value in 45 min. t½ = ?', opts: ['15 min', '22.5 min', '5.6 min', '11.25 min'], a: 0, why: '12.5% = (½)³ → three half-lives in 45 min → t½ = 15 min.' },
  { id: 'p1-kinetics-005', tier: 3, topic: 'kinetics', skill: 'kinetics/mechanisms', q: 'Rate = k[NO]²[O₂] is consistent with which mechanism?', opts: ['a slow 2NO → N₂O₂ step first, then fast with O₂', 'none at all — third order is impossible', 'a slow NO + O₂ step coming first', 'fast 2NO ⇌ N₂O₂, then slow with O₂'], a: 3, why: 'Substituting the pre-equilibrium ([N₂O₂] = K[NO]²) into the slow step\'s rate gives k′[NO]²[O₂]. Put the slow step first and O₂ drops out of the rate law (k[NO]², or k[NO][O₂] for the NO + O₂ version) — the rate law only ever sees the rate-determining step and whatever precedes it. Mechanisms can\'t be proven — only shown consistent.', misconception: 'If the 2NO step were the slow one, O₂ could not appear in the rate law at all: a rate law sees only the rate-determining step and the equilibria that precede it, so anything happening after the bottleneck is invisible to it. Matching [NO]² to a step that consumes two NO, without asking where the [O₂] comes from, is the trap.' },
  { id: 'p1-kinetics-006', topic: 'kinetics', skill: 'kinetics/catalysis', q: 'A catalyst changes which quantity?', opts: ['ΔH°', 'K', 'Ea', 'ΔG°'], a: 2, why: 'Only the barrier. All thermodynamic quantities — and hence the equilibrium position — are untouched.' },
  { id: 'p1-kinetics-007', tier: 3, topic: 'kinetics', skill: 'kinetics/arrhenius', q: 'A rate constant doubles between 25 °C and 35 °C. Ea ≈ ?', opts: ['13 kJ/mol', '53 kJ/mol', '27 kJ/mol', '106 kJ/mol'], a: 1, why: 'ln2 = (Ea/R)(1/298 − 1/308) → Ea = 0.693 × 8.314 / 1.09×10⁻⁴ ≈ 53 kJ/mol — the origin of the "doubles per 10 °C" rule.', misconception: 'Ea comes from the difference of RECIPROCAL temperatures, 1/298 − 1/308 = 1.09×10⁻⁴ K⁻¹, not from the 10 K gap itself — substituting ΔT = 10 directly, or working in Celsius, is what produces the neighbouring answers. And the "doubles every 10 °C" rule is a consequence of Ea happening to be ≈50 kJ/mol near room temperature, not a law.' },
  { id: 'p1-kinetics-008', topic: 'kinetics', skill: 'kinetics/integrated-rate', q: 'For a ZERO-order reaction, the half-life…', opts: ['is proportional to [A]₀', 'is constant', 'is inversely proportional to [A]₀', 'is infinite'], a: 0, why: 't½ = [A]₀/2k — more material takes proportionally longer. (1st: constant; 2nd: inverse.)' },
  { id: 'p1-kinetics-009', topic: 'kinetics', skill: 'kinetics/mechanisms', q: 'The overall rate of a multistep reaction is set by…', opts: ['the first step always', 'the fastest step', 'the sum of all steps', 'the slowest step'], a: 3, why: 'The rate-determining step is the kinetic bottleneck, like the slowest tollbooth on a highway.' },
  { id: 'p1-kinetics-010', topic: 'kinetics', skill: 'kinetics/integrated-rate', q: 'A radioisotope has t½ = 15 y. A sample decays to 1/16 of its activity in…', opts: ['30 y', '60 y', '45 y', '240 y'], a: 1, why: '1/16 = (½)⁴ → 4 half-lives = 60 years. Radioactive decay is strictly first order.' },

  // ================= EQUILIBRIUM =================
  { id: 'p1-equilibrium-001', topic: 'equilibrium', q: 'For CaCO₃(s) ⇌ CaO(s) + CO₂(g), the equilibrium expression is…', opts: ['[CO₂][CaO]/[CaCO₃]', '[CO₂], the only gas', '[CaO][CO₂]', '1/[CO₂]'], a: 1, why: 'Pure solids are omitted → K = [CO₂]. The equilibrium CO₂ pressure depends only on T.' },
  { id: 'p1-equilibrium-002', topic: 'equilibrium', q: 'For PCl₅(g) ⇌ PCl₃(g) + Cl₂(g), Kp equals…', opts: ['Kc(RT)', 'Kc', 'Kc/(RT)', 'Kc(RT)²'], a: 0, why: 'Kp = Kc(RT)^Δn with Δn(gas) = 2 − 1 = +1.' },
  { id: 'p1-equilibrium-003', topic: 'equilibrium', q: '0.50 M HA with Ka = 2×10⁻⁶. Equilibrium [H⁺] ≈ ?', opts: ['5×10⁻⁴ M', '1×10⁻⁶ M', '2×10⁻³ M', '1×10⁻³ M'], a: 3, why: 'x = √(KaC) = √(1×10⁻⁶) = 1×10⁻³ M (0.2% ionized — approximation excellent).' },
  { id: 'p1-equilibrium-004', tier: 3, topic: 'equilibrium', q: 'K = 16 for A ⇌ 2B. K for B ⇌ ½A is…', opts: ['1/16', '4', '1/4', '1/256'], a: 2, why: 'Reverse → 1/16; halve → square root → 1/4.', misconception: '1/16 answers "reverse the equation" and 4 answers "halve it"; the new equation does both, so K must be inverted AND square-rooted. Performing one operation and stopping is the usual slip — K_new = K^(−1/2) = 16^(−1/2) = 1/4.' },
  { id: 'p1-equilibrium-005', tier: 3, topic: 'equilibrium', q: 'An exothermic equilibrium is heated at constant volume. Which happens?', opts: ['K increases, shifts right', 'K decreases, shifts left', 'K constant, shifts left', 'no change'], a: 1, why: 'Heat is a "product" of exothermic reactions — raising T consumes product, and because the stress is thermal, K itself falls.', misconception: 'Temperature is the one stress that changes K itself, and carrying over the habit from concentration and pressure changes — where the position shifts but K is fixed — produces "K constant, shifts left". K depends on T through ΔG° = −RT ln K, so heating an exothermic reaction genuinely lowers the constant.' },
  { id: 'p1-equilibrium-006', tier: 3, topic: 'equilibrium', q: 'Molar solubility of BaSO₄ (Ksp = 1.1×10⁻¹⁰) in 0.10 M Na₂SO₄?', opts: ['1.1×10⁻⁹ M', '1.0×10⁻⁵ M', '1.1×10⁻¹¹ M', '3.3×10⁻⁶ M'], a: 0, why: '[SO₄²⁻] ≈ 0.10 → s = Ksp/0.10 = 1.1×10⁻⁹ M — ten-thousand-fold suppression (common ion).', misconception: '1.0×10⁻⁵ M is the solubility in pure water: reaching for √Ksp ignores the sulfate that is already there. With 0.10 M SO₄²⁻ supplied by the Na₂SO₄, s = Ksp/[SO₄²⁻], and what BaSO₄ itself contributes to the sulfate is negligible beside 0.10 M.' },
  { id: 'p1-equilibrium-007', topic: 'equilibrium', q: 'K = 50; the reaction mixture currently has Q = 80. The system will…', opts: ['make more product instead', 'change K to equal 80', 'stay exactly as it is', 'make more reactant'], a: 3, why: 'Q > K → too much product → net reverse reaction until Q falls to 50.' },
  { id: 'p1-equilibrium-008', topic: 'equilibrium', q: 'For MX₂ with Ksp = 4×10⁻¹², the molar solubility is…', opts: ['2×10⁻⁶ M', '1.6×10⁻⁴ M', '1×10⁻⁴ M', '4×10⁻⁶ M'], a: 2, why: 'Ksp = (s)(2s)² = 4s³ → s = (1×10⁻¹²)^(1/3) = 1×10⁻⁴ M.' },
  { id: 'p1-equilibrium-009', topic: 'equilibrium', q: 'More solid salt is added to an already SATURATED solution. The dissolved concentration…', opts: ['increases steadily', 'stays the same', 'decreases steadily', 'doubles at once'], a: 1, why: 'The solution is already at Q = Ksp; extra solid just sits there. Solids never appear in the equilibrium expression.' },
  { id: 'p1-equilibrium-010', topic: 'equilibrium', q: 'For an endothermic reaction, a plot of ln K vs 1/T is…', opts: ['a line with positive slope', 'flat', 'a parabola', 'a line with negative slope'], a: 3, why: 'van \'t Hoff: ln K = −(ΔH°/R)(1/T) + C. ΔH° > 0 makes the slope −ΔH°/R negative: K grows as T rises (1/T falls).' },

  // ================= ACIDS & BASES =================
  { id: 'p1-acids-001', topic: 'acids', q: 'The conjugate base of HSO₄⁻ is…', opts: ['H₂SO₄', 'OH⁻', 'HSO₃⁻', 'SO₄²⁻'], a: 3, why: 'Remove one H⁺: HSO₄⁻ → SO₄²⁻. (H₂SO₄ is its conjugate acid.)' },
  { id: 'p1-acids-002', tier: 3, topic: 'acids', skill: 'acids/ph-calc', q: 'The pH of 1×10⁻⁸ M HCl is…', opts: ['8.0', '7.02', '6.98', '6.0'], a: 2, why: 'Water\'s own autoionization dominates at this dilution — the answer must stay (barely) below 7. Acid can\'t give a basic pH!', misconception: 'pH = −log(1×10⁻⁸) = 8 treats the added acid as the only source of H⁺, and produces the absurdity of acid making water basic. Below about 10⁻⁶ M the water\'s own 10⁻⁷ M dominates the balance, so the answer must sit just below 7 — and can never rise above it, however dilute the acid gets.', why2: 'The exact route is a charge balance rather than a rule of thumb. Electroneutrality demands [H⁺] = [Cl⁻] + [OH⁻], with [Cl⁻] = 1×10⁻⁸ fixed by the acid added and [OH⁻] = Kᵥ/[H⁺]. Writing x = [H⁺] gives x² − 10⁻⁸x − 10⁻¹⁴ = 0, so x = 1.05×10⁻⁷ M and <b>pH = 6.98</b>. The structure of the answer is worth keeping: [H⁺] is the water\'s 1.00×10⁻⁷ nudged up by roughly half the acid added, because adding H⁺ suppresses the water\'s own ionisation and the two contributions are not simply summed. The same equation run at 10⁻⁶ M returns pH 6.98 → 6.02, and by 10⁻⁵ M the water term has become irrelevant and −log C is accurate again.' },
  { id: 'p1-acids-003', topic: 'acids', skill: 'acids/strong-weak', q: 'Ka(HCN) = 6.2×10⁻¹⁰. Kb of CN⁻ = ?', opts: ['6.2×10⁻¹⁰', '1.6×10⁻⁵', '6.2×10⁻²⁴', '1.6×10⁻⁹'], a: 1, why: 'Kb = Kw/Ka = 10⁻¹⁴ / 6.2×10⁻¹⁰ = 1.6×10⁻⁵ — a fairly strong weak base (weak acid ⇒ stronger conjugate).' },
  { id: 'p1-acids-004', topic: 'acids', skill: 'acids/buffers', q: 'A buffer is 0.20 M in HA (pKa 4.00) and 0.10 M in A⁻. Its pH is…', opts: ['3.70', '4.00', '4.30', '3.00'], a: 0, why: 'pH = 4.00 + log(0.10/0.20) = 4.00 − 0.30 = 3.70. More acid than base → below pKa.' },
  { id: 'p1-acids-005', topic: 'acids', q: 'Which is best described as a Lewis acid?', opts: ['NH₃', 'Cl⁻', 'H₂O', 'BF₃'], a: 3, why: 'Boron\'s empty p orbital accepts an electron pair — the definition of a Lewis acid. NH₃/H₂O/Cl⁻ are donors (bases).' },
  { id: 'p1-acids-006', tier: 3, topic: 'acids', skill: ['acids/strong-weak', 'acids/ph-calc'], q: 'When a weak acid solution is diluted 10×, its percent ionization…', opts: ['decreases 10×', 'is unchanged', 'increases', 'becomes zero'], a: 2, why: 'Dilution drops Q below Ka → equilibrium shifts toward more dissociation (even though pH rises toward 7).', misconception: 'The [H⁺] does fall on dilution, but the <em>fraction</em> ionised rises — Ostwald\'s dilution law — and reading "more dilute, so less ionised" conflates the amount with the proportion. Le Chatelier on the added water favours the side with more dissolved particles, which is the dissociated one.' },
  { id: 'p1-acids-007', topic: 'acids', skill: 'acids/polyprotic', q: 'pKa1 = 6.35 and pKa2 = 10.33 for carbonic acid. The pH of a NaHCO₃ solution ≈ ?', opts: ['6.35', '8.34', '10.33', '7.00'], a: 1, why: 'Amphoteric species: pH ≈ (pKa1 + pKa2)/2 = 8.34, nearly independent of concentration.' },
  { id: 'p1-acids-008', topic: 'acids', skill: 'acids/strong-weak', q: 'The strongest acid among these oxyacids is…', opts: ['HClO₄', 'HClO₂', 'HClO₃', 'HClO'], a: 0, why: 'Each extra O withdraws density and delocalizes the conjugate base\'s charge: HClO₄ is one of the strongest acids known.' },
  { id: 'p1-acids-009', topic: 'acids', skill: 'acids/titration-curves', q: 'At the equivalence point of a weak BASE titrated with strong ACID, the pH is…', opts: ['7', 'above 7', 'equal to pKb', 'below 7'], a: 3, why: 'Only the conjugate ACID remains (e.g., NH₄⁺) — a weakly acidic solution. Mirror image of the weak-acid case.' },
  { id: 'p1-acids-010', topic: 'acids', skill: 'acids/strong-weak', q: 'A 0.1 M solution of Al(NO₃)₃ is…', opts: ['neutral', 'acidic', 'basic', 'amphoteric'], a: 1, why: 'The small, highly charged Al³⁺(aq) polarizes its water ligands: [Al(H₂O)₆]³⁺ donates H⁺ (Ka ≈ 10⁻⁵). NO₃⁻ is neutral.' },

  // ================= ELECTROCHEMISTRY & REDOX =================
  { id: 'p1-redox-001', topic: 'redox', skill: 'redox/oxidation-states', q: 'The oxidation number of S in S₂O₃²⁻ (thiosulfate) is…', opts: ['+6', '+2', '+4', '−2'], a: 1, why: '2x + 3(−2) = −2 → x = +2 (an average; the two S atoms are actually inequivalent).' },
  { id: 'p1-redox-002', topic: 'redox', skill: 'redox/balancing', q: 'Balancing MnO₄⁻ → Mn²⁺ in acid requires…', opts: ['5e⁻ and 8H⁺ on the left', '3e⁻ and 4H⁺ on the left', '5e⁻ on the right', '7e⁻ and 8H⁺'], a: 0, why: 'MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O. Balance O with water, H with H⁺, charge with electrons.' },
  { id: 'p1-redox-003', topic: 'redox', skill: 'redox/cell-potential', q: 'E°: Ag⁺/Ag = +0.80 V, Zn²⁺/Zn = −0.76 V. E°cell of the spontaneous cell = ?', opts: ['0.04 V', '0.84 V', '−1.56 V', '1.56 V'], a: 3, why: 'E° = E°(cathode) − E°(anode) = 0.80 − (−0.76) = 1.56 V. Ag⁺ is reduced, Zn oxidized.' },
  { id: 'p1-redox-004', tier: 3, topic: 'redox', skill: 'redox/electrolysis', q: 'Time to deposit 0.050 mol of Cu from Cu²⁺ at 2.0 A?', opts: ['40 min', '160 min', '80 min', '20 min'], a: 2, why: 'Q = 0.050 × 2 × 96485 = 9650 C → t = 9650/2.0 = 4825 s ≈ 80 min.', misconception: '40 minutes is the n = 1 answer. The electron count comes from the half-equation Cu²⁺ + 2e⁻ → Cu, not from the moles of metal deposited, so the charge required is 0.050 × 2 × 96485 C. Any Faraday-law question turns on reading n off the half-equation first.' },
  { id: 'p1-redox-005', tier: 3, topic: 'redox', skill: 'redox/cell-potential', q: 'Which species can disproportionate in aqueous solution?', opts: ['Cu²⁺', 'Cu⁺', 'Zn²⁺', 'Ag⁺'], a: 1, why: '2Cu⁺ → Cu + Cu²⁺ is spontaneous (E°(Cu⁺/Cu) = +0.52 > E°(Cu²⁺/Cu⁺) = +0.16) — Cu⁺ is unstable in water.', misconception: 'Disproportionation requires an element in an INTERMEDIATE oxidation state, with somewhere to go both up and down. Cu²⁺ is copper\'s top common aqueous state, and Zn²⁺ and Ag⁺ have no accessible higher one — only Cu⁺ sits between Cu(0) and Cu(II), and it goes because E°(Cu⁺/Cu) exceeds E°(Cu²⁺/Cu⁺).' },
  { id: 'p1-redox-006', tier: 3, topic: 'redox', skill: 'redox/nernst', q: 'The cathode ion of a cell (n = 2) is diluted tenfold. The cell voltage…', opts: ['falls ~30 mV', 'rises 59 mV', 'falls 59 mV', 'is unchanged'], a: 0, why: 'Nernst: ΔE = −(0.0592/2)·log(10) = −29.6 mV. Less reactant at the cathode → less push.', misconception: '59 mV per decade is the n = 1 figure; with two electrons transferred each factor of ten is worth only 29.6 mV. The sign is the other half — the diluted ion is at the CATHODE, where it is a reactant, so removing it lowers the driving force. The same dilution at the anode would have raised the voltage.' },
  { id: 'p1-redox-007', topic: 'redox', skill: 'redox/electrolysis', q: 'In an ELECTROLYTIC cell, the cathode is…', opts: ['positive, oxidation', 'negative, oxidation', 'positive, reduction', 'negative, reduction'], a: 3, why: 'Reduction ALWAYS happens at the cathode. In electrolysis the power supply forces it, marking that electrode negative (opposite sign to galvanic).' },
  { id: 'p1-redox-008', topic: 'redox', skill: 'redox/cell-potential', q: 'From a standard reduction table, the strongest REDUCING agent is the species with…', opts: ['the most positive E°, left side', 'the most positive E°, right side', 'the most negative E°, right side', 'E° = 0'], a: 2, why: 'Strong reducers are eager to be oxidized — the reduced form (right side) of the most negative couple, e.g., Li(s).' },
  { id: 'p1-redox-009', topic: 'redox', skill: 'redox/cell-potential', q: 'Zinc blocks protect ship hulls because zinc…', opts: ['is a good deal cheaper than iron', 'is oxidised first, corroding sacrificially', 'forms a physical barrier coating', 'is a poorer electrical conductor than iron'], a: 1, why: 'Zn (E° = −0.76) oxidizes preferentially to Fe (−0.44), making the hull the cathode. "Sacrificial anode."' },
  { id: 'p1-redox-010', topic: 'redox', skill: 'redox/cell-potential', q: 'For a 2-electron cell with E° = +1.10 V, ΔG° ≈ ?', opts: ['−106 kJ', '−53 kJ', '+212 kJ', '−212 kJ'], a: 3, why: 'ΔG° = −nFE° = −2 × 96485 × 1.10 ≈ −212 kJ/mol. Positive E° ⇔ negative ΔG° ⇔ K > 1.' },

  // ================= ATOMIC STRUCTURE =================
  { id: 'p1-atomic-001', topic: 'atomic', skill: 'atomic/spectra', q: 'The energy of a 400 nm photon is about…', opts: ['1.6 eV', '5.0 eV', '3.1 eV', '0.4 eV'], a: 2, why: 'E(eV) ≈ 1240/λ(nm) = 1240/400 = 3.1 eV (violet light).' },
  { id: 'p1-atomic-002', topic: 'atomic', skill: 'atomic/quantum-numbers', q: 'Which quantum number combination is allowed?', opts: ['n=2, ℓ=2, mℓ=1', 'n=3, ℓ=1, mℓ=−2', 'n=1, ℓ=1, mℓ=0', 'n=4, ℓ=2, mℓ=−2'], a: 3, why: 'Need ℓ ≤ n−1 and |mℓ| ≤ ℓ: only n=4, ℓ=2, mℓ=−2 (a 4d orbital) passes both tests.' },
  { id: 'p1-atomic-003', topic: 'atomic', skill: 'atomic/configuration', q: 'Ground-state configuration of Cu (Z = 29)?', opts: ['[Ar]4s¹3d¹⁰', '[Ar]4s²3d⁹', '[Ar]3d¹¹', '[Ar]4s²3d⁸4p¹'], a: 0, why: 'The filled d-shell exception: 4s¹3d¹⁰ is lower in energy than 4s²3d⁹. Same story for Cr (4s¹3d⁵).' },
  { id: 'p1-atomic-004', tier: 3, topic: 'atomic', skill: 'atomic/periodic-trends', q: 'Which has the highest first ionization energy?', opts: ['Na', 'Si', 'Al', 'Mg'], a: 1, why: 'IE rises across the period; the Mg→Al dip (new 3p subshell) doesn\'t overcome Si\'s extra nuclear charge. Order: Na < Al < Mg < Si.', misconception: 'Knowing that Al dips below Mg is correct, but the dip reorders only that adjacent pair — it does not lift Mg above everything further along the period. Silicon has two more protons in the same shell and beats all three: Na < Al < Mg < Si.' },
  { id: 'p1-atomic-005', topic: 'atomic', skill: 'atomic/periodic-trends', q: 'Rank by radius: S²⁻, Cl⁻, K⁺ (all 18 e⁻)…', opts: ['K⁺ > Cl⁻ > S²⁻', 'Cl⁻ > S²⁻ > K⁺', 'S²⁻ > Cl⁻ > K⁺', 'all equal'], a: 2, why: 'Isoelectronic: fewer protons hold the same 18 electrons more loosely. S (16p) largest, K (19p) smallest.' },
  { id: 'p1-atomic-006', topic: 'atomic', skill: 'atomic/pes', q: 'How many peaks appear in the photoelectron spectrum of aluminum?', opts: ['3', '4', '13', '5'], a: 3, why: 'One peak per subshell: 1s, 2s, 2p, 3s, 3p = 5 peaks (areas 2:2:6:2:1).' },
  { id: 'p1-atomic-007', topic: 'atomic', skill: 'atomic/spectra', q: 'Compared with the Balmer series, Lyman-series photons are…', opts: ['higher energy, UV', 'lower in energy, infrared', 'identical in energy', 'in the visible'], a: 0, why: 'Transitions ending at n=1 span bigger energy gaps than those ending at n=2 → all Lyman lines are ultraviolet.' },
  { id: 'p1-atomic-008', tier: 3, topic: 'atomic', skill: 'atomic/periodic-trends', q: 'An element has IE₁–IE₄ of 738, 1451, 7733, 10 540 kJ/mol. It belongs to group…', opts: ['1', '2', '13', '14'], a: 1, why: 'The huge jump comes after removing TWO electrons — the third digs into the core. Two valence electrons = group 2 (this is Mg).' , misconception: 'The break in the sequence comes AFTER the last valence electron has gone, so the jump between IE₂ and IE₃ means two valence electrons, not three. Reading the group number off the ionisation that jumps (the third) is an off-by-one that turns every group 2 element into a group 13 one.' },
  { id: 'p1-atomic-009', topic: 'atomic', skill: 'atomic/quantum-numbers', q: 'The 3d_xy orbital has how many nodal planes?', opts: ['0', '1', '2', '3'], a: 2, why: 'Angular nodes = ℓ = 2: the xz and yz planes both have zero amplitude, giving the four-lobed shape.' },
  { id: 'p1-atomic-010', topic: 'atomic', skill: 'atomic/periodic-trends', q: 'Moving Na → Cl across period 3, Z_eff on the valence electrons…', opts: ['rises steadily across the period', 'decreases across', 'stays essentially constant', 'falls once the 3p subshell starts filling'], a: 0, why: 'Each step adds one proton while same-shell electrons shield it only partially (Slater: ~0.35 each) → net pull climbs by roughly +0.65 per element, Na 2.51 to Cl 6.12. Steadily, not by a full +1 — the added electron does shield a little. This single trend explains radius, IE, EN.' },

  // ================= BONDING & STRUCTURE =================
  { id: 'p1-bonding-001', topic: 'bonding', skill: 'bonding/lewis-vsepr', q: 'The sulfite ion SO₃²⁻ is…', opts: ['trigonal planar, 120°', 'T-shaped, 90°', 'trigonal pyramidal', 'tetrahedral, 109.5°'], a: 2, why: 'S has 3 bonds + 1 lone pair (26 valence e⁻) → AX₃E, pyramidal like NH₃. Sulfate (no lone pair) is the tetrahedral one.' },
  { id: 'p1-bonding-002', topic: 'bonding', skill: 'bonding/hybridisation', q: 'Hybridization of carbon in CO₂?', opts: ['unhybridized', 'sp²', 'sp³', 'sp'], a: 3, why: 'Two σ-domains (two double bonds, no lone pairs) → sp, linear. The two π bonds use the remaining p orbitals.' },
  { id: 'p1-bonding-003', topic: 'bonding', skill: 'bonding/lewis-vsepr', q: 'Which species requires resonance structures to describe properly?', opts: ['CO₃²⁻', 'NH₃ only', 'CH₄ only', 'H₂O only'], a: 0, why: 'The double bond is delocalized over three equivalent C–O positions (bond order 4/3). One Lewis drawing can\'t show that.' },
  { id: 'p1-bonding-004', tier: 3, topic: 'bonding', skill: 'bonding/lewis-vsepr', q: 'The preferred Lewis structure of cyanate, OCN⁻, places the −1 formal charge on…', opts: ['carbon', 'oxygen, the most electronegative', 'nitrogen', 'spread equally by symmetry'], a: 1, why: '⁻O–C≡N with FC(O) = −1 wins: negative charge belongs on the MOST electronegative atom.' , misconception: 'Resonance forms are not automatically equal contributors — they are only averaged evenly when they are genuinely equivalent, as in NO₃⁻ or CO₃²⁻. The three forms of OCN⁻ differ in which atom carries the −1, so the structure that puts it on the most electronegative atom dominates; assuming the charge is smeared out "by symmetry" skips the formal-charge comparison that decides the question.' },
  { id: 'p1-bonding-005', topic: 'bonding', skill: 'bonding/lewis-vsepr', q: 'Correct bond-angle order?', opts: ['H₂O > NH₃ > CH₄', 'NH₃ > CH₄ > H₂O', 'CH₄ > NH₃ > H₂O', 'all 109.5°'], a: 2, why: '109.5° > 107° > 104.5° — each lone pair compresses the bonding angles a bit more.' },
  { id: 'p1-bonding-006', tier: 3, topic: 'bonding', skill: 'bonding/mo-theory', q: 'Bond order of N₂⁻ (11 valence electrons)?', opts: ['3', '1.5', '2', '2.5'], a: 3, why: 'The 11th electron enters antibonding π* → BO = (8−3)/2 = 2.5. Weaker and longer than N₂.' , misconception: 'Adding an electron only strengthens a bond if it lands in a bonding orbital, and for N₂ every bonding orbital is already full — the extra electron has nowhere to go but π*. Each electron is worth half a unit of bond order, so N₂⁻ falls to 2.5, not to 2: an antibonding electron cancels half a bond, never a whole one.' },
  { id: 'p1-bonding-007', topic: 'bonding', skill: 'bonding/polarity', q: 'Which molecule is polar?', opts: ['NF₃', 'CF₄', 'BF₃', 'XeF₂'], a: 0, why: 'NF₃ is pyramidal — bond dipoles and the lone pair don\'t cancel. The others are symmetric (trigonal planar, tetrahedral, linear).' },
  { id: 'p1-bonding-008', topic: 'bonding', skill: 'bonding/bond-properties', q: 'Number of σ and π bonds in HCN?', opts: ['3σ, 1π', '2σ, 2π', '1σ, 3π', '2σ, 1π'], a: 1, why: 'H–C is 1σ; C≡N is 1σ + 2π → total 2σ, 2π.' },
  { id: 'p1-bonding-009', topic: 'bonding', q: 'MgO has a much higher melting point than NaCl mainly because…', opts: ['Mg is the heavier metal', 'MgO is a covalent network solid, like SiO₂', '±2 charges quadruple the lattice energy', 'Cl⁻ is much more polarisable'], a: 2, why: 'Lattice energy ∝ q₁q₂/r: (2+)(2−) vs (1+)(1−) gives ~4× the attraction (plus smaller ions). 2852 °C vs 801 °C.' },
  { id: 'p1-bonding-010', topic: 'bonding', skill: 'bonding/bond-properties', q: 'The C–O bond length in CO₃²⁻ compared with a normal C–O single and C=O double bond is…', opts: ['between the two, all identical', 'equal to the double bond', 'equal to the single bond', 'alternating short and long'], a: 0, why: 'Resonance averages the bonds to order 4/3 — experiment finds three identical intermediate-length bonds, the classic evidence for delocalization.' },

  // ================= DESCRIPTIVE & INORGANIC =================
  { id: 'p1-descriptive-001', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'A lilac/violet flame test indicates…', opts: ['Na⁺', 'Cu²⁺', 'Ca²⁺', 'K⁺'], a: 3, why: 'K⁺ burns lilac (view through cobalt glass to filter the ever-present yellow sodium flare).' },
  { id: 'p1-descriptive-002', topic: 'descriptive', skill: 'descriptive/periodic-groups', q: 'Which oxide dissolves in BOTH strong acid and strong base?', opts: ['Na₂O solid', 'MgO solid', 'Al₂O₃', 'SO₃ gas'], a: 2, why: 'Al₂O₃ is amphoteric: acid → Al³⁺; base → aluminate [Al(OH)₄]⁻. Same family: ZnO, BeO, PbO, SnO.' },
  { id: 'p1-descriptive-003', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'A gas that turns limewater milky is…', opts: ['H₂', 'CO₂', 'O₂', 'NH₃'], a: 1, why: 'CO₂ + Ca(OH)₂ → CaCO₃(s) white precipitate. (Excess CO₂ re-dissolves it as Ca(HCO₃)₂.)' },
  { id: 'p1-descriptive-004', topic: 'descriptive', skill: 'descriptive/periodic-groups', q: 'The brown gas produced when copper reacts with concentrated nitric acid is…', opts: ['NO₂', 'NO', 'N₂O', 'HNO₃ vapor'], a: 0, why: 'Concentrated HNO₃ → brown NO₂; DILUTE gives colorless NO (which browns in air). A classic observation pair.' },
  { id: 'p1-descriptive-005', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'Which precipitate dissolves in aqueous ammonia?', opts: ['Fe(OH)₃', 'BaSO₄', 'PbS', 'AgCl'], a: 3, why: 'AgCl + 2NH₃ → [Ag(NH₃)₂]⁺ + Cl⁻ — complex-ion formation pulls the dissolution. (AgI resists: too insoluble.)' },
  { id: 'p1-descriptive-006', topic: 'descriptive', skill: 'descriptive/periodic-groups', q: 'Reactivity of the alkali metals with water increases…', opts: ['up the group', 'toward the middle', 'down the group', 'not at all'], a: 2, why: 'IE falls down the group — Cs loses its electron easiest. Li fizzes, Na darts, K ignites, Cs detonates.' },
  { id: 'p1-descriptive-007', topic: 'descriptive', skill: 'descriptive/qualitative-analysis', q: 'During a dichromate titration of Fe²⁺, the solution color change at the endpoint region involves Cr species going…', opts: ['yellow → blue', 'orange → green', 'purple → colorless', 'green → orange'], a: 1, why: 'Cr₂O₇²⁻ (orange) is reduced to Cr³⁺ (green). Purple→colorless is permanganate\'s signature instead.' },
  { id: 'p1-descriptive-008', topic: 'descriptive', q: 'Industrial ammonia synthesis (Haber) uses roughly…', opts: ['450 °C, 200 atm, Fe', '25 °C and 1 atm', '1000 °C under vacuum', '0 °C and 500 atm'], a: 0, why: 'A compromise: high P pushes 4 gas mol → 2; moderate-high T for rate (K would prefer cold); iron catalyst bridges the gap.' },
  { id: 'p1-descriptive-009', topic: 'descriptive', skill: 'descriptive/periodic-groups', q: 'Which pair shows a diagonal relationship?', opts: ['Li and Na', 'B and C', 'Be and Mg', 'Li and Mg'], a: 3, why: 'Li/Mg (also Be/Al, B/Si): similar charge density gives similar chemistry — e.g., both Li and Mg form nitrides directly.' },
  { id: 'p1-descriptive-010', tier: 3, topic: 'descriptive', skill: 'descriptive/periodic-groups', q: 'Chlorine water is added to KI solution with a little hexane. The hexane layer turns…', opts: ['colourless', 'brown/purple', 'pale green', 'deep blue'], a: 1, why: 'Cl₂ displaces I₂ (halogen activity falls down the group); I₂ partitions into hexane with its violet color.' , misconception: 'The organic layer reports the colour of the halogen that has been DISPLACED, not of the reagent added. Iodine is non-polar and partitions strongly into hexane, so the layer takes the violet-brown of I₂; answering "pale green" quotes the colour of the chlorine you poured in, and "colourless" assumes the iodine stays in the water it was born in.' },

  // ================= ORGANIC =================
  { id: 'p1-organic-001', topic: 'organic', skill: 'organic/nomenclature', q: 'The IUPAC name of (CH₃)₂CHCH₂OH is…', opts: ['2-methylpropan-1-ol', 'butan-1-ol, unbranched', 'butan-2-ol, unbranched', '2-methylpropan-2-ol'], a: 0, why: 'Longest chain bearing the OH is propanol; a methyl sits on C2 → 2-methyl-1-propanol (isobutanol).' },
  { id: 'p1-organic-002', topic: 'organic', q: 'Degrees of unsaturation in C₆H₁₀?', opts: ['0', '2', '1', '3'], a: 1, why: 'DoU = (2×6+2−10)/2 = 2 — e.g., one ring + one double bond (cyclohexene) or two π bonds (hexadiene).' },
  { id: 'p1-organic-003', topic: 'organic', skill: 'organic/stereochemistry', q: 'How many chiral centers does 2-bromobutane have?', opts: ['0', '2', '1', '3'], a: 2, why: 'C2 carries Br, H, CH₃, and C₂H₅ — four different groups. The molecule is chiral (two enantiomers).' },
  { id: 'p1-organic-004', topic: 'organic', skill: 'organic/mechanisms', q: '1-butene + HBr (no peroxides) gives mainly…', opts: ['1-bromobutane', 'butane', '1,2-dibromobutane', '2-bromobutane'], a: 3, why: 'Markovnikov via the 2° carbocation at C2.' },
  { id: 'p1-organic-005', topic: 'organic', skill: 'organic/stereochemistry', q: 'A double bond with the two HIGHEST-priority groups on opposite sides is designated…', opts: ['E', 'Z', 'cis', 'R'], a: 0, why: 'E (entgegen = opposite); Z (zusammen) = same side. CIP priorities, not "bigger group," decide.' },
  { id: 'p1-organic-006', topic: 'organic', skill: 'organic/aromatic', q: 'Which species is aromatic?', opts: ['cyclobutadiene, 4 π', 'cyclopentadienyl anion', 'cyclooctatetraene, tub-shaped', 'cyclohexene, one C=C'], a: 1, why: 'C₅H₅⁻: planar, cyclic, fully conjugated, 6 π electrons (4n+2, n=1). Cyclobutadiene\'s 4 π e⁻ make it antiaromatic.' },
  { id: 'p1-organic-007', topic: 'organic', skill: 'organic/carbonyl', q: 'Oxidation of 2-propanol with acidified dichromate gives…', opts: ['propanal', 'propanoic acid', 'acetone', 'propene'], a: 2, why: '2° alcohol → ketone, and it stops there (no H left on the carbinol carbon to remove).' },
  { id: 'p1-organic-008', topic: 'organic', skill: 'organic/carbonyl', q: 'Basic hydrolysis (saponification) of ethyl acetate gives…', opts: ['acetic acid + ethanol', 'acetaldehyde + ethanol', 'ethyl alcohol only', 'acetate ion + ethanol'], a: 3, why: 'OH⁻ attacks the carbonyl; the carboxylate product is deprotonated under the basic conditions — which is what makes it irreversible.' },
  { id: 'p1-organic-009', topic: 'organic', skill: 'organic/substitution-elimination', q: 'Relative SN2 rates follow…', opts: ['methyl > 1° > 2° ≫ 3°', '3° > 2° > 1° > methyl', 'all four are equal', '2° > 1° > methyl > 3°'], a: 0, why: 'Backside attack demands an open approach: each added alkyl group blocks it, and 3° shuts it down completely.' },
  { id: 'p1-organic-010', topic: 'organic', skill: 'organic/carbonyl', q: 'Which reagent distinguishes pentanal from 2-pentanone?', opts: ['bromine water, decolourised only by the ketone', 'aqueous NaOH', 'Tollens\' reagent', 'NaHCO₃ solution'], a: 2, why: 'Aldehydes give the silver mirror; ketones do not. (Fehling\'s/Benedict\'s works too.)' },
];
