// Question Bank — Part I: multiple choice in CCC Part A / USNCO Part I style.
// All questions are original, written to match the format and difficulty of
// those exams. 10 per topic across 11 topics.

export interface BankMC {
  id: string;        // explicit and permanent — see QuizQ in framework.ts
  topic: string;     // an ExamTopicId (the coarse 12), not a ModuleId
  q: string;
  opts: string[];
  a: number;
  why: string;
}

export const PART1: BankMC[] = [
  // ================= STOICHIOMETRY =================
  { id: 'p1-stoich-001', topic: 'stoich', q: 'What mass of oxygen is contained in 0.50 mol of CaCO₃?', opts: ['8 g', '16 g', '24 g', '48 g'], a: 2, why: '0.50 mol × 3 O per formula × 16 g/mol = 24 g.' },
  { id: 'p1-stoich-002', topic: 'stoich', q: '5.6 L of H₂ at STP (22.4 L/mol) reacts with excess N₂. Moles of NH₃ produced?', opts: ['0.25', '0.17', '0.38', '0.50'], a: 1, why: '5.6/22.4 = 0.25 mol H₂; ratio 2NH₃ : 3H₂ → 0.25 × 2/3 = 0.167 mol.' },
  { id: 'p1-stoich-003', topic: 'stoich', q: 'Mass percent of water in MgSO₄·7H₂O (M = 246.5)?', opts: ['28%', '39%', '51%', '63%'], a: 2, why: '7 × 18.02 = 126.1 g of water per mole → 126.1/246.5 = 51%.' },
  { id: 'p1-stoich-004', topic: 'stoich', q: '25.0 mL of 0.200 M AgNO₃ is treated with excess NaCl. Mass of AgCl (M = 143.3) formed?', opts: ['0.36 g', '0.72 g', '1.43 g', '0.14 g'], a: 1, why: '0.0250 L × 0.200 M = 5.00×10⁻³ mol Ag⁺ → same moles AgCl → 0.717 g.' },
  { id: 'p1-stoich-005', topic: 'stoich', q: 'Complete combustion of a hydrocarbon gives 0.44 g CO₂ and 0.18 g H₂O. Its empirical formula is…', opts: ['CH', 'CH₂', 'CH₃', 'C₂H₃'], a: 1, why: '0.44/44 = 0.010 mol C; 0.18/18 = 0.010 mol H₂O → 0.020 mol H. C:H = 1:2 → CH₂.' },
  { id: 'p1-stoich-006', topic: 'stoich', q: 'Concentrated HCl is 37% by mass with density 1.19 g/mL. Its molarity is about…', opts: ['6 M', '10 M', '12 M', '18 M'], a: 2, why: 'Per liter: 1190 g × 0.37 = 440 g HCl → 440/36.5 ≈ 12.1 mol.' },
  { id: 'p1-stoich-007', topic: 'stoich', q: 'In acidic solution, one mole of Cr₂O₇²⁻ oxidizes how many moles of Fe²⁺?', opts: ['2', '3', '6', '1'], a: 2, why: 'Each Cr goes +6 → +3 (3 e⁻) × 2 Cr = 6 e⁻ gained; each Fe²⁺ gives 1 e⁻ → 6 Fe²⁺.' },
  { id: 'p1-stoich-008', topic: 'stoich', q: 'Which sample contains the same number of molecules as 16 g of O₂?', opts: ['28 g N₂', '22 g CO₂', '4 g H₂', '8 g SO₂'], a: 1, why: '16 g O₂ = 0.50 mol. CO₂: 22/44 = 0.50 mol ✓. (N₂ 1.0, H₂ 2.0, SO₂ 0.125 mol.)' },
  { id: 'p1-stoich-009', topic: 'stoich', q: '10.0 g Al (27.0) reacts with 30.0 g Cl₂ (70.9) via 2Al + 3Cl₂ → 2AlCl₃. Mass of AlCl₃ (133.3) formed?', opts: ['37.6 g', '49.4 g', '28.2 g', '56.4 g'], a: 0, why: 'Al: 0.370/2 = 0.185; Cl₂: 0.423/3 = 0.141 → Cl₂ limiting. AlCl₃ = 0.423 × 2/3 = 0.282 mol × 133.3 = 37.6 g.' },
  { id: 'p1-stoich-010', topic: 'stoich', q: 'Drinking water contains 40 ppm Ca²⁺ (40.1 g/mol). Its molar concentration is about…', opts: ['1×10⁻³ M', '4×10⁻² M', '1×10⁻⁴ M', '4×10⁻⁵ M'], a: 0, why: '40 ppm ≈ 40 mg/L → 0.040 g ÷ 40.1 g/mol ≈ 1.0×10⁻³ mol/L.' },

  // ================= STATES OF MATTER & GASES =================
  { id: 'p1-states-001', topic: 'states', q: 'A real gas deviates most from ideal behavior at…', opts: ['high T, low P', 'high T, high P', 'low T, high P', 'low T, low P'], a: 2, why: 'Molecules close together (high P) and slow (low T): attractions and molecular volume both matter — the conditions approaching liquefaction.' },
  { id: 'p1-states-002', topic: 'states', q: 'At the same temperature, He and SO₂ gases have the same…', opts: ['rms speed', 'average kinetic energy', 'density', 'effusion rate'], a: 1, why: 'Average translational KE = (3/2)kT depends only on T. Lighter He compensates with higher speed.' },
  { id: 'p1-states-003', topic: 'states', q: 'A 2.0 L balloon at 300 K is heated to 600 K at constant pressure. New volume?', opts: ['1.0 L', '2.0 L', '4.0 L', '8.0 L'], a: 2, why: 'Charles\'s law: V ∝ T(K) → doubling T doubles V.' },
  { id: 'p1-states-004', topic: 'states', q: 'Which gas is densest at STP?', opts: ['N₂', 'O₂', 'CO₂', 'CH₄'], a: 2, why: 'Same molar volume for all ideal gases → density tracks molar mass: CO₂ (44) wins.' },
  { id: 'p1-states-005', topic: 'states', q: '2.0 mol He and 2.0 mol Ne exert 4.0 atm total. The partial pressure of He is…', opts: ['1.0 atm', '2.0 atm', '3.0 atm', '4.0 atm'], a: 1, why: 'Mole fraction ½ × 4.0 atm = 2.0 atm.' },
  { id: 'p1-states-006', topic: 'states', q: 'An unknown gas effuses half as fast as He. Its molar mass is…', opts: ['2 g/mol', '8 g/mol', '16 g/mol', '32 g/mol'], a: 2, why: 'Graham: rate ∝ 1/√M → half the rate = 4× the mass = 16 g/mol.' },
  { id: 'p1-states-007', topic: 'states', q: 'Which molecule CANNOT act as a hydrogen-bond donor?', opts: ['CH₃OH', 'NH₃', 'CH₃OCH₃', 'HF'], a: 2, why: 'Dimethyl ether has no H bonded to N/O/F — it can accept H-bonds through its O but never donate.' },
  { id: 'p1-states-008', topic: 'states', q: 'Glycerol is far more viscous than ethanol chiefly because it…', opts: ['has a higher molar mass', 'has three –OH groups for extensive H-bonding', 'is denser', 'is more polarizable'], a: 1, why: 'Three hydroxyls per molecule create a 3-D hydrogen-bond network that resists flow.' },
  { id: 'p1-states-009', topic: 'states', q: 'A solid is heated at a constant pressure BELOW its triple-point pressure. It will…', opts: ['melt, then boil', 'sublime directly to gas', 'stay solid', 'become supercritical'], a: 1, why: 'Below the triple point pressure the liquid field is never crossed — solid converts directly to vapor (like CO₂ at 1 atm).' },
  { id: 'p1-states-010', topic: 'states', q: 'The measured pressure of a real gas is slightly LOWER than the ideal prediction because…', opts: ['molecules have volume', 'intermolecular attractions soften wall impacts', 'collisions are inelastic', 'temperature falls'], a: 1, why: 'Molecules being pulled back by neighbors strike the walls less hard — the "a" correction in van der Waals.' },

  // ================= THERMODYNAMICS =================
  { id: 'p1-thermo-001', topic: 'thermo', q: 'A reaction with ΔH > 0…', opts: ['releases heat', 'absorbs heat', 'is never spontaneous', 'has negative ΔS'], a: 1, why: 'Positive ΔH = endothermic. Spontaneity still depends on TΔS.' },
  { id: 'p1-thermo-002', topic: 'thermo', q: 'On a heating curve, during the flat segment at the melting point the added energy goes into…', opts: ['kinetic energy of molecules', 'potential energy (breaking lattice attractions)', 'raising the pressure', 'nothing — it is lost'], a: 1, why: 'Temperature (average KE) is constant; energy is spent disrupting intermolecular attractions.' },
  { id: 'p1-thermo-003', topic: 'thermo', q: 'A gas absorbs 300 J of heat and does 100 J of work on the surroundings. ΔU = ?', opts: ['+400 J', '+200 J', '−200 J', '+300 J'], a: 1, why: 'ΔU = q + w = +300 + (−100) = +200 J. Work done BY the system is negative w.' },
  { id: 'p1-thermo-004', topic: 'thermo', q: 'ΔH°f: SO₂ = −296.8, SO₃ = −395.7 kJ/mol. ΔH° for 2SO₂ + O₂ → 2SO₃?', opts: ['−98.9 kJ', '−197.8 kJ', '−692.5 kJ', '+197.8 kJ'], a: 1, why: '2(−395.7) − 2(−296.8) = −791.4 + 593.6 = −197.8 kJ.' },
  { id: 'p1-thermo-005', topic: 'thermo', q: 'Which process has ΔS < 0?', opts: ['evaporating ether', 'dissolving O₂ gas in water', 'melting ice', 'heating N₂ gas'], a: 1, why: 'A free gas becomes caged among water molecules — fewer accessible microstates. Gas dissolution is entropy-negative.' },
  { id: 'p1-thermo-006', topic: 'thermo', q: 'ΔH(vap) = 40.7 kJ/mol and ΔS(vap) = 109 J/mol·K for water. The boiling point is about…', opts: ['298 K', '340 K', '373 K', '410 K'], a: 2, why: 'At the transition ΔG = 0 → T = ΔH/ΔS = 40700/109 ≈ 373 K.' },
  { id: 'p1-thermo-007', topic: 'thermo', q: 'Bond energies: H–I 299, H–H 436, I–I 151 kJ/mol. ΔH for 2HI → H₂ + I₂?', opts: ['−11 kJ', '+11 kJ', '+288 kJ', '−288 kJ'], a: 1, why: 'Break 2(299) = 598; form 436 + 151 = 587 → ΔH = 598 − 587 = +11 kJ (slightly endothermic).' },
  { id: 'p1-thermo-008', topic: 'thermo', q: '50 mL of 1.0 M HCl + 50 mL of 1.0 M NaOH raises the mixture (100 g, c = 4.18) by 6.8 °C. ΔH(neutralization) ≈ ?', opts: ['−28 kJ/mol', '−57 kJ/mol', '−114 kJ/mol', '−6.8 kJ/mol'], a: 1, why: 'q = 100 × 4.18 × 6.8 = 2.84 kJ for 0.050 mol H₂O formed → 56.9 kJ/mol released.' },
  { id: 'p1-thermo-009', topic: 'thermo', q: 'Which is NOT a state function?', opts: ['enthalpy', 'entropy', 'heat q', 'internal energy'], a: 2, why: 'q (and w) depend on the path taken; H, S, U, G depend only on the state. That path-dependence is why calorimetry needs controlled conditions.' },
  { id: 'p1-thermo-010', topic: 'thermo', q: 'An ideal gas expands into a vacuum (free expansion). Which is TRUE?', opts: ['q > 0', 'w < 0', 'ΔU = 0 and ΔS > 0', 'ΔS = 0'], a: 2, why: 'No external pressure → w = 0; insulated → q = 0 → ΔU = 0 (T constant for ideal gas). But the volume doubled: ΔS = nR ln(V₂/V₁) > 0. Entropy-driven.' },

  // ================= KINETICS =================
  { id: 'p1-kinetics-001', topic: 'kinetics', q: 'In N₂ + 3H₂ → 2NH₃, H₂ is consumed at 0.30 M/s. NH₃ forms at…', opts: ['0.30 M/s', '0.20 M/s', '0.45 M/s', '0.10 M/s'], a: 1, why: 'Divide by coefficients: rate = 0.30/3 = 0.10 → NH₃ = 2 × 0.10 = 0.20 M/s.' },
  { id: 'p1-kinetics-002', topic: 'kinetics', q: 'Doubling [A] doubles the rate; doubling [B] changes nothing. The rate law is…', opts: ['k[A][B]', 'k[A]', 'k[A]²', 'k[B]'], a: 1, why: 'First order in A, zero order in B → rate = k[A]. Orders come from experiment, not the balanced equation.' },
  { id: 'p1-kinetics-003', topic: 'kinetics', q: 'Units of k for a second-order reaction (rate in M/s)?', opts: ['s⁻¹', 'M⁻¹s⁻¹', 'M·s⁻¹', 'M⁻²s⁻¹'], a: 1, why: 'rate = k[A]² → k = rate/[A]² = (M/s)/M² = M⁻¹s⁻¹. Order is readable from k\'s units.' },
  { id: 'p1-kinetics-004', topic: 'kinetics', q: 'A first-order reactant falls to 12.5% of its initial value in 45 min. t½ = ?', opts: ['15 min', '22.5 min', '5.6 min', '11.25 min'], a: 0, why: '12.5% = (½)³ → three half-lives in 45 min → t½ = 15 min.' },
  { id: 'p1-kinetics-005', topic: 'kinetics', q: 'Rate = k[NO]²[O₂] is consistent with which mechanism?', opts: ['single termolecular step only', 'fast 2NO ⇌ N₂O₂, then slow N₂O₂ + O₂ → 2NO₂', 'slow NO + O₂ step first', 'none — third order is impossible'], a: 1, why: 'Substituting the pre-equilibrium ([N₂O₂] = K[NO]²) into the slow step\'s rate gives k′[NO]²[O₂]. Mechanisms can\'t be proven — only shown consistent.' },
  { id: 'p1-kinetics-006', topic: 'kinetics', q: 'A catalyst changes which quantity?', opts: ['ΔH°', 'K', 'Ea', 'ΔG°'], a: 2, why: 'Only the barrier. All thermodynamic quantities — and hence the equilibrium position — are untouched.' },
  { id: 'p1-kinetics-007', topic: 'kinetics', q: 'A rate constant doubles between 25 °C and 35 °C. Ea ≈ ?', opts: ['13 kJ/mol', '27 kJ/mol', '53 kJ/mol', '106 kJ/mol'], a: 2, why: 'ln2 = (Ea/R)(1/298 − 1/308) → Ea = 0.693 × 8.314 / 1.09×10⁻⁴ ≈ 53 kJ/mol — the origin of the "doubles per 10 °C" rule.' },
  { id: 'p1-kinetics-008', topic: 'kinetics', q: 'For a ZERO-order reaction, the half-life…', opts: ['is constant', 'is proportional to [A]₀', 'is inversely proportional to [A]₀', 'is infinite'], a: 1, why: 't½ = [A]₀/2k — more material takes proportionally longer. (1st: constant; 2nd: inverse.)' },
  { id: 'p1-kinetics-009', topic: 'kinetics', q: 'The overall rate of a multistep reaction is set by…', opts: ['the first step always', 'the fastest step', 'the slowest step', 'the sum of all steps'], a: 2, why: 'The rate-determining step is the kinetic bottleneck, like the slowest tollbooth on a highway.' },
  { id: 'p1-kinetics-010', topic: 'kinetics', q: 'A radioisotope has t½ = 15 y. A sample decays to 1/16 of its activity in…', opts: ['30 y', '45 y', '60 y', '240 y'], a: 2, why: '1/16 = (½)⁴ → 4 half-lives = 60 years. Radioactive decay is strictly first order.' },

  // ================= EQUILIBRIUM =================
  { id: 'p1-equilibrium-001', topic: 'equilibrium', q: 'For CaCO₃(s) ⇌ CaO(s) + CO₂(g), the equilibrium expression is…', opts: ['[CO₂][CaO]/[CaCO₃]', '[CO₂]', '[CaO][CO₂]', '1/[CO₂]'], a: 1, why: 'Pure solids are omitted → K = [CO₂]. The equilibrium CO₂ pressure depends only on T.' },
  { id: 'p1-equilibrium-002', topic: 'equilibrium', q: 'For PCl₅(g) ⇌ PCl₃(g) + Cl₂(g), Kp equals…', opts: ['Kc', 'Kc(RT)', 'Kc/(RT)', 'Kc(RT)²'], a: 1, why: 'Kp = Kc(RT)^Δn with Δn(gas) = 2 − 1 = +1.' },
  { id: 'p1-equilibrium-003', topic: 'equilibrium', q: '0.50 M HA with Ka = 2×10⁻⁶. Equilibrium [H⁺] ≈ ?', opts: ['1×10⁻³ M', '1×10⁻⁶ M', '2×10⁻³ M', '5×10⁻⁴ M'], a: 0, why: 'x = √(KaC) = √(1×10⁻⁶) = 1×10⁻³ M (0.2% ionized — approximation excellent).' },
  { id: 'p1-equilibrium-004', topic: 'equilibrium', q: 'K = 16 for A ⇌ 2B. K for B ⇌ ½A is…', opts: ['1/16', '1/4', '4', '1/256'], a: 1, why: 'Reverse → 1/16; halve → square root → 1/4.' },
  { id: 'p1-equilibrium-005', topic: 'equilibrium', q: 'An exothermic equilibrium is heated at constant volume. Which happens?', opts: ['K increases, shifts right', 'K decreases, shifts left', 'K constant, shifts left', 'no change'], a: 1, why: 'Heat is a "product" of exothermic reactions — raising T consumes product, and because the stress is thermal, K itself falls.' },
  { id: 'p1-equilibrium-006', topic: 'equilibrium', q: 'Molar solubility of BaSO₄ (Ksp = 1.1×10⁻¹⁰) in 0.10 M Na₂SO₄?', opts: ['1.0×10⁻⁵ M', '1.1×10⁻⁹ M', '1.1×10⁻¹¹ M', '3.3×10⁻⁶ M'], a: 1, why: '[SO₄²⁻] ≈ 0.10 → s = Ksp/0.10 = 1.1×10⁻⁹ M — ten-thousand-fold suppression (common ion).' },
  { id: 'p1-equilibrium-007', topic: 'equilibrium', q: 'K = 50; the reaction mixture currently has Q = 80. The system will…', opts: ['make more products', 'make more reactants', 'stay put', 'change K to 80'], a: 1, why: 'Q > K → too much product → net reverse reaction until Q falls to 50.' },
  { id: 'p1-equilibrium-008', topic: 'equilibrium', q: 'For MX₂ with Ksp = 4×10⁻¹², the molar solubility is…', opts: ['2×10⁻⁶ M', '1×10⁻⁴ M', '1.6×10⁻⁴ M', '4×10⁻⁶ M'], a: 1, why: 'Ksp = (s)(2s)² = 4s³ → s = (1×10⁻¹²)^(1/3) = 1×10⁻⁴ M.' },
  { id: 'p1-equilibrium-009', topic: 'equilibrium', q: 'More solid salt is added to an already SATURATED solution. The dissolved concentration…', opts: ['increases', 'decreases', 'stays the same', 'doubles'], a: 2, why: 'The solution is already at Q = Ksp; extra solid just sits there. Solids never appear in the equilibrium expression.' },
  { id: 'p1-equilibrium-010', topic: 'equilibrium', q: 'For an endothermic reaction, a plot of ln K vs 1/T is…', opts: ['a line with positive slope', 'a line with negative slope', 'a parabola', 'flat'], a: 1, why: 'van \'t Hoff: ln K = −(ΔH°/R)(1/T) + C. ΔH° > 0 makes the slope −ΔH°/R negative: K grows as T rises (1/T falls).' },

  // ================= ACIDS & BASES =================
  { id: 'p1-acids-001', topic: 'acids', q: 'The conjugate base of HSO₄⁻ is…', opts: ['H₂SO₄', 'SO₄²⁻', 'HSO₃⁻', 'OH⁻'], a: 1, why: 'Remove one H⁺: HSO₄⁻ → SO₄²⁻. (H₂SO₄ is its conjugate acid.)' },
  { id: 'p1-acids-002', topic: 'acids', q: 'The pH of 1×10⁻⁸ M HCl is…', opts: ['8.0', '6.98', '7.02', '6.0'], a: 1, why: 'Water\'s own autoionization dominates at this dilution — the answer must stay (barely) below 7. Acid can\'t give a basic pH!' },
  { id: 'p1-acids-003', topic: 'acids', q: 'Ka(HCN) = 6.2×10⁻¹⁰. Kb of CN⁻ = ?', opts: ['6.2×10⁻¹⁰', '1.6×10⁻⁵', '6.2×10⁻²⁴', '1.6×10⁻⁹'], a: 1, why: 'Kb = Kw/Ka = 10⁻¹⁴ / 6.2×10⁻¹⁰ = 1.6×10⁻⁵ — a fairly strong weak base (weak acid ⇒ stronger conjugate).' },
  { id: 'p1-acids-004', topic: 'acids', q: 'A buffer is 0.20 M in HA (pKa 4.00) and 0.10 M in A⁻. Its pH is…', opts: ['4.30', '4.00', '3.70', '3.00'], a: 2, why: 'pH = 4.00 + log(0.10/0.20) = 4.00 − 0.30 = 3.70. More acid than base → below pKa.' },
  { id: 'p1-acids-005', topic: 'acids', q: 'Which is best described as a Lewis acid?', opts: ['NH₃', 'BF₃', 'H₂O', 'Cl⁻'], a: 1, why: 'Boron\'s empty p orbital accepts an electron pair — the definition of a Lewis acid. NH₃/H₂O/Cl⁻ are donors (bases).' },
  { id: 'p1-acids-006', topic: 'acids', q: 'When a weak acid solution is diluted 10×, its percent ionization…', opts: ['decreases 10×', 'is unchanged', 'increases', 'becomes zero'], a: 2, why: 'Dilution drops Q below Ka → equilibrium shifts toward more dissociation (even though pH rises toward 7).' },
  { id: 'p1-acids-007', topic: 'acids', q: 'pKa1 = 6.35 and pKa2 = 10.33 for carbonic acid. The pH of a NaHCO₃ solution ≈ ?', opts: ['6.35', '8.34', '10.33', '7.00'], a: 1, why: 'Amphoteric species: pH ≈ (pKa1 + pKa2)/2 = 8.34, nearly independent of concentration.' },
  { id: 'p1-acids-008', topic: 'acids', q: 'The strongest acid among these oxyacids is…', opts: ['HClO', 'HClO₂', 'HClO₃', 'HClO₄'], a: 3, why: 'Each extra O withdraws density and delocalizes the conjugate base\'s charge: HClO₄ is one of the strongest acids known.' },
  { id: 'p1-acids-009', topic: 'acids', q: 'At the equivalence point of a weak BASE titrated with strong ACID, the pH is…', opts: ['7', 'above 7', 'below 7', 'equal to pKb'], a: 2, why: 'Only the conjugate ACID remains (e.g., NH₄⁺) — a weakly acidic solution. Mirror image of the weak-acid case.' },
  { id: 'p1-acids-010', topic: 'acids', q: 'A 0.1 M solution of Al(NO₃)₃ is…', opts: ['neutral', 'basic', 'acidic', 'amphoteric'], a: 2, why: 'The small, highly charged Al³⁺(aq) polarizes its water ligands: [Al(H₂O)₆]³⁺ donates H⁺ (Ka ≈ 10⁻⁵). NO₃⁻ is neutral.' },

  // ================= ELECTROCHEMISTRY & REDOX =================
  { id: 'p1-redox-001', topic: 'redox', q: 'The oxidation number of S in S₂O₃²⁻ (thiosulfate) is…', opts: ['+6', '+4', '+2', '−2'], a: 2, why: '2x + 3(−2) = −2 → x = +2 (an average; the two S atoms are actually inequivalent).' },
  { id: 'p1-redox-002', topic: 'redox', q: 'Balancing MnO₄⁻ → Mn²⁺ in acid requires…', opts: ['5e⁻ and 8H⁺ on the left', '3e⁻ and 4H⁺ on the left', '5e⁻ on the right', '7e⁻ and 8H⁺'], a: 0, why: 'MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O. Balance O with water, H with H⁺, charge with electrons.' },
  { id: 'p1-redox-003', topic: 'redox', q: 'E°: Ag⁺/Ag = +0.80 V, Zn²⁺/Zn = −0.76 V. E°cell of the spontaneous cell = ?', opts: ['0.04 V', '1.56 V', '−1.56 V', '0.84 V'], a: 1, why: 'E° = E°(cathode) − E°(anode) = 0.80 − (−0.76) = 1.56 V. Ag⁺ is reduced, Zn oxidized.' },
  { id: 'p1-redox-004', topic: 'redox', q: 'Time to deposit 0.050 mol of Cu from Cu²⁺ at 2.0 A?', opts: ['40 min', '80 min', '160 min', '20 min'], a: 1, why: 'Q = 0.050 × 2 × 96485 = 9650 C → t = 9650/2.0 = 4825 s ≈ 80 min.' },
  { id: 'p1-redox-005', topic: 'redox', q: 'Which species can disproportionate in aqueous solution?', opts: ['Cu²⁺', 'Cu⁺', 'Zn²⁺', 'Ag⁺'], a: 1, why: '2Cu⁺ → Cu + Cu²⁺ is spontaneous (E°(Cu⁺/Cu) = +0.52 > E°(Cu²⁺/Cu⁺) = +0.16) — Cu⁺ is unstable in water.' },
  { id: 'p1-redox-006', topic: 'redox', q: 'The cathode ion of a cell (n = 2) is diluted tenfold. The cell voltage…', opts: ['rises 59 mV', 'falls ~30 mV', 'falls 59 mV', 'is unchanged'], a: 1, why: 'Nernst: ΔE = −(0.0592/2)·log(10) = −29.6 mV. Less reactant at the cathode → less push.' },
  { id: 'p1-redox-007', topic: 'redox', q: 'In an ELECTROLYTIC cell, the cathode is…', opts: ['positive, oxidation', 'negative, reduction', 'positive, reduction', 'negative, oxidation'], a: 1, why: 'Reduction ALWAYS happens at the cathode. In electrolysis the power supply forces it, marking that electrode negative (opposite sign to galvanic).' },
  { id: 'p1-redox-008', topic: 'redox', q: 'From a standard reduction table, the strongest REDUCING agent is the species with…', opts: ['the most positive E°, left side', 'the most negative E°, right side', 'the most positive E°, right side', 'E° = 0'], a: 1, why: 'Strong reducers are eager to be oxidized — the reduced form (right side) of the most negative couple, e.g., Li(s).' },
  { id: 'p1-redox-009', topic: 'redox', q: 'Zinc blocks protect ship hulls because zinc…', opts: ['is cheaper than iron', 'is more easily oxidized, corroding sacrificially', 'forms a physical coating', 'is a better conductor'], a: 1, why: 'Zn (E° = −0.76) oxidizes preferentially to Fe (−0.44), making the hull the cathode. "Sacrificial anode."' },
  { id: 'p1-redox-010', topic: 'redox', q: 'For a 2-electron cell with E° = +1.10 V, ΔG° ≈ ?', opts: ['−106 kJ', '−212 kJ', '+212 kJ', '−53 kJ'], a: 1, why: 'ΔG° = −nFE° = −2 × 96485 × 1.10 ≈ −212 kJ/mol. Positive E° ⇔ negative ΔG° ⇔ K > 1.' },

  // ================= ATOMIC STRUCTURE =================
  { id: 'p1-atomic-001', topic: 'atomic', q: 'The energy of a 400 nm photon is about…', opts: ['1.6 eV', '3.1 eV', '5.0 eV', '0.4 eV'], a: 1, why: 'E(eV) ≈ 1240/λ(nm) = 1240/400 = 3.1 eV (violet light).' },
  { id: 'p1-atomic-002', topic: 'atomic', q: 'Which quantum number combination is allowed?', opts: ['n=2, ℓ=2, mℓ=1', 'n=3, ℓ=1, mℓ=−2', 'n=4, ℓ=2, mℓ=−2', 'n=1, ℓ=1, mℓ=0'], a: 2, why: 'Need ℓ ≤ n−1 and |mℓ| ≤ ℓ: only n=4, ℓ=2, mℓ=−2 (a 4d orbital) passes both tests.' },
  { id: 'p1-atomic-003', topic: 'atomic', q: 'Ground-state configuration of Cu (Z = 29)?', opts: ['[Ar]4s²3d⁹', '[Ar]4s¹3d¹⁰', '[Ar]3d¹¹', '[Ar]4s²3d⁸4p¹'], a: 1, why: 'The filled d-shell exception: 4s¹3d¹⁰ is lower in energy than 4s²3d⁹. Same story for Cr (4s¹3d⁵).' },
  { id: 'p1-atomic-004', topic: 'atomic', q: 'Which has the highest first ionization energy?', opts: ['Na', 'Mg', 'Al', 'Si'], a: 3, why: 'IE rises across the period; the Mg→Al dip (new 3p subshell) doesn\'t overcome Si\'s extra nuclear charge. Order: Na < Al < Mg < Si.' },
  { id: 'p1-atomic-005', topic: 'atomic', q: 'Rank by radius: S²⁻, Cl⁻, K⁺ (all 18 e⁻)…', opts: ['K⁺ > Cl⁻ > S²⁻', 'S²⁻ > Cl⁻ > K⁺', 'Cl⁻ > S²⁻ > K⁺', 'all equal'], a: 1, why: 'Isoelectronic: fewer protons hold the same 18 electrons more loosely. S (16p) largest, K (19p) smallest.' },
  { id: 'p1-atomic-006', topic: 'atomic', q: 'How many peaks appear in the photoelectron spectrum of aluminum?', opts: ['3', '4', '5', '13'], a: 2, why: 'One peak per subshell: 1s, 2s, 2p, 3s, 3p = 5 peaks (areas 2:2:6:2:1).' },
  { id: 'p1-atomic-007', topic: 'atomic', q: 'Compared with the Balmer series, Lyman-series photons are…', opts: ['lower energy, IR', 'higher energy, UV', 'the same energy', 'visible'], a: 1, why: 'Transitions ending at n=1 span bigger energy gaps than those ending at n=2 → all Lyman lines are ultraviolet.' },
  { id: 'p1-atomic-008', topic: 'atomic', q: 'An element has IE₁–IE₄ of 738, 1451, 7733, 10 540 kJ/mol. It belongs to group…', opts: ['1', '2', '13', '14'], a: 1, why: 'The huge jump comes after removing TWO electrons — the third digs into the core. Two valence electrons = group 2 (this is Mg).' },
  { id: 'p1-atomic-009', topic: 'atomic', q: 'The 3d_xy orbital has how many nodal planes?', opts: ['0', '1', '2', '3'], a: 2, why: 'Angular nodes = ℓ = 2: the xz and yz planes both have zero amplitude, giving the four-lobed shape.' },
  { id: 'p1-atomic-010', topic: 'atomic', q: 'Moving Na → Cl across period 3, Z_eff on the valence electrons…', opts: ['stays constant', 'decreases', 'increases by roughly +1 per element', 'doubles'], a: 2, why: 'Each step adds one proton while same-shell electrons shield poorly (~0.35) → net pull climbs steadily. This single trend explains radius, IE, EN.' },

  // ================= BONDING & STRUCTURE =================
  { id: 'p1-bonding-001', topic: 'bonding', q: 'The sulfite ion SO₃²⁻ is…', opts: ['trigonal planar, 120°', 'trigonal pyramidal, ~107°', 'T-shaped', 'tetrahedral'], a: 1, why: 'S has 3 bonds + 1 lone pair (26 valence e⁻) → AX₃E, pyramidal like NH₃. Sulfate (no lone pair) is the tetrahedral one.' },
  { id: 'p1-bonding-002', topic: 'bonding', q: 'Hybridization of carbon in CO₂?', opts: ['sp', 'sp²', 'sp³', 'unhybridized'], a: 0, why: 'Two σ-domains (two double bonds, no lone pairs) → sp, linear. The two π bonds use the remaining p orbitals.' },
  { id: 'p1-bonding-003', topic: 'bonding', q: 'Which species requires resonance structures to describe properly?', opts: ['CH₄', 'NH₃', 'CO₃²⁻', 'H₂O'], a: 2, why: 'The double bond is delocalized over three equivalent C–O positions (bond order 4/3). One Lewis drawing can\'t show that.' },
  { id: 'p1-bonding-004', topic: 'bonding', q: 'The preferred Lewis structure of cyanate, OCN⁻, places the −1 formal charge on…', opts: ['carbon', 'oxygen', 'nitrogen', 'spread equally by symmetry'], a: 1, why: '⁻O–C≡N with FC(O) = −1 wins: negative charge belongs on the MOST electronegative atom.' },
  { id: 'p1-bonding-005', topic: 'bonding', q: 'Correct bond-angle order?', opts: ['H₂O > NH₃ > CH₄', 'CH₄ > NH₃ > H₂O', 'NH₃ > CH₄ > H₂O', 'all 109.5°'], a: 1, why: '109.5° > 107° > 104.5° — each lone pair compresses the bonding angles a bit more.' },
  { id: 'p1-bonding-006', topic: 'bonding', q: 'Bond order of N₂⁻ (11 valence electrons)?', opts: ['3', '2.5', '2', '1.5'], a: 1, why: 'The 11th electron enters antibonding π* → BO = (8−3)/2 = 2.5. Weaker and longer than N₂.' },
  { id: 'p1-bonding-007', topic: 'bonding', q: 'Which molecule is polar?', opts: ['BF₃', 'CF₄', 'NF₃', 'XeF₂'], a: 2, why: 'NF₃ is pyramidal — bond dipoles and the lone pair don\'t cancel. The others are symmetric (trigonal planar, tetrahedral, linear).' },
  { id: 'p1-bonding-008', topic: 'bonding', q: 'Number of σ and π bonds in HCN?', opts: ['3σ, 1π', '2σ, 2π', '1σ, 3π', '2σ, 1π'], a: 1, why: 'H–C is 1σ; C≡N is 1σ + 2π → total 2σ, 2π.' },
  { id: 'p1-bonding-009', topic: 'bonding', q: 'MgO has a much higher melting point than NaCl mainly because…', opts: ['Mg is heavier', 'the ±2 charges quadruple the lattice energy', 'MgO is covalent', 'Cl⁻ is polarizable'], a: 1, why: 'Lattice energy ∝ q₁q₂/r: (2+)(2−) vs (1+)(1−) gives ~4× the attraction (plus smaller ions). 2852 °C vs 801 °C.' },
  { id: 'p1-bonding-010', topic: 'bonding', q: 'The C–O bond length in CO₃²⁻ compared with a normal C–O single and C=O double bond is…', opts: ['equal to the single', 'equal to the double', 'between the two, all three identical', 'alternating short-long'], a: 2, why: 'Resonance averages the bonds to order 4/3 — experiment finds three identical intermediate-length bonds, the classic evidence for delocalization.' },

  // ================= DESCRIPTIVE & INORGANIC =================
  { id: 'p1-descriptive-001', topic: 'descriptive', q: 'A lilac/violet flame test indicates…', opts: ['Na⁺', 'K⁺', 'Ca²⁺', 'Cu²⁺'], a: 1, why: 'K⁺ burns lilac (view through cobalt glass to filter the ever-present yellow sodium flare).' },
  { id: 'p1-descriptive-002', topic: 'descriptive', q: 'Which oxide dissolves in BOTH strong acid and strong base?', opts: ['Na₂O', 'MgO', 'Al₂O₃', 'SO₃'], a: 2, why: 'Al₂O₃ is amphoteric: acid → Al³⁺; base → aluminate [Al(OH)₄]⁻. Same family: ZnO, BeO, PbO, SnO.' },
  { id: 'p1-descriptive-003', topic: 'descriptive', q: 'A gas that turns limewater milky is…', opts: ['H₂', 'O₂', 'CO₂', 'NH₃'], a: 2, why: 'CO₂ + Ca(OH)₂ → CaCO₃(s) white precipitate. (Excess CO₂ re-dissolves it as Ca(HCO₃)₂.)' },
  { id: 'p1-descriptive-004', topic: 'descriptive', q: 'The brown gas produced when copper reacts with concentrated nitric acid is…', opts: ['NO', 'NO₂', 'N₂O', 'HNO₃ vapor'], a: 1, why: 'Concentrated HNO₃ → brown NO₂; DILUTE gives colorless NO (which browns in air). A classic observation pair.' },
  { id: 'p1-descriptive-005', topic: 'descriptive', q: 'Which precipitate dissolves in aqueous ammonia?', opts: ['AgCl', 'BaSO₄', 'PbS', 'Fe(OH)₃'], a: 0, why: 'AgCl + 2NH₃ → [Ag(NH₃)₂]⁺ + Cl⁻ — complex-ion formation pulls the dissolution. (AgI resists: too insoluble.)' },
  { id: 'p1-descriptive-006', topic: 'descriptive', q: 'Reactivity of the alkali metals with water increases…', opts: ['up the group', 'down the group', 'toward the middle', 'not at all'], a: 1, why: 'IE falls down the group — Cs loses its electron easiest. Li fizzes, Na darts, K ignites, Cs detonates.' },
  { id: 'p1-descriptive-007', topic: 'descriptive', q: 'During a dichromate titration of Fe²⁺, the solution color change at the endpoint region involves Cr species going…', opts: ['orange → green', 'yellow → blue', 'purple → colorless', 'green → orange'], a: 0, why: 'Cr₂O₇²⁻ (orange) is reduced to Cr³⁺ (green). Purple→colorless is permanganate\'s signature instead.' },
  { id: 'p1-descriptive-008', topic: 'descriptive', q: 'Industrial ammonia synthesis (Haber) uses roughly…', opts: ['25 °C, 1 atm', '450 °C, 200 atm, Fe catalyst', '1000 °C, vacuum', '0 °C, 500 atm'], a: 1, why: 'A compromise: high P pushes 4 gas mol → 2; moderate-high T for rate (K would prefer cold); iron catalyst bridges the gap.' },
  { id: 'p1-descriptive-009', topic: 'descriptive', q: 'Which pair shows a diagonal relationship?', opts: ['Li and Na', 'Li and Mg', 'Be and Mg', 'B and C'], a: 1, why: 'Li/Mg (also Be/Al, B/Si): similar charge density gives similar chemistry — e.g., both Li and Mg form nitrides directly.' },
  { id: 'p1-descriptive-010', topic: 'descriptive', q: 'Chlorine water is added to KI solution with a little hexane. The hexane layer turns…', opts: ['colorless', 'brown/purple', 'green', 'blue'], a: 1, why: 'Cl₂ displaces I₂ (halogen activity falls down the group); I₂ partitions into hexane with its violet color.' },

  // ================= ORGANIC =================
  { id: 'p1-organic-001', topic: 'organic', q: 'The IUPAC name of (CH₃)₂CHCH₂OH is…', opts: ['1-butanol', '2-methyl-1-propanol', '2-butanol', 'tert-butanol'], a: 1, why: 'Longest chain bearing the OH is propanol; a methyl sits on C2 → 2-methyl-1-propanol (isobutanol).' },
  { id: 'p1-organic-002', topic: 'organic', q: 'Degrees of unsaturation in C₆H₁₀?', opts: ['0', '1', '2', '3'], a: 2, why: 'DoU = (2×6+2−10)/2 = 2 — e.g., one ring + one double bond (cyclohexene) or two π bonds (hexadiene).' },
  { id: 'p1-organic-003', topic: 'organic', q: 'How many chiral centers does 2-bromobutane have?', opts: ['0', '1', '2', '3'], a: 1, why: 'C2 carries Br, H, CH₃, and C₂H₅ — four different groups. The molecule is chiral (two enantiomers).' },
  { id: 'p1-organic-004', topic: 'organic', q: '1-butene + HBr (no peroxides) gives mainly…', opts: ['1-bromobutane', '2-bromobutane', '1,2-dibromobutane', 'butane'], a: 1, why: 'Markovnikov via the 2° carbocation at C2.' },
  { id: 'p1-organic-005', topic: 'organic', q: 'A double bond with the two HIGHEST-priority groups on opposite sides is designated…', opts: ['cis', 'Z', 'E', 'R'], a: 2, why: 'E (entgegen = opposite); Z (zusammen) = same side. CIP priorities, not "bigger group," decide.' },
  { id: 'p1-organic-006', topic: 'organic', q: 'Which species is aromatic?', opts: ['cyclobutadiene', 'cyclopentadienyl anion', 'cyclooctatetraene', 'cyclohexene'], a: 1, why: 'C₅H₅⁻: planar, cyclic, fully conjugated, 6 π electrons (4n+2, n=1). Cyclobutadiene\'s 4 π e⁻ make it antiaromatic.' },
  { id: 'p1-organic-007', topic: 'organic', q: 'Oxidation of 2-propanol with acidified dichromate gives…', opts: ['propanal', 'propanoic acid', 'acetone', 'propene'], a: 2, why: '2° alcohol → ketone, and it stops there (no H left on the carbinol carbon to remove).' },
  { id: 'p1-organic-008', topic: 'organic', q: 'Basic hydrolysis (saponification) of ethyl acetate gives…', opts: ['acetic acid + ethanol', 'acetate ion + ethanol', 'ethyl alcohol only', 'acetaldehyde + ethanol'], a: 1, why: 'OH⁻ attacks the carbonyl; the carboxylate product is deprotonated under the basic conditions — which is what makes it irreversible.' },
  { id: 'p1-organic-009', topic: 'organic', q: 'Relative SN2 rates follow…', opts: ['3° > 2° > 1°', 'methyl > 1° > 2° ≫ 3°', 'all equal', '2° > 1° > methyl'], a: 1, why: 'Backside attack demands an open approach: each added alkyl group blocks it, and 3° shuts it down completely.' },
  { id: 'p1-organic-010', topic: 'organic', q: 'Which reagent distinguishes pentanal from 2-pentanone?', opts: ['bromine water', 'Tollens\' reagent', 'NaOH', 'NaHCO₃'], a: 1, why: 'Aldehydes give the silver mirror; ketones do not. (Fehling\'s/Benedict\'s works too.)' },
];
