// Question Bank — Part III: laboratory practical scenarios (original questions
// in the style of lab-based exam sections). Each is a short experimental
// situation requiring technique knowledge or error-direction reasoning.

import type { BankMC } from './bankPart1';

export const PART3: BankMC[] = [
  // ---- titration technique ----
  { topic: 'acids', q: 'During a titration you overshoot the endpoint by several drops before noticing. The calculated analyte concentration will be…', opts: ['too low', 'too high', 'unaffected', 'random'], a: 1, why: 'Extra titrant is recorded as "needed" → moles of analyte calculated too high. If it happens, the honest fixes are: discard the trial, or back-titrate.' },
  { topic: 'acids', q: 'A buret is rinsed with distilled water but NOT with the NaOH titrant before filling. The reported acid concentration will be…', opts: ['too high', 'too low', 'unaffected', 'exactly halved'], a: 0, why: 'Residual water dilutes the NaOH → more volume needed to deliver the same moles → V reads high → calculated acid concentration too high.' },
  { topic: 'acids', q: 'NaOH is standardized against KHP that absorbed moisture before weighing. The NaOH concentration determined will be…', opts: ['too high', 'too low', 'unaffected', 'zero'], a: 0, why: 'Part of the weighed "KHP" is water → true moles of KHP are LESS than calculated, so less NaOH is used (small V). C = n(assumed)/V(small) → overestimated.' },
  { topic: 'acids', q: 'For a weak-acid/strong-base titration, methyl orange (range 3.1–4.4) is used by mistake. The endpoint will appear…', opts: ['after the true equivalence', 'before the true equivalence, badly early', 'exactly at equivalence', 'never'], a: 1, why: 'The curve passes pH 3–4.4 long before the steep jump (equivalence is ~8.7). The indicator changes while acid is still mostly untitrated → endpoint far too early.' },

  // ---- gravimetric analysis ----
  { topic: 'stoich', q: 'In a gravimetric chloride analysis, the AgCl precipitate is weighed while still slightly damp. The reported %Cl will be…', opts: ['too low', 'too high', 'unaffected', 'negative'], a: 1, why: 'Water adds mass attributed to AgCl → moles of Cl calculated high. "Heat to constant mass" exists exactly to kill this error.' },
  { topic: 'stoich', q: 'A precipitate is washed with very large volumes of pure water. The main risk is…', opts: ['contaminating it', 'dissolving away some product (solubility loss)', 'making it too dry', 'nothing — more washing is always better'], a: 1, why: 'Even "insoluble" salts have finite Ksp; unlimited washing steadily dissolves product → results biased low. Wash with small portions (sometimes with a common-ion solution).' },
  { topic: 'stoich', q: 'The filtrate from a gravimetric analysis still gives a precipitate when more reagent is added. This means…', opts: ['the analysis is fine', 'precipitation was incomplete — results will be low', 'the precipitate was contaminated', 'Ksp was exceeded'], a: 1, why: 'Analyte remained in solution → the collected mass undercounts it. Always test the filtrate for completeness of precipitation.' },

  // ---- calorimetry ----
  { topic: 'thermo', q: 'A coffee-cup calorimetry experiment ignores heat absorbed by the cup and thermometer. The measured |ΔH| will be…', opts: ['too large', 'too small', 'unaffected', 'doubled'], a: 1, why: 'Some heat warms the apparatus instead of the water → ΔT of the water is smaller than it "should" be → computed |q| and |ΔH| too small. Fix: determine the calorimeter constant.' },
  { topic: 'thermo', q: 'In measuring the heat of a slow reaction in a simple calorimeter, the biggest systematic problem is…', opts: ['stirring too much', 'heat exchange with the room during the long run', 'reading the balance', 'using too much water'], a: 1, why: 'The longer the run, the more heat leaks to (or from) the surroundings. Extrapolating the temperature-time curve back to mixing time is the standard correction.' },

  // ---- spectrophotometry ----
  { topic: 'lab', q: 'A fingerprint on the cuvette scatters light during an absorbance reading. The measured concentration will be…', opts: ['too low', 'too high', 'unaffected', 'exactly right if λmax is used'], a: 1, why: 'Scattered light never reaches the detector → instrument reads it as absorption → A high → c = A/εb overestimated. Wipe with lint-free tissue, handle by the frosted sides.' },
  { topic: 'lab', q: 'Your unknown reads A = 1.9 while your standards span 0.1–0.8. Best procedure?', opts: ['report the value from the fitted line', 'dilute the unknown quantitatively and re-measure', 'extrapolate the calibration', 'switch wavelength randomly'], a: 1, why: 'A = 1.9 means ~1% transmittance — noise-dominated and outside the calibrated (and linear) range. Dilute by a known factor, re-measure, multiply back.' },
  { topic: 'lab', q: 'The blank used to zero a spectrophotometer should contain…', opts: ['distilled water only, always', 'everything in the sample except the analyte', 'the most concentrated standard', 'nothing — an empty holder'], a: 1, why: 'Matrix, solvent and cuvette all absorb a little; only a matched blank subtracts them cleanly, isolating the analyte\'s absorbance.' },

  // ---- kinetics experiments ----
  { topic: 'kinetics', q: 'In an iodine clock experiment, the measured time-to-color is used as a rate proxy because…', opts: ['rate = k·t', 'rate ∝ 1/t (fixed amount of reaction per trial)', 't = half-life', 'color is proportional to k'], a: 1, why: 'Each trial consumes the same small fixed amount of thiosulfate before the color snaps in → rate ≈ (fixed Δ[X])/t → rate ∝ 1/t. Doubling of 1/t reveals reaction orders.' },
  { topic: 'kinetics', q: 'A kinetics run is done in a water bath that slowly warms by 3 °C during the experiment. The measured rate constant will be…', opts: ['a clean average', 'biased high late in the run (Arrhenius)', 'unaffected — k is constant', 'biased low late in the run'], a: 1, why: 'k grows exponentially with T (Arrhenius); the data collected later reflect a faster reaction → curvature in the linear plots and an inflated k. Thermostat quality is everything in kinetics.' },

  // ---- electrochemistry experiments ----
  { topic: 'redox', q: 'In an electroplating experiment, plotting mass deposited against total charge gives a straight line whose slope equals…', opts: ['nF/M', 'M/(nF)', 'F/M', 'It'], a: 1, why: 'm = (M/nF)·Q — Faraday\'s law. From the slope you can extract n (or M), a favorite lab-data question.' },
  { topic: 'redox', q: 'A student builds a galvanic cell but forgets the salt bridge. The voltmeter shows…', opts: ['the full E°', 'a brief reading that collapses to ~0', 'double the voltage', 'reversed polarity'], a: 1, why: 'Charge builds up in each half-cell within moments — without ion flow to neutralize it, the reaction (and current) stops. The bridge completes the circuit ionically.' },

  // ---- qualitative analysis ----
  { topic: 'descriptive', q: 'Every flame test in the lab shows a yellow tinge. The most likely cause and remedy are…', opts: ['potassium contamination; new samples', 'ubiquitous sodium contamination; view through cobalt-blue glass', 'a faulty burner; more gas', 'the wire is too hot'], a: 1, why: 'Traces of Na⁺ are everywhere (skin, glass, dust) and its emission is intense. Cobalt glass filters the yellow D-line so other colors (like K⁺ lilac) show through.' },
  { topic: 'descriptive', q: 'A white chloride precipitate dissolves when the mixture is heated, and re-forms on cooling. The cation is…', opts: ['Ag⁺', 'Pb²⁺', 'Hg₂²⁺', 'Ba²⁺'], a: 1, why: 'PbCl₂ is distinctly more soluble hot — the classic separation of Pb²⁺ from Ag⁺/Hg₂²⁺ within the chloride group.' },
  { topic: 'descriptive', q: 'To confirm NH₄⁺ in a solid, the standard test is…', opts: ['flame test', 'warm with NaOH and hold damp red litmus in the vapor', 'add AgNO₃', 'add BaCl₂'], a: 1, why: 'NH₄⁺ + OH⁻ → NH₃(g) on warming; ammonia turns damp red litmus blue (and has an unmistakable odor).' },
  { topic: 'descriptive', q: 'Adding dilute acid to an unknown solid produces a gas that pops with a lit splint. The gas — and a plausible solid — are…', opts: ['CO₂; a carbonate', 'H₂; an active metal like zinc', 'O₂; a peroxide', 'NH₃; an ammonium salt'], a: 1, why: 'The squeaky pop is hydrogen\'s signature (CO₂ extinguishes; O₂ relights a glowing splint; NH₃ needs base, not acid).' },

  // ---- organic technique ----
  { topic: 'organic', q: 'An impure organic solid melts at 118–124 °C while the pure compound melts sharply at 133 °C. This pattern is…', opts: ['impossible', 'typical: impurities lower AND broaden the melting range', 'a sign of decomposition', 'evidence of a different compound only'], a: 1, why: 'Impurities disrupt the lattice (freezing-point depression) and melt unevenly → depressed, broadened range. A sharp mp at the literature value is the purity check.' },
  { topic: 'organic', q: 'A good recrystallization solvent dissolves the compound…', opts: ['well hot and well cold', 'well hot but poorly cold', 'poorly hot and cold', 'only with stirring'], a: 1, why: 'Dissolve everything hot; on slow cooling the pure compound crystallizes while impurities (present in small amounts) stay dissolved. Then wash with ice-cold solvent.' },
  { topic: 'organic', q: 'In a simple distillation, the thermometer bulb must sit…', opts: ['dipped in the boiling liquid', 'level with the side-arm opening, in the vapor', 'above the condenser', 'anywhere'], a: 1, why: 'You want the temperature of the vapor actually leaving to the condenser — that\'s the boiling point of what you\'re collecting. In the liquid it reads the pot, not the distillate.' },

  // ---- measurement & uncertainty ----
  { topic: 'lab', q: 'You must add "about 20 mL" of a wash solvent (volume not critical) and separately "25.00 mL" of standard solution. Best glassware pair?', opts: ['two burets', 'graduated cylinder for the wash; volumetric pipet for the standard', 'two beakers', 'volumetric flask for both'], a: 1, why: 'Match precision to need: rough volume → cylinder (fast, ±0.5 mL); analytical volume → volumetric pipet (±0.03 mL). Using precise glassware for rough jobs wastes time; the reverse wrecks data.' },
  { topic: 'lab', q: 'A result depends on: mass 2.5000 g (±0.0002), volume 25.00 mL (±0.03), and titre 12.55 mL (±0.04). Which measurement limits the precision?', opts: ['the mass', 'the 25.00 mL pipet', 'the 12.55 mL titre', 'they are equal'], a: 2, why: 'Compare RELATIVE uncertainties: mass 0.008%, pipet 0.12%, titre 0.32%. The titre dominates — improving anything else is wasted effort. Percent uncertainties add for ×/÷.' },
];
