// Advanced (CCO) quiz banks: advanced inorganic (CFT/solid-state/descriptive),
// physical & biochemistry. 5 warm-ups then 20 CCO/IChO-level. All original.
import type { QuizQ } from './framework';

export const INORGANIC_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'ain-001', topic: 'advinorganic', q: 'In an octahedral field, the d orbitals split into…', opts: ['two e_g (up) and three t₂g (down)', 'three up and two down', 'all equal', 'one and four'], a: 0, why: 'The e_g pair (d_z², d_x²−y²) points at the ligands → higher; the t₂g trio points between → lower. Gap = Δ_o.' },
  { id: 'ain-002', topic: 'advinorganic', q: 'A face-centred cubic (FCC) unit cell contains how many atoms?', opts: ['1', '2', '4', '6'], a: 2, why: '8 corners×⅛ + 6 faces×½ = 1 + 3 = 4 atoms per cell.' },
  { id: 'ain-003', topic: 'advinorganic', q: 'Strong-field ligands tend to give…', opts: ['high-spin complexes', 'low-spin complexes', 'no splitting', 'tetrahedral only'], a: 1, why: 'Large Δ_o exceeds the pairing energy, so electrons pair in t₂g before occupying e_g → low spin.' },
  { id: 'ain-004', topic: 'advinorganic', q: 'The coordination number of an atom in a body-centred cubic (BCC) metal is…', opts: ['6', '8', '12', '4'], a: 1, why: 'The central atom touches all 8 corner atoms. FCC/HCP are 12-coordinate (closest packing).' },
  { id: 'ain-005', topic: 'advinorganic', q: 'A d¹⁰ ion such as Zn²⁺ is…', opts: ['strongly colored', 'colorless (no d–d transition)', 'paramagnetic', 'high spin'], a: 1, why: 'A full d subshell has no vacancy for a d–d transition, so no visible absorption → colorless.' },
  // ---- CCO-level ----
  { id: 'ain-006', topic: 'advinorganic', q: 'For a d⁶ octahedral ion, the ligand-field stabilization energy (LFSE) in the LOW-spin case is…', opts: ['−0.4 Δ_o', '−1.6 Δ_o', '−2.4 Δ_o', '0'], a: 2, why: 'Low-spin d⁶ = t₂g⁶e_g⁰ → 6×(−0.4) = −2.4 Δ_o (plus pairing energy). High-spin d⁶ is only −0.4 Δ_o.' },
  { id: 'ain-007', topic: 'advinorganic', q: 'The Jahn–Teller theorem predicts distortion for octahedral ions with…', opts: ['symmetric electron configurations', 'unequally occupied degenerate orbitals (e.g. high-spin d⁴, d⁹)', 'd⁰ and d¹⁰', 'tetrahedral geometry'], a: 1, why: 'An uneven e_g occupancy (Cu²⁺ d⁹, Mn³⁺ d⁴) lifts the degeneracy by elongating/compressing the octahedron — lowering energy.' },
  { id: 'ain-008', topic: 'advinorganic', q: 'Cu²⁺ (d⁹) complexes are famously Jahn–Teller distorted, typically showing…', opts: ['a perfect octahedron', 'two long axial + four short equatorial bonds', 'square planar always', 'linear geometry'], a: 1, why: 'The single e_g hole makes axial elongation favorable, giving the classic 4-short/2-long tetragonal distortion.' },
  { id: 'ain-009', topic: 'advinorganic', q: 'The ground-state term symbol for a free d² ion (like V³⁺) is…', opts: ['³F', '³P', '¹D', '⁵D'], a: 0, why: 'Hund: max S = 1 (2 unpaired) → 2S+1 = 3; max L for two d electrons = 3 (F). Ground term ³F.' },
  { id: 'ain-010', topic: 'advinorganic', q: 'Tetrahedral complexes are almost always high-spin because…', opts: ['Δ_t is large', 'Δ_t ≈ (4/9)Δ_o is small, below the pairing energy', 'they have no d orbitals', 'ligands are weak'], a: 1, why: 'The tetrahedral splitting is only ~4/9 of the octahedral value and there are only 4 ligands, so pairing rarely pays.' },
  { id: 'ain-011', topic: 'advinorganic', q: 'Packing efficiency of a face-centred cubic (closest-packed) lattice is…', opts: ['52%', '68%', '74%', '90%'], a: 2, why: 'FCC and HCP both achieve 74% — the maximum for equal spheres. BCC is 68%, simple cubic 52%.' },
  { id: 'ain-012', topic: 'advinorganic', q: 'For an FCC metal, the atomic radius r relates to the edge length a by…', opts: ['a = 2r', '4r = a√2', '4r = a√3', 'a = r√2'], a: 1, why: 'Atoms touch along the face diagonal (length a√2 = 4r). BCC touches along the body diagonal: 4r = a√3.' },
  { id: 'ain-013', topic: 'advinorganic', q: 'Bragg\'s law is nλ = 2d sin θ. Increasing the interplanar spacing d causes the diffraction angle θ to…', opts: ['increase', 'decrease', 'stay constant', 'double'], a: 1, why: 'For fixed n and λ, sin θ = nλ/2d — larger d means smaller θ. Wider planes diffract at lower angles.' },
  { id: 'ain-014', topic: 'advinorganic', q: 'The radius ratio r₊/r₋ for octahedral (6-coordinate) coordination lies between…', opts: ['0.155–0.225', '0.225–0.414', '0.414–0.732', '0.732–1.000'], a: 2, why: '0.414–0.732 favours octahedral holes; 0.732–1.0 → cubic (8), 0.225–0.414 → tetrahedral (4).' },
  { id: 'ain-015', topic: 'advinorganic', q: 'In band theory, an insulator has…', opts: ['overlapping bands', 'a large band gap between filled valence and empty conduction bands', 'a partly filled band', 'no bands'], a: 1, why: 'A big gap (>~3 eV) prevents thermal promotion of electrons. Semiconductors have a small gap; metals have no gap or a partly filled band.' },
  { id: 'ain-016', topic: 'advinorganic', q: 'A Schottky defect in an ionic crystal is…', opts: ['an interstitial cation', 'a paired cation + anion vacancy (preserving stoichiometry)', 'an impurity atom', 'a dislocation'], a: 1, why: 'Equal numbers of cation and anion vacancies keep charge balance and lower the density. A Frenkel defect moves an ion to an interstitial site instead.' },
  { id: 'ain-017', topic: 'advinorganic', q: 'The spectrochemical series orders ligands by Δ. Which is correct (weak → strong)?', opts: ['CN⁻ < NH₃ < H₂O < I⁻', 'I⁻ < Cl⁻ < H₂O < NH₃ < CN⁻', 'CO < CN⁻ < en < F⁻', 'H₂O < F⁻ < Cl⁻ < Br⁻'], a: 1, why: 'Halides are weak-field; H₂O/NH₃ intermediate; CN⁻ and CO are strong-field π-acceptors giving the largest Δ.' },
  { id: 'ain-018', topic: 'advinorganic', q: 'The colour of [Ti(H₂O)₆]³⁺ (d¹) arises from…', opts: ['a charge-transfer band', 'a single d–d transition (t₂g → e_g)', 'ligand fluorescence', 'a Jahn–Teller band only'], a: 1, why: 'Promoting the lone d electron across Δ_o absorbs ~500 nm (green), so the ion looks purple. Its broadness reflects Jahn–Teller.' },
  { id: 'ain-019', topic: 'advinorganic', q: 'Intense colour from permanganate MnO₄⁻ (d⁰) is due to…', opts: ['d–d transitions', 'ligand-to-metal charge transfer (LMCT)', 'Jahn–Teller distortion', 'spin–orbit coupling'], a: 1, why: 'A d⁰ ion has no d electrons for a d–d transition; the deep purple comes from O→Mn charge transfer, which is fully allowed and intense.' },
  { id: 'ain-020', topic: 'advinorganic', q: 'The 18-electron rule is most reliably obeyed by…', opts: ['early main-group ions', 'low-oxidation-state organometallics with π-acceptor ligands (e.g. metal carbonyls)', 'lanthanides', 'alkali metals'], a: 1, why: 'Strong-field π-acceptors like CO create a large gap that favours filling all bonding/nonbonding MOs — 18 electrons (e.g. Ni(CO)₄, Fe(CO)₅).' },
  { id: 'ain-021', topic: 'advinorganic', q: 'The chelate effect makes [Ni(en)₃]²⁺ more stable than [Ni(NH₃)₆]²⁺ chiefly due to…', opts: ['stronger Ni–N bonds', 'a favorable entropy change (more free particles released)', 'lower enthalpy', 'ring strain'], a: 1, why: '3 bidentate en release 6 water while binding — net increase in particle count → +ΔS drives a larger formation constant.' },
  { id: 'ain-022', topic: 'advinorganic', q: 'A linkage isomer differs by…', opts: ['which end of an ambidentate ligand binds (e.g. –NO₂ vs –ONO)', 'the counter-ion', 'optical rotation', 'the metal', ], a: 0, why: 'Nitrito-N (M–NO₂) vs nitrito-O (M–ONO) bind through different atoms of the same ligand — classic for NO₂⁻, SCN⁻.' },
  { id: 'ain-023', topic: 'advinorganic', q: 'Density of an FCC metal is computed from the unit cell as…', opts: ['ρ = M/(N_A a³)', 'ρ = ZM/(N_A a³) with Z = 4', 'ρ = a³/M', 'ρ = 4πr³/3'], a: 1, why: 'Z atoms per cell × molar mass ÷ (Avogadro × cell volume). For FCC, Z = 4 — a standard crystallography calculation.' },
  { id: 'ain-024', topic: 'advinorganic', q: 'Aluminium (amphoteric) dissolves in NaOH to give…', opts: ['Al(OH)₃ precipitate', 'the aluminate ion [Al(OH)₄]⁻ + H₂', 'AlH₃', 'no reaction'], a: 1, why: '2Al + 2NaOH + 6H₂O → 2Na[Al(OH)₄] + 3H₂. Amphoteric oxides/hydroxides (Al, Zn, Pb, Sn, Be) react with both acids and bases.' },
  { id: 'ain-025', topic: 'advinorganic', q: 'The lanthanide contraction makes the radii of Zr⁴⁺ and Hf⁴⁺ nearly identical because…', opts: ['they are the same element', 'poor 4f shielding offsets the added shell in period 6', 'both are radioactive', 'relativistic effects cancel'], a: 1, why: 'Across the 4f series the ineffective f-shielding lets Z_eff rise, shrinking radii so much that the 5d Hf ends up the same size as the 4d Zr — hence their notoriously difficult chemical separation.' },
];

export const BIOPHYS_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'bio-001', topic: 'biophys', q: 'The building blocks of proteins are…', opts: ['nucleotides', 'amino acids', 'monosaccharides', 'fatty acids'], a: 1, why: 'Twenty α-amino acids link by peptide (amide) bonds into polypeptide chains.' },
  { id: 'bio-002', topic: 'biophys', q: 'An enzyme increases a reaction rate by…', opts: ['raising the temperature', 'lowering the activation energy', 'shifting the equilibrium', 'adding energy'], a: 1, why: 'Enzymes are catalysts: they stabilize the transition state, lowering Ea, without changing ΔG or K.' },
  { id: 'bio-003', topic: 'biophys', q: 'The Arrhenius equation is k = A·e^(−Ea/RT). Raising T…', opts: ['lowers k', 'raises k', 'no effect', 'reverses the reaction'], a: 1, why: 'A larger fraction of molecules exceeds Ea, so k rises exponentially with temperature.' },
  { id: 'bio-004', topic: 'biophys', q: 'ATP is often called the cell\'s…', opts: ['genetic material', 'energy currency', 'catalyst', 'membrane'], a: 1, why: 'Hydrolysis of ATP to ADP + Pᵢ releases ~30 kJ/mol used to drive endergonic biochemical steps.' },
  { id: 'bio-005', topic: 'biophys', q: 'The base that pairs with adenine in DNA is…', opts: ['guanine', 'cytosine', 'thymine', 'uracil'], a: 2, why: 'A–T (two H-bonds) and G–C (three H-bonds). Uracil replaces thymine in RNA.' },
  // ---- CCO-level ----
  { id: 'bio-006', topic: 'biophys', q: 'In Michaelis–Menten kinetics, K_M equals the substrate concentration at which the rate is…', opts: ['zero', 'V_max', 'half of V_max', 'twice V_max'], a: 2, why: 'At [S] = K_M, v = V_max/2. A small K_M means tight binding / high apparent affinity.' },
  { id: 'bio-007', topic: 'biophys', q: 'A Lineweaver–Burk plot (1/v vs 1/[S]) gives a y-intercept of…', opts: ['1/K_M', '1/V_max', 'K_M/V_max', '−1/K_M'], a: 1, why: 'The double-reciprocal form 1/v = (K_M/V_max)(1/[S]) + 1/V_max: slope K_M/V_max, y-int 1/V_max, x-int −1/K_M.' },
  { id: 'bio-008', topic: 'biophys', q: 'A competitive inhibitor changes the kinetics by…', opts: ['lowering V_max', 'raising the apparent K_M, V_max unchanged', 'lowering both', 'raising V_max'], a: 1, why: 'It competes for the active site; enough substrate still reaches V_max, but you need more [S] → apparent K_M rises.' },
  { id: 'bio-009', topic: 'biophys', q: 'The Eyring equation relates rate to ΔG‡ (activation free energy). Compared with Arrhenius, it explicitly separates…', opts: ['ΔH‡ and ΔS‡ (entropy of activation)', 'A and Ea', 'k and K', 'pressure and volume'], a: 0, why: 'k = (k_B T/h)·e^(−ΔG‡/RT) with ΔG‡ = ΔH‡ − TΔS‡; the entropy of activation reflects ordering in the transition state.' },
  { id: 'bio-010', topic: 'biophys', q: 'A large NEGATIVE entropy of activation (ΔS‡) suggests a transition state that is…', opts: ['looser than reactants', 'more ordered/associative than reactants', 'identical to products', 'gaseous'], a: 1, why: 'Bringing two molecules together into an ordered TS loses translational/rotational freedom → ΔS‡ < 0 (associative, e.g. bimolecular).' },
  { id: 'bio-011', topic: 'biophys', q: 'The steady-state approximation assumes that for a reactive intermediate…', opts: ['its concentration is zero', 'd[intermediate]/dt ≈ 0 (formed and consumed at equal rates)', 'it equals the product', 'it never forms'], a: 1, why: 'A short-lived intermediate reaches a near-constant low concentration; setting its net rate to zero lets you eliminate it from the rate law.' },
  { id: 'bio-012', topic: 'biophys', q: 'In the Lindemann mechanism for a "unimolecular" gas reaction, the rate becomes first order at…', opts: ['low pressure', 'high pressure', 'all pressures', 'zero pressure'], a: 1, why: 'At high pressure, collisional activation is fast and the slow unimolecular step dominates → first order. At low pressure, activation is limiting → second order.' },
  { id: 'bio-013', topic: 'biophys', q: 'The Boltzmann population ratio of two states separated by ΔE is N₂/N₁ = e^(−ΔE/kT). Raising T…', opts: ['empties the upper state', 'increases the population of the upper state', 'no effect', 'inverts the populations'], a: 1, why: 'Higher thermal energy narrows the gap\'s effect, so the excited state gains population (approaching equal at very high T).' },
  { id: 'bio-014', topic: 'biophys', q: 'At physiological pH (~7.4), a neutral amino acid exists mainly as a…', opts: ['fully protonated cation', 'zwitterion (NH₃⁺ / COO⁻)', 'fully deprotonated anion', 'neutral un-ionized form'], a: 1, why: 'The carboxyl (pKa ~2) is deprotonated and the amino group (pKa ~9) is protonated → a dipolar zwitterion.' },
  { id: 'bio-015', topic: 'biophys', q: 'The isoelectric point (pI) of an amino acid is the pH at which it…', opts: ['is most soluble', 'has zero net charge', 'is fully protonated', 'denatures'], a: 1, why: 'For a simple amino acid, pI = ½(pKa1 + pKa2); at pI the zwitterion dominates and electrophoretic mobility is zero.' },
  { id: 'bio-016', topic: 'biophys', q: 'The α-helix and β-sheet are examples of protein…', opts: ['primary structure', 'secondary structure', 'tertiary structure', 'quaternary structure'], a: 1, why: 'Secondary structure = local backbone folding held by H-bonds. Primary = sequence; tertiary = 3-D fold; quaternary = subunit assembly.' },
  { id: 'bio-017', topic: 'biophys', q: 'The peptide bond has partial double-bond character, which makes it…', opts: ['freely rotating', 'planar and rigid (cis/trans restricted)', 'ionic', 'easily hydrolyzed'], a: 1, why: 'Resonance delocalizes the N lone pair into the C=O, giving ~40% double-bond character and restricting rotation about the C–N bond.' },
  { id: 'bio-018', topic: 'biophys', q: 'Coupling ATP hydrolysis (ΔG°′ = −31 kJ/mol) to a reaction with ΔG°′ = +14 kJ/mol makes the overall ΔG°′…', opts: ['+45 kJ/mol', '−17 kJ/mol', '+17 kJ/mol', '−45 kJ/mol'], a: 1, why: 'Free energies add: −31 + 14 = −17 kJ/mol → the coupled process becomes spontaneous. This is how endergonic biosynthesis is driven.' },
  { id: 'bio-019', topic: 'biophys', q: 'The standard cell potential of the respiratory chain (NADH → O₂) is large and positive, meaning electron transport is…', opts: ['non-spontaneous', 'strongly spontaneous (ΔG = −nFE°′ ≪ 0)', 'at equilibrium', 'endothermic only'], a: 1, why: 'E°′ ≈ +1.14 V from NADH/NAD⁺ (−0.32) to O₂/H₂O (+0.82); ΔG = −nFE°′ is very negative, powering ATP synthesis.' },
  { id: 'bio-020', topic: 'biophys', q: 'The Michaelis–Menten catalytic efficiency of an enzyme is best expressed by…', opts: ['V_max', 'K_M', 'k_cat/K_M', 'k_cat only'], a: 2, why: 'k_cat/K_M (the specificity constant) combines turnover and binding; enzymes near 10⁸–10⁹ M⁻¹s⁻¹ are "catalytically perfect" (diffusion-limited).' },
  { id: 'bio-021', topic: 'biophys', q: 'A protein denatures when heated because…', opts: ['peptide bonds hydrolyze', 'non-covalent interactions maintaining the fold are disrupted', 'the sequence changes', 'water evaporates'], a: 1, why: 'Heat overcomes the H-bonds, hydrophobic packing, and salt bridges holding tertiary structure — the primary sequence is unchanged.' },
  { id: 'bio-022', topic: 'biophys', q: 'Glucose (an aldohexose) exists in solution predominantly as…', opts: ['the open-chain aldehyde', 'a cyclic hemiacetal (pyranose ring)', 'a carboxylic acid', 'a ketone'], a: 1, why: 'The C5–OH attacks the C1 aldehyde intramolecularly, giving the six-membered pyranose hemiacetal; α/β anomers interconvert (mutarotation).' },
  { id: 'bio-023', topic: 'biophys', q: 'The rate-limiting enzyme of a metabolic pathway is usually regulated by…', opts: ['substrate only', 'allosteric feedback inhibition by a downstream product', 'temperature only', 'pH only'], a: 1, why: 'End-product binding at an allosteric site throttles the committed step — efficient feedback control (e.g. ATP inhibiting phosphofructokinase).' },
  { id: 'bio-024', topic: 'biophys', q: 'Compared with the uncatalyzed reaction, an enzyme changes the equilibrium constant K by…', opts: ['increasing it', 'decreasing it', 'not at all', 'making it 1'], a: 2, why: 'A catalyst speeds forward and reverse equally; ΔG° and therefore K are untouched — only the rate of approach to equilibrium changes.' },
  { id: 'bio-025', topic: 'biophys', q: 'The Henderson–Hasselbalch equation is used in biochemistry to relate the pH of a buffer to…', opts: ['temperature', 'the ratio of conjugate base to acid, pH = pKa + log([A⁻]/[HA])', 'ionic strength only', 'enzyme concentration'], a: 1, why: 'Physiological buffers (bicarbonate, phosphate, protein side chains) are analyzed this way; blood is held near pH 7.4 because the HCO₃⁻/H₂CO₃ ratio sits about 20:1, close to that system\'s effective pKa.' },
];
