// Advanced (CCO) quiz banks: advanced inorganic (CFT/solid-state/descriptive),
// physical & biochemistry. 5 warm-ups then 20 CCO/IChO-level. All original.
import type { QuizQ } from './framework';

export const INORGANIC_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'ain-001', topic: 'advinorganic', q: 'In an octahedral field, the d orbitals split into…', opts: ['three orbitals up, two down', 'two e_g up, three t₂g down', 'all five stay degenerate', 'one up and four down'], a: 1, why: 'The e_g pair (d_z², d_x²−y²) points at the ligands → higher; the t₂g trio points between → lower. Gap = Δ_o.' },
  { id: 'ain-002', topic: 'advinorganic', q: 'A face-centred cubic (FCC) unit cell contains how many atoms?', opts: ['4', '2', '1', '6'], a: 0, why: '8 corners×⅛ + 6 faces×½ = 1 + 3 = 4 atoms per cell.' },
  { id: 'ain-003', topic: 'advinorganic', q: 'Strong-field ligands tend to give…', opts: ['high-spin complexes', 'tetrahedral only', 'no splitting', 'low-spin complexes'], a: 3, why: 'Large Δ_o exceeds the pairing energy, so electrons pair in t₂g before occupying e_g → low spin.' },
  { id: 'ain-004', topic: 'advinorganic', q: 'The coordination number of an atom in a body-centred cubic (BCC) metal is…', opts: ['6', '12', '8', '4'], a: 2, why: 'The central atom touches all 8 corner atoms. FCC/HCP are 12-coordinate (closest packing).' },
  { id: 'ain-005', topic: 'advinorganic', q: 'A d¹⁰ ion such as Zn²⁺ is…', opts: ['strongly coloured, from d–d bands', 'colourless, having no d–d transition', 'paramagnetic, with one unpaired e⁻', 'high spin in a weak field'], a: 1, why: 'A full d subshell has no vacancy for a d–d transition, so no visible absorption → colorless.' },
  // ---- CCO-level ----
  { id: 'ain-006', topic: 'advinorganic', q: 'For a d⁶ octahedral ion, the ligand-field stabilization energy (LFSE) in the LOW-spin case is…', opts: ['−2.4 Δ_o', '−1.6 Δ_o', '−0.4 Δ_o', '0'], a: 0, why: 'Low-spin d⁶ = t₂g⁶e_g⁰ → 6×(−0.4) = −2.4 Δ_o (plus pairing energy). High-spin d⁶ is only −0.4 Δ_o.', misconception: 'LFSE is not the whole stability story, and quoting it alone is what makes low-spin look unconditionally better. Low-spin d⁶ gains −2.4Δ_o against high-spin\'s −0.4Δ_o, but it also pays the pairing energy for two extra pairs — which is exactly why the comparison is decided by Δ_o versus P, not by LFSE in isolation. Always write both terms before declaring a spin state.' },
  { id: 'ain-007', topic: 'advinorganic', q: 'The Jahn–Teller theorem predicts distortion for octahedral ions with…', opts: ['symmetric electron configurations only', 'tetrahedral geometry, where Δ is small', 'd⁰ and d¹⁰, having no partial filling', 'unequally occupied degenerate orbitals'], a: 3, why: 'An uneven e_g occupancy (Cu²⁺ d⁹, Mn³⁺ d⁴) lifts the degeneracy by elongating/compressing the octahedron — lowering energy.', misconception: 'Jahn–Teller distortion needs <em>unequal occupancy of degenerate orbitals</em>, which is a much narrower condition than "has unpaired electrons". High-spin d⁴ (e_g¹) and d⁹ (e_g³) distort strongly because the e_g set is unevenly filled; d³ and low-spin d⁶ do not, however many electrons they carry. The distortion is strongest when the imbalance is in e_g, which points straight at the ligands.' },
  { id: 'ain-008', topic: 'advinorganic', q: 'Cu²⁺ (d⁹) complexes are famously Jahn–Teller distorted, typically showing…', opts: ['a perfectly regular octahedron', 'square-planar geometry in every case', 'two long and four short bonds', 'linear two-coordinate geometry'], a: 2, why: 'The single e_g hole makes axial elongation favorable, giving the classic 4-short/2-long tetragonal distortion.' },
  { id: 'ain-009', topic: 'advinorganic', q: 'The ground-state term symbol for a free d² ion (like V³⁺) is…', opts: ['³P', '³F', '¹D', '⁵D'], a: 1, why: 'Hund: max S = 1 (2 unpaired) → 2S+1 = 3; max L for two d electrons = 3 (F). Ground term ³F.' },
  { id: 'ain-010', topic: 'advinorganic', q: 'Tetrahedral complexes are almost always high-spin because…', opts: ['Δ_t is large, so electrons stay apart', 'the ligands involved are always weak-field', 'the four ligands leave no d orbitals split', 'Δ_t ≈ (4/9)Δ_o, below the pairing energy'], a: 3, why: 'The tetrahedral splitting is only ~4/9 of the octahedral value and there are only 4 ligands, so pairing rarely pays.' },
  { id: 'ain-011', topic: 'advinorganic', q: 'Packing efficiency of a face-centred cubic (closest-packed) lattice is…', opts: ['74%', '68%', '52%', '90%'], a: 0, why: 'FCC and HCP both achieve 74% — the maximum for equal spheres. BCC is 68%, simple cubic 52%.' },
  { id: 'ain-012', topic: 'advinorganic', q: 'For an FCC metal, the atomic radius r relates to the edge length a by…', opts: ['a = 2r', '4r = a√2', '4r = a√3', 'a = r√2'], a: 1, why: 'Atoms touch along the face diagonal (length a√2 = 4r). BCC touches along the body diagonal: 4r = a√3.' , why2: 'Draw one face of the cube and stop memorising. On that face there are atoms at the four corners and one in the middle; the corner atom and the face-centre atom are in contact. So the face <em>diagonal</em> runs corner-atom-centre → face-atom → corner-atom-centre, a length of r + 2r + r = <b>4r</b>. By Pythagoras that same diagonal is a√2. Hence 4r = a√2, i.e. r = a√2/4 ≈ 0.354a. The drawing generalises: the contact line in BCC is the <em>body</em> diagonal (4r = a√3), and in simple cubic it is the <em>edge</em> (2r = a). One picture per lattice beats three formulas that look alike.' },
  { id: 'ain-013', topic: 'advinorganic', q: 'Bragg\'s law is nλ = 2d sin θ. Increasing the interplanar spacing d causes the diffraction angle θ to…', opts: ['increase', 'stay constant', 'decrease', 'double'], a: 2, why: 'For fixed n and λ, sin θ = nλ/2d — larger d means smaller θ. Wider planes diffract at lower angles.', misconception: 'In Bragg\'s law nλ = 2d sin θ, spacing and angle are inversely related — wider planes diffract at <em>smaller</em> angles. The intuition that "bigger spacing means bigger angle" reverses the geometry and inverts every structure you would deduce from a pattern. It is also why high-angle reflections carry the fine structural detail.' },
  { id: 'ain-014', topic: 'advinorganic', q: 'The radius ratio r₊/r₋ for octahedral (6-coordinate) coordination lies between…', opts: ['0.155–0.225', '0.225–0.414', '0.732–1.000', '0.414–0.732'], a: 3, why: '0.414–0.732 favours octahedral holes; 0.732–1.0 → cubic (8), 0.225–0.414 → tetrahedral (4).', misconception: 'Radius-ratio rules are a rough geometric guide, not a law, and they get a substantial fraction of real structures wrong. They assume hard touching spheres and purely ionic bonding, so they fail wherever covalency or polarisability matters — LiI is the classic counterexample. Use the ratio to form an expectation, then let the actual structure overrule it.' },
  { id: 'ain-015', topic: 'advinorganic', q: 'In band theory, an insulator has…', opts: ['a large valence–conduction gap', 'valence and conduction bands that overlap', 'a partly filled conduction band', 'no band structure at all'], a: 0, why: 'A big gap (>~3 eV) prevents thermal promotion of electrons. Semiconductors have a small gap; metals have no gap or a partly filled band.' },
  { id: 'ain-016', topic: 'advinorganic', q: 'A Schottky defect in an ionic crystal is…', opts: ['a cation displaced to an interstitial site', 'a set of cation and anion vacancies in stoichiometric proportion', 'an impurity atom on a lattice site', 'a dislocation line through the lattice'], a: 1, why: 'Equal numbers of cation and anion vacancies keep charge balance and lower the density. A Frenkel defect moves an ion to an interstitial site instead.' },
  { id: 'ain-017', topic: 'advinorganic', q: 'The spectrochemical series orders ligands by Δ. Which is correct (weak → strong)?', opts: ['CN⁻ < NH₃ < H₂O < Cl⁻ < I⁻', 'CO < CN⁻ < en < F⁻', 'I⁻ < Cl⁻ < H₂O < NH₃ < CN⁻', 'H₂O < F⁻ < Cl⁻ < Br⁻'], a: 2, why: 'Halides are weak-field; H₂O/NH₃ intermediate; CN⁻ and CO are strong-field π-acceptors giving the largest Δ.' },
  { id: 'ain-018', topic: 'advinorganic', q: 'The colour of [Ti(H₂O)₆]³⁺ (d¹) arises from…', opts: ['a ligand-to-metal charge transfer', 'a Jahn–Teller splitting of the ground state', 'fluorescence from the aqua ligands', 'a single d–d transition'], a: 3, why: 'Promoting the lone d electron across Δ_o absorbs ~500 nm (green), so the ion looks purple. Its broadness reflects Jahn–Teller.' },
  { id: 'ain-019', topic: 'advinorganic', q: 'Intense colour from permanganate MnO₄⁻ (d⁰) is due to…', opts: ['ligand-to-metal charge transfer', 'a d–d transition in the d⁰ ion', 'Jahn–Teller distortion of the tetrahedron', 'strong spin–orbit coupling at Mn'], a: 0, why: 'A d⁰ ion has no d electrons for a d–d transition; the deep purple comes from O→Mn charge transfer, which is fully allowed and intense.', misconception: 'Permanganate is d⁰, so its intense purple cannot be a d–d transition — there are no d electrons to promote. The colour is ligand-to-metal charge transfer, an allowed transition with molar absorptivities in the thousands, which is why MnO₄⁻ and CrO₄²⁻ are so much more intensely coloured than a typical d–d complex. Reaching for crystal-field splitting to explain every coloured transition-metal species fails at both d⁰ and d¹⁰.' },
  { id: 'ain-020', topic: 'advinorganic', q: 'The 18-electron rule is most reliably obeyed by…', opts: ['low-oxidation-state organometallics', 'early main-group ions and their halides', 'the lanthanides, with buried 4f', 'alkali metals in their compounds'], a: 0, why: 'Strong-field π-acceptors like CO create a large gap that favours filling all bonding/nonbonding MOs — 18 electrons (e.g. Ni(CO)₄, Fe(CO)₅).' },
  { id: 'ain-021', topic: 'advinorganic', q: 'The chelate effect makes [Ni(en)₃]²⁺ more stable than [Ni(NH₃)₆]²⁺ chiefly due to…', opts: ['individually stronger Ni–N bonds', 'relief of ring strain on binding', 'a markedly lower binding enthalpy', 'a favourable entropy change'], a: 3, why: '3 bidentate en release 6 water while binding — net increase in particle count → +ΔS drives a larger formation constant.' },
  { id: 'ain-022', topic: 'advinorganic', q: 'A linkage isomer differs by…', opts: ['the sign of its optical rotation', 'which ion sits outside the sphere', 'which end of the ligand binds', 'the identity of the central metal', ], a: 2, why: 'Nitrito-N (M–NO₂) vs nitrito-O (M–ONO) bind through different atoms of the same ligand — classic for NO₂⁻, SCN⁻.' },
  { id: 'ain-023', topic: 'advinorganic', q: 'Density of an FCC metal is computed from the unit cell as…', opts: ['ρ = M/(N_A a³), one atom per cell', 'ρ = ZM/(N_A a³), Z = 4', 'ρ = a³/M, inverted', 'ρ = 4πr³/3, the sphere volume'], a: 1, why: 'Z atoms per cell × molar mass ÷ (Avogadro × cell volume). For FCC, Z = 4 — a standard crystallography calculation.' },
  { id: 'ain-024', topic: 'advinorganic', q: 'Aluminium (amphoteric) dissolves in NaOH to give…', opts: ['[Al(OH)₄]⁻ and H₂', 'a precipitate of Al(OH)₃', 'AlH₃ and sodium oxide', 'no reaction — Al is passivated'], a: 0, why: '2Al + 2NaOH + 6H₂O → 2Na[Al(OH)₄] + 3H₂. Amphoteric oxides/hydroxides (Al, Zn, Pb, Sn, Be) react with both acids and bases.' },
  { id: 'ain-025', topic: 'advinorganic', q: 'The lanthanide contraction makes the radii of Zr⁴⁺ and Hf⁴⁺ nearly identical because…', opts: ['they are two names for one element', 'relativistic effects cancel exactly here', 'both are radioactive and unstable', 'poor 4f shielding offsets the new shell'], a: 3, why: 'Across the 4f series the ineffective f-shielding lets Z_eff rise, shrinking radii so much that the 5d Hf ends up the same size as the 4d Zr — hence their notoriously difficult chemical separation.', misconception: 'The lanthanide contraction is a shielding effect, not a coincidence or a relativistic curiosity. Filling the 4f shell across fourteen elements adds protons while the diffuse f electrons shield poorly, so radii shrink enough to cancel the extra shell that period 6 should have added. The result is that Zr and Hf are nearly identical in size and chemistry — and correspondingly hard to separate industrially.' },
];

export const BIOPHYS_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'bio-001', topic: 'biophys', q: 'The building blocks of proteins are…', opts: ['nucleotides', 'fatty acids', 'monosaccharides', 'amino acids'], a: 3, why: 'Twenty α-amino acids link by peptide (amide) bonds into polypeptide chains.' },
  { id: 'bio-002', topic: 'biophys', q: 'An enzyme increases a reaction rate by…', opts: ['raising the local temperature', 'shifting the position of equilibrium', 'lowering the activation energy', 'adding energy to the reactants'], a: 2, why: 'Enzymes are catalysts: they stabilize the transition state, lowering Ea, without changing ΔG or K.' },
  { id: 'bio-003', topic: 'biophys', q: 'The Arrhenius equation is k = A·e^(−Ea/RT). Raising T…', opts: ['lowers k', 'raises k', 'no effect', 'reverses the reaction'], a: 1, why: 'A larger fraction of molecules exceeds Ea, so k rises exponentially with temperature.' },
  { id: 'bio-004', topic: 'biophys', q: 'ATP is often called the cell\'s…', opts: ['energy currency', 'genetic material', 'catalyst', 'membrane'], a: 0, why: 'Hydrolysis of ATP to ADP + Pᵢ releases ~30 kJ/mol used to drive endergonic biochemical steps.' },
  { id: 'bio-005', topic: 'biophys', q: 'The base that pairs with adenine in DNA is…', opts: ['guanine', 'cytosine', 'uracil', 'thymine'], a: 3, why: 'A–T (two H-bonds) and G–C (three H-bonds). Uracil replaces thymine in RNA.' },
  // ---- CCO-level ----
  { id: 'bio-006', topic: 'biophys', q: 'In Michaelis–Menten kinetics, K_M equals the substrate concentration at which the rate is…', opts: ['zero, at saturation', 'V_max exactly', 'half V_max, by definition of K_M', 'twice V_max, extrapolated'], a: 2, why: 'At [S] = K_M, v = V_max/2. A small K_M means tight binding / high apparent affinity.', misconception: 'K_M is not a dissociation constant, and treating it as one is only safe in a limit. It is (k₋₁ + k_cat)/k₁, so it equals K_d only when catalysis is slow compared with substrate release (k_cat ≪ k₋₁). What K_M does mean without qualification is the substrate concentration at which v = V_max/2 — an operational definition, and the one to quote.' },
  { id: 'bio-007', topic: 'biophys', q: 'A Lineweaver–Burk plot (1/v vs 1/[S]) gives a y-intercept of…', opts: ['1/K_M', '1/V_max', 'K_M/V_max', '−1/K_M'], a: 1, why: 'The double-reciprocal form 1/v = (K_M/V_max)(1/[S]) + 1/V_max: slope K_M/V_max, y-int 1/V_max, x-int −1/K_M.' },
  { id: 'bio-008', topic: 'biophys', q: 'A competitive inhibitor changes the kinetics by…', opts: ['K_M rises, V_max unchanged', 'V_max falls, K_M unchanged', 'both K_M and V_max fall together', 'V_max rises, K_M unchanged'], a: 0, why: 'It competes for the active site; enough substrate still reaches V_max, but you need more [S] → apparent K_M rises.' },
  { id: 'bio-009', topic: 'biophys', q: 'The Eyring equation relates rate to ΔG‡ (activation free energy). Compared with Arrhenius, it explicitly separates…', opts: ['the pressure and volume terms', 'the A factor from Ea', 'the rate constant from K', 'ΔH‡ from ΔS‡, the entropy of activation'], a: 3, why: 'k = (k_B T/h)·e^(−ΔG‡/RT) with ΔG‡ = ΔH‡ − TΔS‡; the entropy of activation reflects ordering in the transition state.' },
  { id: 'bio-010', topic: 'biophys', q: 'A large NEGATIVE entropy of activation (ΔS‡) suggests a transition state that is…', opts: ['looser than the reactants were', 'more ordered than the reactants', 'identical in order to the products', 'gaseous rather than solvated'], a: 1, why: 'Bringing two molecules together into an ordered TS loses translational/rotational freedom → ΔS‡ < 0 (associative, e.g. bimolecular).', misconception: 'A negative entropy of activation is information about the transition state\'s <em>order</em>, not about temperature or the reaction being unfavourable. Bringing two molecules into one ordered transition state costs translational and rotational freedom, so ΔS‡ &lt; 0 signals an associative mechanism; a positive ΔS‡ points to a dissociative one. This is precisely the detail Arrhenius hides inside the pre-exponential factor A.' },
  { id: 'bio-011', topic: 'biophys', q: 'The steady-state approximation assumes that for a reactive intermediate…', opts: ['its concentration is exactly zero', 'its concentration equals the product', 'd[intermediate]/dt ≈ 0', 'it never actually forms'], a: 2, why: 'A short-lived intermediate reaches a near-constant low concentration; setting its net rate to zero lets you eliminate it from the rate law.', misconception: 'The steady-state approximation says the intermediate\'s concentration is <em>constant and small</em>, not zero. Setting it to zero would mean the intermediate never forms and no product could appear; setting its <em>derivative</em> to zero says it is consumed as fast as it is made. That distinction is the entire derivation of the Michaelis–Menten equation.' },
  { id: 'bio-012', topic: 'biophys', q: 'In the Lindemann mechanism for a "unimolecular" gas reaction, the rate becomes first order at…', opts: ['low pressure', 'zero pressure', 'all pressures', 'high pressure'], a: 3, why: 'At high pressure, collisional activation is fast and the slow unimolecular step dominates → first order. At low pressure, activation is limiting → second order.' },
  { id: 'bio-013', topic: 'biophys', q: 'The Boltzmann population ratio of two states separated by ΔE is N₂/N₁ = e^(−ΔE/kT). Raising T…', opts: ['raises the upper state', 'empties the upper state entirely', 'has no effect on the ratio', 'inverts the two populations'], a: 0, why: 'Higher thermal energy narrows the gap\'s effect, so the excited state gains population (approaching equal at very high T).', misconception: 'The Boltzmann ratio N₂/N₁ = e^(−ΔE/kT) never exceeds 1 at any positive temperature — raising T pushes the ratio toward 1, it does not invert it. A population inversion (more molecules upstairs than downstairs) is impossible at thermal equilibrium and requires active pumping, which is exactly why a laser needs a power supply. Higher temperature means a more even spread, never an upside-down one.' },
  { id: 'bio-014', topic: 'biophys', q: 'At physiological pH (~7.4), a neutral amino acid exists mainly as a…', opts: ['fully protonated cation', 'zwitterion (NH₃⁺ / COO⁻)', 'fully deprotonated anion', 'neutral un-ionized form'], a: 1, why: 'The carboxyl (pKa ~2) is deprotonated and the amino group (pKa ~9) is protonated → a dipolar zwitterion.', misconception: 'At physiological pH an amino acid is a zwitterion, not the neutral form drawn in most textbooks\' structural formula. The carboxyl group (pKa ≈ 2) has lost its proton and the amino group (pKa ≈ 9) has gained one, so the molecule carries both charges while being neutral overall. This is why amino acids are high-melting, water-soluble solids rather than the oily liquids their neutral structure would suggest.' },
  { id: 'bio-015', topic: 'biophys', q: 'The isoelectric point (pI) of an amino acid is the pH at which it…', opts: ['is most soluble', 'is fully protonated', 'has zero net charge', 'denatures'], a: 2, why: 'For a simple amino acid, pI = ½(pKa1 + pKa2); at pI the zwitterion dominates and electrophoretic mobility is zero.' },
  { id: 'bio-016', topic: 'biophys', q: 'The α-helix and β-sheet are examples of protein…', opts: ['primary structure', 'quaternary structure', 'tertiary structure', 'secondary structure'], a: 3, why: 'Secondary structure = local backbone folding held by H-bonds. Primary = sequence; tertiary = 3-D fold; quaternary = subunit assembly.' },
  { id: 'bio-017', topic: 'biophys', q: 'The peptide bond has partial double-bond character, which makes it…', opts: ['planar and rigid', 'freely rotating about C–N', 'ionic in character', 'easily hydrolysed in water'], a: 0, why: 'Resonance delocalizes the N lone pair into the C=O, giving ~40% double-bond character and restricting rotation about the C–N bond.' },
  { id: 'bio-018', topic: 'biophys', q: 'Coupling ATP hydrolysis (ΔG°′ = −31 kJ/mol) to a reaction with ΔG°′ = +14 kJ/mol makes the overall ΔG°′…', opts: ['+45 kJ/mol', '−17 kJ/mol', '+17 kJ/mol', '−45 kJ/mol'], a: 1, why: 'Free energies add: −31 + 14 = −17 kJ/mol → the coupled process becomes spontaneous. This is how endergonic biosynthesis is driven.' },
  { id: 'bio-019', topic: 'biophys', q: 'The standard cell potential of the respiratory chain (NADH → O₂) is large and positive, meaning electron transport is…', opts: ['non-spontaneous overall', 'poised at equilibrium', 'strongly spontaneous', 'endothermic but still driven'], a: 2, why: 'E°′ ≈ +1.14 V from NADH/NAD⁺ (−0.32) to O₂/H₂O (+0.82); ΔG = −nFE°′ is very negative, powering ATP synthesis.' },
  { id: 'bio-020', topic: 'biophys', q: 'The Michaelis–Menten catalytic efficiency of an enzyme is best expressed by…', opts: ['V_max', 'K_M', 'k_cat/K_M', 'k_cat only'], a: 2, why: 'k_cat/K_M (the specificity constant) combines turnover and binding; enzymes near 10⁸–10⁹ M⁻¹s⁻¹ are "catalytically perfect" (diffusion-limited).' },
  { id: 'bio-021', topic: 'biophys', q: 'A protein denatures when heated because…', opts: ['the peptide bonds hydrolyse', 'non-covalent interactions break', 'the amino-acid sequence changes', 'the surrounding water evaporates'], a: 1, why: 'Heat overcomes the H-bonds, hydrophobic packing, and salt bridges holding tertiary structure — the primary sequence is unchanged.' },
  { id: 'bio-022', topic: 'biophys', q: 'Glucose (an aldohexose) exists in solution predominantly as…', opts: ['a cyclic hemiacetal', 'the open-chain aldehyde form', 'the corresponding carboxylic acid', 'a ketone, after tautomerism'], a: 0, why: 'The C5–OH attacks the C1 aldehyde intramolecularly, giving the six-membered pyranose hemiacetal; α/β anomers interconvert (mutarotation).' },
  { id: 'bio-023', topic: 'biophys', q: 'The rate-limiting enzyme of a metabolic pathway is usually regulated by…', opts: ['substrate concentration alone', 'the ambient pH alone', 'the temperature alone', 'feedback inhibition'], a: 3, why: 'End-product binding at an allosteric site throttles the committed step — efficient feedback control (e.g. ATP inhibiting phosphofructokinase).' },
  { id: 'bio-024', topic: 'biophys', q: 'Compared with the uncatalyzed reaction, an enzyme changes the equilibrium constant K by…', opts: ['increasing it', 'decreasing it', 'not at all', 'making it 1'], a: 2, why: 'A catalyst speeds forward and reverse equally; ΔG° and therefore K are untouched — only the rate of approach to equilibrium changes.', misconception: 'An enzyme cannot change the equilibrium constant, however dramatic its effect on the rate. It lowers the activation barrier for the forward and reverse reactions equally, so both rate constants rise and their ratio K is untouched, as is ΔG°. An enzyme that made a reaction more favourable would be a perpetual-motion machine — it would create free energy from a catalyst.' , why2: 'Suppose the opposite and watch it break. If a catalyst raised K, then dropping it into a mixture already at equilibrium would drive net reaction forward; filtering it out would let the mixture fall back; and repeating the cycle would extract work indefinitely from a system at constant temperature. That is a perpetual-motion machine of the second kind, so the premise is false. The formal statement is the same argument without the drama: K depends only on ΔG° = G°(products) − G°(reactants) — the two <em>endpoints</em> — while a catalyst alters only the path between them. Since K = k<sub>f</sub>/k<sub>r</sub> must be preserved, a catalyst that speeds the forward reaction a millionfold speeds the reverse one by exactly the same factor.' },
  { id: 'bio-025', topic: 'biophys', q: 'The Henderson–Hasselbalch equation is used in biochemistry to relate the pH of a buffer to…', opts: ['the temperature of the buffer', 'the base-to-acid ratio', 'the ionic strength alone', 'the enzyme concentration present'], a: 1, why: 'Physiological buffers (bicarbonate, phosphate, protein side chains) are analyzed this way; blood is held near pH 7.4 because the HCO₃⁻/H₂CO₃ ratio sits about 20:1, close to that system\'s effective pKa.' },
];
