// Advanced (CCO) quiz banks: analytical & quantitative, spectroscopy + synthesis.
// 5 warm-ups then 20 CCO/IChO-level. All original.
import type { QuizQ } from './framework';

export const ANALYTICAL_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { q: 'A primary standard must be…', opts: ['a strong acid', 'high purity, stable, and of known composition', 'colored', 'volatile'], a: 1, why: 'Primary standards (KHP, Na₂CO₃, K₂Cr₂O₇) are pure, non-hygroscopic, and stoichiometrically exact so they can be weighed directly.' },
  { q: 'In a titration, the equivalence point is where…', opts: ['the indicator changes', 'moles of titrant stoichiometrically equal moles of analyte', 'pH = 7', 'the burette is empty'], a: 1, why: 'The endpoint (indicator change) only approximates the true equivalence point.' },
  { q: 'EDTA forms complexes with metal ions in a ratio of…', opts: ['1:1', '2:1', '1:6', '3:1'], a: 0, why: 'EDTA is hexadentate — one molecule wraps a single metal ion, always 1:1 regardless of charge.' },
  { q: 'Gravimetric analysis determines an analyte by measuring…', opts: ['volume', 'absorbance', 'the mass of a pure precipitate', 'pH'], a: 2, why: 'The analyte is converted to an insoluble compound of known formula, filtered, dried, and weighed.' },
  { q: 'A back-titration is used when…', opts: ['the analyte is colored', 'the direct reaction is slow or the analyte is a solid/volatile', 'no indicator exists', 'the titrant is unstable'], a: 1, why: 'Add a known excess of reagent, let it react fully, then titrate the leftover — used for antacids (CaCO₃), etc.' },
  // ---- CCO-level ----
  { q: 'EDTA titrations are buffered at high pH mainly to…', opts: ['speed the reaction', 'keep EDTA in its fully deprotonated Y⁴⁻ form (raise α₄)', 'dissolve the indicator', 'prevent oxidation'], a: 1, why: 'The conditional constant K′ = α₄·K_f; at low pH most EDTA is protonated (small α₄), so K′ collapses and the endpoint blurs.' },
  { q: 'The conditional formation constant K′ for a metal–EDTA complex is defined as…', opts: ['K_f only', 'α₄·K_f', 'K_f/α₄', 'α₄/K_f'], a: 1, why: 'α₄ is the fraction of EDTA present as Y⁴⁻ at that pH; multiplying folds the pH dependence into one effective constant.' },
  { q: 'By the Debye–Hückel limiting law, increasing ionic strength causes the mean activity coefficient γ± of a salt to…', opts: ['increase above 1', 'decrease below 1', 'stay exactly 1', 'become negative'], a: 1, why: 'log γ± = −0.51 z₊|z₋|√I (at 25 °C, dilute): the ionic atmosphere screens the ions, lowering effective concentration.' },
  { q: 'Adding inert KNO₃ to a saturated AgCl solution causes its solubility to…', opts: ['decrease (common ion)', 'increase slightly (activity/salt effect)', 'stay the same', 'drop to zero'], a: 1, why: 'Higher ionic strength lowers γ± of Ag⁺ and Cl⁻; since Ksp = γ²[Ag⁺][Cl⁻] is fixed, the concentrations must rise. The "diverse ion effect."' },
  { q: 'In a KMnO₄ titration, no external indicator is needed because…', opts: ['MnO₄⁻ is a primary standard', 'MnO₄⁻ is self-indicating (first excess drop stays pink)', 'the analyte is colored', 'the endpoint is at pH 7'], a: 1, why: 'Deep-purple permanganate is decolorized as it reacts; one drop past equivalence tints the solution permanently pink.' },
  { q: 'A 0.1000 g sample needing 12.00 mL of 0.05000 M EDTA contains how many mmol of metal?', opts: ['0.600', '0.240', '1.20', '0.0600'], a: 0, why: '1:1 stoichiometry → mmol metal = 0.05000 M × 12.00 mL = 0.600 mmol.' },
  { q: 'Chloride is precipitated as AgCl (M = 143.3) and weighs 0.2870 g. The mass of Cl (M = 35.45) is…', opts: ['0.0710 g', '0.1435 g', '0.2870 g', '0.0355 g'], a: 0, why: 'Gravimetric factor = 35.45/143.3 = 0.2474 → 0.2870 × 0.2474 = 0.0710 g Cl.' },
  { q: 'The "5% rule" fails and a quadratic is needed when…', opts: ['Ka is very small', 'the amount ionized exceeds 5% of the initial concentration', 'the acid is diprotic', 'temperature is high'], a: 1, why: 'Neglecting x in (C₀ − x) is only safe when x is small; strong-ish weak acids or dilute solutions break it.' },
  { q: 'A Gran plot linearizes a titration curve to find the equivalence point by plotting…', opts: ['pH vs V', 'a function proportional to [H⁺]·V vs V, extrapolated to zero', 'log V vs pH', 'absorbance vs V'], a: 1, why: 'Gran functions turn the sigmoid into straight lines whose x-intercept gives V_eq precisely — robust when the endpoint break is weak.' },
  { q: 'In complexometric titration, Eriochrome Black T changes color because…', opts: ['pH shifts', 'it is a metal-ion indicator: free vs metal-bound forms differ in color', 'it oxidizes', 'EDTA is colored'], a: 1, why: 'At the endpoint EDTA strips the metal from the (wine-red) MgIn complex, freeing the (blue) indicator.' },
  { q: 'To determine water hardness, Ca²⁺ + Mg²⁺ are titrated with EDTA. Titrating at pH 12 (Mg(OH)₂ precipitated) gives…', opts: ['total hardness', 'Ca²⁺ only', 'Mg²⁺ only', 'neither'], a: 1, why: 'Masking Mg²⁺ as its hydroxide leaves only Ca²⁺ to react — the difference from the pH-10 total gives Mg²⁺.' },
  { q: 'The method of standard additions corrects for…', opts: ['random error', 'matrix effects that change instrument sensitivity', 'dilution only', 'temperature'], a: 1, why: 'Spiking the real sample with known analyte and extrapolating removes matrix-dependent slope errors that an external calibration misses.' },
  { q: 'In iodometry, thiosulfate titrates I₂; starch is added…', opts: ['at the start', 'near the endpoint, once the solution is pale yellow', 'never', 'to buffer the solution'], a: 1, why: 'Added early, starch binds I₂ too tightly (irreversible blue). Near the end, the sharp blue→colourless flip marks the endpoint.' },
  { q: 'A weak acid HA (Ka = 1.8×10⁻⁵) is titrated with NaOH. The buffer region is best resisted to pH change at…', opts: ['the start', 'half-equivalence (pH = pKa)', 'the equivalence point', 'past equivalence'], a: 1, why: 'Maximum buffer capacity occurs where [HA] = [A⁻], i.e. pH = pKa = 4.74 — the flattest part of the curve.' },
  { q: 'Coprecipitation in gravimetry leads to results that are typically…', opts: ['too low', 'too high (extra mass on the precipitate)', 'unaffected', 'negative'], a: 1, why: 'Foreign ions adsorb/occlude onto the precipitate, adding mass → analyte overestimated. Digestion and reprecipitation reduce it.' },
  { q: 'For the reaction 2S₂O₃²⁻ + I₂ → S₄O₆²⁻ + 2I⁻, 25.00 mL of 0.1000 M thiosulfate reacts with how many mmol I₂?', opts: ['2.500', '1.250', '5.000', '0.625'], a: 1, why: '2:1 ratio → mmol I₂ = (0.1000 × 25.00)/2 = 1.250 mmol.' },
  { q: 'The activity of pure water and pure solids is taken as…', opts: ['0', '1', 'their molarity', 'γ times concentration'], a: 1, why: 'Standard-state activity of a pure condensed phase is 1 — which is why they drop out of K and Ksp expressions.' },
  { q: 'Karl Fischer titration specifically determines…', opts: ['acidity', 'water content', 'chloride', 'dissolved O₂'], a: 1, why: 'The I₂/SO₂/pyridine reagent consumes water stoichiometrically — the standard method for trace moisture.' },
  { q: 'Fajans method uses an adsorption indicator; the endpoint color change occurs because…', opts: ['pH changes', 'the precipitate surface charge flips, adsorbing the dye', 'the analyte oxidizes', 'a complex forms'], a: 1, why: 'Just past equivalence, excess Ag⁺ makes the AgCl surface positive, adsorbing dichlorofluorescein (pink) — a surface phenomenon.' },
  { q: 'A titration curve\'s equivalence-point break is sharpest when…', opts: ['both analyte and titrant are weak', 'the reaction has a large equilibrium constant and reasonable concentrations', 'the solution is dilute', 'the temperature is low'], a: 1, why: 'A big K (strong acid/base, large K_f, large cell E°) gives a near-vertical jump; weak reactions and dilution flatten it.' },
];

export const SPECTROSCOPY_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { q: 'Infrared spectroscopy probes molecular…', opts: ['electronic transitions', 'bond vibrations', 'nuclear spin flips', 'ionization'], a: 1, why: 'IR photons excite stretching/bending vibrations; the frequency depends on bond strength and atom masses.' },
  { q: '¹H NMR tells you about…', opts: ['the carbon skeleton only', 'hydrogen environments and their neighbours', 'molecular mass', 'color'], a: 1, why: 'Chemical shift = environment, integration = how many H, splitting = number of neighbouring H.' },
  { q: 'In mass spectrometry, the M⁺ peak corresponds to…', opts: ['the base peak always', 'the molecular ion (intact molecule minus an electron)', 'the largest fragment', 'the solvent'], a: 1, why: 'The molecular ion gives the molar mass; the base peak (100%) is the most abundant fragment, not necessarily M⁺.' },
  { q: 'A strong IR absorption near 1700 cm⁻¹ indicates a…', opts: ['C–H bond', 'O–H bond', 'C=O (carbonyl)', 'C–C bond'], a: 2, why: 'The carbonyl stretch is intense and diagnostic around 1700–1750 cm⁻¹.' },
  { q: 'In ¹H NMR, a triplet arises from a proton with…', opts: ['0 neighbours', '1 neighbour', '2 equivalent neighbours', '3 neighbours'], a: 2, why: 'n+1 rule: 2 neighbours → 3 peaks. The classic CH₃CH₂– ethyl pattern is triplet + quartet.' },
  // ---- CCO-level ----
  { q: 'A compound C₄H₈O shows a strong IR band at 1715 cm⁻¹ and a ¹H NMR singlet near 2.1 ppm. It is likely…', opts: ['butanal', 'butan-2-one', 'diethyl ether', 'but-3-en-1-ol'], a: 1, why: 'Carbonyl (1715) + only a methyl-ketone singlet (no aldehyde H near 9.7) → butanone, (CH₃)COCH₂CH₃; the two CH₃ environments differ but 2.1 ppm is the acetyl methyl.' },
  { q: 'The IR O–H stretch of a carboxylic acid appears as…', opts: ['a sharp band at 3600', 'a very broad band 2500–3300 cm⁻¹', 'no band', 'a band at 1700'], a: 1, why: 'Strong hydrogen bonding in the acid dimer smears the O–H stretch into a broad hump overlapping the C–H region.' },
  { q: 'Degrees of unsaturation for C₆H₅NO₂ (nitrobenzene) — using DoU = (2C+2+N−H)/2 — equals…', opts: ['3', '4', '5', '6'], a: 2, why: 'DoU = (2·6 + 2 + 1 − 5)/2 = 10/2 = <b>5</b> (oxygen is ignored). Structurally: benzene ring = 4, plus one N=O in the nitro group = 5.' },
  { q: 'The "nitrogen rule" states that an odd molecular mass (M⁺) implies…', opts: ['an even number of N atoms', 'an odd number of N atoms', 'no nitrogen', 'a halogen'], a: 1, why: 'An odd nominal M⁺ means an odd count of nitrogen atoms — a fast MS diagnostic for amines/amides.' },
  { q: 'A molecular ion cluster with M and M+2 peaks in ~1:1 ratio indicates…', opts: ['chlorine', 'bromine', 'nitrogen', 'sulfur'], a: 1, why: '⁷⁹Br and ⁸¹Br are ~50:50, giving the tell-tale 1:1 M/M+2. Chlorine (³⁵/³⁷ ≈ 3:1) gives 3:1.' },
  { q: 'In ¹³C NMR, the number of signals equals the number of…', opts: ['carbons', 'hydrogens', 'chemically inequivalent carbons', 'bonds'], a: 2, why: 'Symmetry-equivalent carbons overlap; para-xylene shows only 3 aromatic-region carbons plus the methyl, not 8.' },
  { q: 'An ethyl group (–CH₂CH₃) in ¹H NMR shows…', opts: ['two singlets', 'a triplet (CH₃) and a quartet (CH₂)', 'a doublet and a septet', 'one broad peak'], a: 1, why: 'CH₃ sees 2 H → triplet; CH₂ sees 3 H → quartet, with 3:2 integration.' },
  { q: 'An isopropyl group (CH₃)₂CH– gives, for the methine CH, a…', opts: ['triplet', 'quartet', 'septet', 'singlet'], a: 2, why: 'The CH sees six equivalent methyl H → n+1 = 7 (septet); the two CH₃ appear as a doublet.' },
  { q: 'Chemical shift (ppm) is independent of spectrometer field strength because it is defined as…', opts: ['absolute frequency', '(Δν/operating frequency)×10⁶ — a field-independent ratio', 'coupling constant', 'peak area'], a: 1, why: 'Referencing to TMS and dividing by the instrument frequency cancels the field, so shifts are comparable across spectrometers.' },
  { q: 'Coupling constant J is measured in Hz and, unlike chemical shift, is…', opts: ['field-dependent', 'field-independent', 'always 7 Hz', 'zero for aromatics'], a: 1, why: 'J reflects a through-bond interaction between nuclei — a real energy in Hz that does not scale with the applied field.' },
  { q: 'A carbonyl stretch order C=O: which absorbs at the HIGHEST wavenumber?', opts: ['amide', 'ketone', 'ester', 'acid chloride'], a: 3, why: 'Acyl chlorides ~1800 cm⁻¹ (strong EWG raises bond order); amides lowest ~1650 (N lone-pair donation). Frequency tracks C=O bond strength.' },
  { q: 'Loss of 15 from M⁺ in a mass spectrum usually signals loss of…', opts: ['OH', 'CH₃', 'H₂O', 'CO'], a: 1, why: 'A methyl radical (mass 15). Loss of 18 = water, 28 = CO or C₂H₄, 29 = CHO or C₂H₅.' },
  { q: 'Conjugation in a molecule shifts UV-Vis absorption to…', opts: ['shorter wavelength (blue shift)', 'longer wavelength (red shift)', 'no change', 'the IR', ], a: 1, why: 'Extended conjugation lowers the HOMO–LUMO gap → longer λ (bathochromic shift). β-carotene\'s 11 double bonds make it orange.' },
  { q: 'A ¹H NMR peak that disappears on shaking with D₂O is a…', opts: ['CH₃', 'aromatic H', 'labile OH or NH proton', 'CH₂'], a: 2, why: 'Exchangeable O–H/N–H protons swap for D and vanish — a classic assignment trick.' },
  { q: 'The Diels–Alder reaction is a [4+2] cycloaddition that is…', opts: ['radical', 'thermally allowed, suprafacial–suprafacial (6 π electrons)', 'photochemical only', 'ionic'], a: 1, why: 'Woodward–Hoffmann: 4n+2 π electrons → thermal supra-supra allowed. Forms a cyclohexene with defined stereochemistry.' },
  { q: 'In a Diels–Alder, the diene must adopt which conformation?', opts: ['s-trans', 's-cis', 'linear', 'either'], a: 1, why: 'Only the s-cis diene can reach both ends of the dienophile; cyclic locked-s-cis dienes (cyclopentadiene) are especially reactive.' },
  { q: 'The Wittig reaction converts a ketone/aldehyde plus a phosphorus ylide into…', opts: ['an alcohol', 'an alkene', 'a carboxylic acid', 'an ether'], a: 1, why: 'R₂C=O + Ph₃P=CR′₂ → R₂C=CR′₂ + Ph₃P=O. Reliable C=C formation at a defined position.' },
  { q: 'A silyl ether (TBS) protecting group is removed by…', opts: ['aqueous base', 'fluoride (e.g. TBAF)', 'hydrogenation', 'oxidation'], a: 1, why: 'The strong Si–F bond drives selective deprotection; TBS survives many conditions then comes off cleanly with F⁻.' },
  { q: 'Retrosynthetic analysis works by identifying disconnections that reveal…', opts: ['the final product', 'simpler synthons/precursors', 'the mechanism', 'the spectrum'], a: 1, why: 'Break the target at strategic bonds (⇒) back to available synthons; the forward synthesis reverses those steps.' },
  { q: 'An electrocyclic ring closure of a triene under thermal conditions proceeds…', opts: ['disrotatory (6 π e⁻)', 'conrotatory (6 π e⁻)', 'radically', 'never'], a: 0, why: 'Thermal 6-π-electron electrocyclizations are disrotatory (Woodward–Hoffmann); photochemical ones flip to conrotatory. Count the electrons, then apply the rule.' },
];
