// Quiz banks for the periodicity and polymers modules.
// 5 warm-ups then 20 CCC/CCO/USNCO-style. All original.
import type { QuizQ } from './framework';

export const PERIODICITY_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'per-001', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Across a period (left → right), atomic radius generally…', opts: ['increases', 'stays constant', 'decreases', 'doubles'], a: 2, why: 'Rising effective nuclear charge pulls the same-shell electrons in tighter, so radius shrinks across a period.' },
  { id: 'per-002', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Down a group, first ionization energy generally…', opts: ['increases', 'is zero', 'stays constant', 'decreases'], a: 3, why: 'Valence electrons occupy higher shells farther from the nucleus and are better shielded, so they are easier to remove.' },
  { id: 'per-003', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'The most electronegative element is…', opts: ['F', 'O', 'Cl', 'Cs'], a: 0, why: 'Fluorine (Pauling 4.0) tops the scale; electronegativity rises toward the top-right (excluding noble gases).' },
  { id: 'per-004', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Which is the largest species?', opts: ['Na⁺', 'Na', 'Mg²⁺', 'Al³⁺'], a: 1, why: 'Neutral Na keeps its 3s electron and full shell; cations lose a shell and shrink further with charge.', misconception: 'A cation is always smaller than its parent atom and an anion always larger — the electron count, not the nuclear charge, is what changed. Na loses its entire 3s shell to become Na⁺, so the drop is a whole quantum level rather than a small contraction. Ranking these by "more charge, bigger ion" inverts the answer; ranking by electron configuration gets it right every time.' },
  { id: 'per-005', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Metallic character generally increases…', opts: ['up, and toward the right', 'toward fluorine at the top', 'down, and to the left', 'toward helium, the smallest'], a: 2, why: 'Elements lose electrons more readily down a group and to the left — the metals occupy the lower-left of the table.' },
  // ---- olympiad ----
  { id: 'per-006', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'First ionization energy dips from Be to B because…', opts: ['B is the larger of the two atoms', 'Be is a metalloid and holds electrons loosely', 'B has more protons pulling inward', 'the electron leaves a 2p orbital'], a: 3, why: 'Be is 2s²; B\'s outermost electron is a single 2p, higher in energy and better shielded by the 2s pair — easier to remove despite the extra proton.' },
  { id: 'per-007', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Ionization energy dips from N to O because…', opts: ['a paired 2p electron is easier to remove', 'O is the smaller atom of the two', 'N has a completely full valence shell', 'O is more electronegative, holding on harder'], a: 0, why: 'N is 2p³ (half-filled, all unpaired, extra stable). O must pair a fourth 2p electron; that pairing repulsion lowers its IE below nitrogen\'s.' },
  { id: 'per-008', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Electron affinity of fluorine is LESS exothermic than chlorine\'s because…', opts: ['F is the less electronegative of the two', 'the small 2p shell of F is crowded', 'Cl has fewer inner-shell electrons than F, so the added electron is less shielded', 'F is a gas and Cl is not'], a: 1, why: 'Adding an electron to F\'s compact 2p subshell crowds it, so the energy released is smaller than for the roomier Cl — the classic F < Cl anomaly.' },
  { id: 'per-009', tier: 3, topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Using Slater\'s rules, the effective nuclear charge felt by a 3p electron in sulfur (Z = 16) is about…', opts: ['16.0', '10.9', '5.5', '1.0'], a: 2, why: 'S = 1s²2s²2p⁶3s²3p⁴. Same-shell (n=3) electrons shield 0.35 each (5 others → 1.75); n−1 shell (8 e⁻) shield 0.85 each (6.8); inner (2 e⁻) 1.00 (2.0). S = 10.55 → Z_eff ≈ 16 − 10.55 = 5.45 ≈ 5.5.', misconception: 'Slater\'s rules do not shield all inner electrons equally, and using Z minus the total electron count is the usual shortcut that fails. Same-shell electrons contribute 0.35 each, the (n−1) shell 0.85, and anything deeper 1.00 — which for sulfur\'s 3p electron gives Z_eff ≈ 5.45, not 16 and not 6. The graded values are the whole point of the rules.' , why2: 'Bound the answer before computing it. Z<sub>eff</sub> must be smaller than Z = 16 (there is screening) and larger than 1 (screening is never perfect), which kills two options at sight. Then use the crude version of Slater: the ten inner electrons in the n = 1 and n = 2 shells screen almost completely, so they take roughly 10 units off 16, leaving about 6 — and the five same-shell partners only nibble a little more. That is enough to pick <b>5.5</b> and to reject 10.9, which is not the charge at all but the <em>shielding constant</em> S = 10.55 that you subtract from Z. Reporting S in place of Z<sub>eff</sub> is the single most common way this calculation goes wrong.' },
  { id: 'per-010', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Rank ionic radii: O²⁻, F⁻, Na⁺, Mg²⁺ (all 10 electrons)…', opts: ['O²⁻ > F⁻ > Na⁺ > Mg²⁺', 'Mg²⁺ > Na⁺ > F⁻ > O²⁻', 'all equal', 'F⁻ > O²⁻ > Mg²⁺ > Na⁺'], a: 0, why: 'Isoelectronic: more protons pull the same 10 electrons tighter. O (8p) is largest, Mg (12p) smallest.' },
  { id: 'per-011', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'The second ionization energy of sodium is enormously larger than its first because…', opts: ['Na⁺ is radioactive and unstable', 'shielding increases sharply after the first', 'sodium is a metal, so it resists a second loss', 'the second electron comes from the n=2 core'], a: 3, why: 'After losing 3s¹, Na⁺ has a neon core; removing a tightly held, unshielded 2p electron costs ~10× more. The jump reveals one valence electron → group 1.', misconception: 'The huge jump between successive ionisation energies is a <em>configuration</em> signal, not a size effect, and its position identifies the group. Sodium\'s first electron leaves the 3s; the second has to be torn out of a filled neon core, which costs almost ten times as much. Reading where the jump occurs — after one electron, after two, after three — is how an unknown element\'s group is deduced from an IE table.' },
  { id: 'per-012', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Which pair shows a diagonal relationship?', opts: ['Na and K, same group', 'C and N, adjacent', 'Li and Mg, in different groups and periods', 'F and Cl, both halogens'], a: 2, why: 'Li~Mg, Be~Al, B~Si: the diagonal neighbours have similar charge/size ratios and hence similar chemistry (e.g. both Li and Mg form nitrides and burn in N₂).' },
  { id: 'per-013', topic: 'periodicity', skill: 'descriptive/periodic-groups', q: 'Which oxide is amphoteric?', opts: ['Na₂O, a group-1 oxide', 'Al₂O₃, a group-13 oxide', 'MgO, a group-2 oxide', 'SO₃, a non-metal oxide'], a: 1, why: 'Al₂O₃ reacts with both acids (→ Al³⁺) and bases (→ [Al(OH)₄]⁻). Amphoteric set: Al, Zn, Be, Sn, Pb oxides.', misconception: 'Amphoterism is not a property of "metal oxides" or "non-metal oxides" as blocks; it belongs to a specific short list — Al, Zn, Be, Sn, Pb — sitting on the metal/non-metal boundary. Al₂O₃ dissolves in acid to give Al³⁺ and in base to give the aluminate [Al(OH)₄]⁻. Assuming every metal oxide is basic gets Na₂O and MgO right and Al₂O₃ wrong.' },
  { id: 'per-014', topic: 'periodicity', skill: 'descriptive/periodic-groups', q: 'Across period 3, the oxides change from…', opts: ['basic, through amphoteric, to acidic', 'acidic on the left to basic on the right', 'neutral the whole way across', 'basic the whole way across'], a: 0, why: 'Metal oxides are basic, the metalloid oxide amphoteric, and non-metal oxides acidic — a periodic acid–base trend.' },
  { id: 'per-015', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'The inert-pair effect explains why…', opts: ['the noble gases are chemically inert', 'fluorine is unusually small for its group', 'transition-metal compounds are coloured', 'Tl⁺, Pb²⁺ and Bi³⁺ are unusually stable'], a: 3, why: 'For heavy p-block elements the ns² pair resists ionization, favouring an oxidation state two below the group valence (Pb²⁺ over Pb⁴⁺).' },
  { id: 'per-016', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Atomic radius depends on coordination/measurement, so quoted values can differ. Which comparison is still safe?', opts: ['metallic vs covalent radius of different elements', 'cation vs anion of unrelated atoms', 'radii within one consistent trend/definition', 'radius vs mass'], a: 2, why: 'Trends hold within a consistent definition; mixing metallic, covalent, and ionic radii across unrelated species is the trap.', misconception: 'Atomic radii are not a single measurable quantity: metallic, covalent, van der Waals and ionic radii are different definitions with different numbers for the same element. Comparisons are only meaningful within one consistent set, which is why tables always say which kind they list. Mixing a covalent radius with a van der Waals one can reverse an apparent trend entirely.' },
  { id: 'per-017', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Electronegativity scales differ. Which is defined from ionization energy and electron affinity?', opts: ['Pauling, from bond energies', 'Mulliken, from IE and EA', 'Allred–Rochow, from effective charge', 'Sanderson, from electron density'], a: 1, why: 'Mulliken electronegativity is the average of IE and EA. Pauling uses bond energies; Allred–Rochow uses Z_eff/r².' },
  { id: 'per-018', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Which has the highest first ionization energy?', opts: ['N', 'C', 'B', 'O'], a: 0, why: 'N (2p³ half-filled) exceeds O (which dips from pairing) — the local order across period 2 is B < C < O < N.' },
  { id: 'per-019', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Which element has the most exothermic (most negative) electron affinity overall?', opts: ['F, the most electronegative', 'S, in period 3', 'O, small and avid', 'Cl, also in period 3'], a: 3, why: 'Chlorine (~−349 kJ/mol) beats fluorine (~−328) because F\'s tiny shell suffers electron–electron repulsion on gaining an electron.', misconception: 'Electronegativity and electron affinity are different properties and they do not have to agree — which is exactly why this question catches people. <b>Electronegativity</b> is how strongly a <em>bonded</em> atom pulls on a shared pair; it is a relative scale with no units, and fluorine tops it. <b>Electron affinity</b> is a measured energy for an <em>isolated gaseous</em> atom accepting an electron, and chlorine wins it, because cramming an extra electron into fluorine\'s tiny 2p shell costs real repulsion energy. "F is the most electronegative" is true and simply does not settle this question.' },
  { id: 'per-020', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Down group 1, reactivity with water increases because…', opts: ['the atoms get steadily smaller', 'they gain protons and pull harder', 'the density of the metal rises', 'ionisation energy falls'], a: 3, why: 'Lower IE down the group means Cs releases its valence electron most readily — Li fizzes, Na darts, K ignites, Cs explodes.' },
  { id: 'per-021', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'The lanthanide contraction causes…', opts: ['Zr and Hf to have near-identical radii', 'the 5d elements to exceed the 4d in size', 'the actinides to contract instead', 'group 1 radii to expand sharply'], a: 0, why: 'Poor 4f shielding shrinks the lanthanides so much that the following 5d element (Hf) matches its 4d congener (Zr) in size — hence their hard separation.' },
  { id: 'per-022', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Why does electronegativity peak near fluorine and drop toward the bottom-left?', opts: ['atomic mass increases across a period', 'high Z_eff and a small radius', 'metals share electrons rather than take them', 'the noble-gas column distorts the trend'], a: 1, why: 'Electronegativity tracks Z_eff/radius — greatest for small, highly-charged top-right atoms; large, well-shielded bottom-left metals hold shared electrons weakly.' },
  { id: 'per-023', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'The most metallic (largest, lowest-IE) stable element among these is…', opts: ['Li', 'F', 'Cs', 'C'], a: 2, why: 'Cs sits lowest-left among stable elements: largest radius, lowest ionization energy, most metallic character (Fr is radioactive/rare).' },
  { id: 'per-024', topic: 'periodicity', skill: 'atomic/periodic-trends', q: 'Which best explains why noble gases have very high ionization energies but near-zero electron affinity?', opts: ['they are radioactive and short-lived', 'they behave as metals at low temperature', 'they are heavy compared to their neighbours', 'a filled valence shell resists both'], a: 3, why: 'The closed-shell octet resists both losing an electron (huge IE) and gaining one (the next electron would start a new, high-energy shell).', misconception: 'The noble gases\' inertness needs two separate statements, not one. A filled valence shell means the electrons are held very tightly (huge ionisation energy) <em>and</em> that there is no favourable low-energy orbital to accept another electron (electron affinity near zero, even slightly positive). Saying "they are stable" without splitting it into these two directions misses what a question about IE versus EA is asking.' },
  { id: 'per-025', tier: 3, topic: 'periodicity', skill: 'descriptive/periodic-groups', q: 'A period-3 element forms an acidic oxide, a covalent chloride that hydrolyses, and a −3 hydride. It is likely…', opts: ['P', 'Mg', 'Na', 'Ar'], a: 0, why: 'Phosphorus: P₄O₁₀ (acidic), PCl₃/PCl₅ (hydrolyse to H₃PO₃/H₃PO₄), PH₃ (−3 hydride). Non-metal behaviour on the right of period 3.', misconception: '"Its chloride hydrolyses" is not the same as "its chloride dissolves": NaCl and MgCl₂ dissolve to near-neutral solutions with the metal–chlorine relationship intact, whereas a covalent chloride like PCl₃ is destroyed by water to H₃PO₃ and HCl. All three clues describe a non-metal, and the acidic oxide alone already excludes every period-3 metal.' },
];

export const POLYMERS_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'pol-001', topic: 'polymers', skill: 'organic/polymers', q: 'A polymer is a large molecule built from repeating units called…', opts: ['isotopes', 'isomers', 'monomers', 'ions'], a: 2, why: 'Monomers link covalently into a long chain; the repeat unit reflects the monomer(s).' },
  { id: 'pol-002', topic: 'polymers', skill: 'organic/polymers', q: 'Polyethylene is made from…', opts: ['ethyne, HC≡CH', 'ethanol, by dehydration', 'ethane, C₂H₆', 'ethene, CH₂=CH₂'], a: 3, why: 'Ethene\'s C=C opens in chain-growth addition polymerization to give –(CH₂CH₂)ₙ–.' },
  { id: 'pol-003', topic: 'polymers', skill: 'organic/polymers', q: 'Which is a condensation polymer?', opts: ['nylon-6,6', 'polystyrene', 'polyethylene', 'PVC'], a: 0, why: 'Nylon forms by amide linkages between a diamine and a diacid, expelling water — step-growth condensation.' },
  { id: 'pol-004', topic: 'polymers', skill: 'organic/polymers', q: 'Addition polymerization typically requires the monomer to have…', opts: ['two –OH groups per monomer', 'a C=C double bond to open', 'a saturated ring such as cyclohexane, which opens on heating', 'a metal centre to coordinate'], a: 1, why: 'Chain-growth adds across the alkene π bond; vinyl monomers (ethene, styrene, vinyl chloride) are the classic feedstocks.' },
  { id: 'pol-005', topic: 'polymers', skill: 'organic/polymers', q: 'A thermoset plastic, once hardened…', opts: ['melts easily and can be reshaped', 'dissolves readily in warm water', 'cannot be remelted, being cross-linked', 'conducts electricity along the chain'], a: 2, why: 'Cross-links lock the network; heating degrades rather than melts it. Thermoplastics (no cross-links) soften and reflow.' },
  // ---- olympiad ----
  { id: 'pol-006', topic: 'polymers', skill: 'organic/polymers', q: 'The by-product of forming a polyester from a diol and a diacid is…', opts: ['CO₂ gas', 'none at all', 'HCl gas', 'water'], a: 3, why: 'Esterification of –OH with –COOH releases H₂O each linkage — the signature of step-growth condensation.' },
  { id: 'pol-007', topic: 'polymers', skill: 'organic/polymers', q: 'In chain-growth (addition) polymerization, high molecular weight is reached…', opts: ['early, at low conversion', 'only at very high conversion', 'never, at any conversion', 'only on prolonged heating'], a: 0, why: 'Individual chains grow rapidly to full length while monomer remains; MW is high from the start. Step-growth MW rises only near complete conversion.', misconception: 'Chain-growth and step-growth reach high molar mass in completely different ways, and this is the fastest way to tell a mechanism from data. In chain growth, individual chains reach full length almost immediately, so high-MW polymer coexists with unreacted monomer from the start. In step growth, everything grows together and the molar mass only climbs at the very end — the Carothers relation DP = 1/(1−p) means 99% conversion gives just DP 100.' },
  { id: 'pol-008', topic: 'polymers', skill: 'organic/polymers', q: 'The radical initiator in addition polymerization functions by…', opts: ['removing water from the monomer', 'making a radical that starts chains', 'cross-linking the finished polymer chains', 'lowering the reaction temperature'], a: 1, why: 'Peroxides/AIBN homolyse to radicals that attack the alkene, beginning propagation. Termination is by combination or disproportionation.' },
  { id: 'pol-009', topic: 'polymers', skill: 'organic/polymers', q: 'Which monomer pair makes a polyamide (nylon-6,6)?', opts: ['ethylene glycol + terephthalic acid', 'styrene alone', 'hexamethylenediamine + adipic acid', 'vinyl chloride alone'], a: 2, why: 'A diamine + a diacid form repeating amide bonds. (Ethylene glycol + terephthalic acid gives the polyester PET.)' },
  { id: 'pol-010', topic: 'polymers', skill: 'organic/polymers', q: 'PET (a polyester bottle plastic) is formed from…', opts: ['ethylene glycol + terephthalic acid', 'adipic acid with a diamine, as in nylon', 'propene, by addition', 'glucose, a natural monomer'], a: 0, why: 'Terephthalic acid + ethylene glycol condense to poly(ethylene terephthalate), releasing water.' },
  { id: 'pol-011', topic: 'polymers', skill: 'organic/polymers', q: 'Number-average molar mass Mₙ = 20 000 and weight-average Mᵂ = 30 000. The polydispersity index (PDI) is…', opts: ['0.67', '10 000', '2.0', '1.5'], a: 3, why: 'PDI = Mᵂ/Mₙ = 30 000/20 000 = 1.5. PDI = 1 only for perfectly uniform chains; higher means a broader distribution.', misconception: 'PDI is M̄w/M̄n and can never be less than 1, because the weight average always over-counts the longer chains. Getting 0.67 means the ratio was taken upside down. A PDI of 1.5 is typical of radical polymerisation, 2.0 of step growth, and only living polymerisation — or a ribosome, where the chain length is transcribed rather than left to statistics — approaches exactly 1.' },
  { id: 'pol-012', topic: 'polymers', skill: 'organic/polymers', q: 'Isotactic polypropylene (all methyl groups on one side) is…', opts: ['amorphous, soft and waxy', 'water-soluble from the polar CH₃', 'highly crystalline', 'a thermoset once formed'], a: 2, why: 'Regular (isotactic) stereochemistry lets chains pack into crystallites → higher density, strength, and melting point. Atactic PP is soft and amorphous.' },
  { id: 'pol-013', topic: 'polymers', skill: 'organic/polymers', q: 'Cross-linking (e.g. vulcanizing rubber with sulfur) changes the material by…', opts: ['lowering its melting point sharply', 'making it more rigid and elastic', 'making it dissolve in solvent', 'turning it into a conductor'], a: 1, why: 'Sulfur bridges tie chains together, converting soft rubber into a tougher, elastic, thermoset network.' },
  { id: 'pol-014', topic: 'polymers', skill: 'organic/polymers', q: 'Bakelite (phenol + formaldehyde) is a…', opts: ['thermoset condensation polymer', 'thermoplastic addition polymer', 'linear polyester', 'natural polymer'], a: 0, why: 'Phenol–formaldehyde builds a heavily cross-linked 3-D network by condensation (losing water) — one of the first thermosets.' },
  { id: 'pol-015', tier: 3, topic: 'polymers', skill: 'organic/polymers', q: 'Nylon-6 and nylon-6,6 are both polyamides with almost identical properties, but only one of them is a condensation polymer. Which, and why?', opts: ['nylon-6, because it uses one monomer', 'neither — polyamides are addition polymers', 'both, since both contain amide bonds', 'nylon-6,6 — diamine + diacid, losing water'], a: 3, why: 'The linkage type does not decide the mechanism; the <b>by-product</b> does. Nylon-6,6 joins hexamethylenediamine to adipic acid and loses H₂O at every bond — step-growth condensation. Nylon-6 comes from ring-opening polymerisation of a single monomer, caprolactam: the ring simply opens and adds on, with <b>nothing expelled</b>, so the repeat unit has exactly the monomer\'s formula. <span class="trap">"Contains amide bonds" and "was made by condensation" are different claims — proteins and nylon-6 both have peptide/amide backbones and only one of them loses water on forming.</span>', misconception: 'Condensation and addition classify the <em>reaction</em>, not the product\'s linkage — which is why nylon-6 and nylon-6,6 are both polyamides but not both condensation polymers. Nylon-6,6 condenses a diamine with a diacid and expels water; nylon-6 is a ring-opening polymerisation of caprolactam, losing nothing at all. Classifying by the amide bond in the product would put both in the same box and be wrong.' },
  { id: 'pol-016', topic: 'polymers', skill: 'organic/polymers', q: 'The degree of polymerization is…', opts: ['the melting point of the polymer', 'the polydispersity index M_w/M_n', 'repeat units per chain', 'the number of cross-links per chain'], a: 2, why: 'DP = average chain length = number-average molar mass ÷ molar mass of the repeat unit.' },
  { id: 'pol-017', topic: 'polymers', skill: 'organic/polymers', q: 'Teflon (PTFE) is made from tetrafluoroethylene by…', opts: ['condensation, losing HF', 'radical addition', 'ionic substitution of fluoride', 'oxidation by peroxide'], a: 1, why: 'F₂C=CF₂ undergoes chain-growth radical addition to –(CF₂CF₂)ₙ–; the strong C–F bonds make it inert and non-stick.' },
  { id: 'pol-018', topic: 'polymers', skill: 'organic/polymers', q: 'A polymer that softens and can be reshaped repeatedly on heating is a…', opts: ['thermoplastic', 'thermoset', 'elastomer network', 'cross-linked resin'], a: 0, why: 'Thermoplastics have no cross-links; chains slide past one another when heated, so they can be remelted and recycled.' },
  { id: 'pol-019', topic: 'polymers', skill: 'organic/polymers', q: 'From a backbone repeat unit –[CH₂–CHCl]–, the monomer is…', opts: ['ethene plus chlorine', 'chloroethane, CH₃CH₂Cl', 'PVC, the polymer itself', 'vinyl chloride'], a: 3, why: 'Reverse the addition: restore the C=C to get the vinyl monomer, chloroethene (vinyl chloride) → poly(vinyl chloride).' },
  { id: 'pol-020', topic: 'polymers', skill: 'organic/polymers', q: 'Cationic vs anionic vs radical addition polymerization differ mainly in…', opts: ['which monomer can be used', 'whether water is released as by-product', 'the reaction temperature alone', 'what the reactive chain end is'], a: 3, why: 'Each mechanism propagates through a different reactive centre; monomer electronics dictate which works (electron-rich → cationic, electron-poor → anionic).' },
  { id: 'pol-021', topic: 'polymers', skill: 'organic/polymers', q: 'Which statement about step-growth polymerization is correct?', opts: ['any two species react; high MW needs near-complete conversion', 'high MW appears almost immediately', 'it requires a radical initiator to start', 'it always yields an addition polymer instead, never a condensate'], a: 0, why: 'Monomers, dimers, and longer oligomers all couple; the number-average chain length rises sharply only as conversion approaches 100% (Carothers equation).' },
  { id: 'pol-022', topic: 'polymers', skill: 'organic/polymers', q: 'Kevlar\'s exceptional strength comes from…', opts: ['extensive covalent cross-linking', 'aligned chains, hydrogen bonded', 'reinforcement by embedded metal fibres', 'a very high polydispersity'], a: 1, why: 'Rigid para-aramid chains H-bond into sheets that stack, giving very high tensile strength along the fibre.' },
  { id: 'pol-023', topic: 'polymers', skill: 'organic/polymers', q: 'Which behaviour is NOT expected of a typical polyalkene such as polyethylene?', opts: ['general chemical inertness', 'good electrical insulation', 'reacting with dilute acid', 'flexibility at room temperature'], a: 2, why: 'The backbone is a saturated hydrocarbon: no polar bonds, no lone pairs, no π system, nothing for an acid or base to attack — so it is inert, insulating and flexible. That inertness is exactly what makes polyethylene useful for containers and exactly why it persists in the environment: the same missing reactive site defeats both reagents and micro-organisms.', misconception: 'The polyethylene backbone is a saturated hydrocarbon, and saturated hydrocarbons are chemically dull — no polar bonds, no π system, nothing for an acid or base to attack. That inertness is the material property being sold (bottles, pipes, bags) and it is also the disposal problem. Expecting an "organic polymer" to be chemically reactive confuses functional-group chemistry with backbone chemistry.' },
  { id: 'pol-024', tier: 3, topic: 'polymers', skill: 'organic/polymers', q: 'The Carothers equation shows that to reach a high degree of polymerization in step-growth, you need…', opts: ['a large excess of one of the monomers', 'a consistently low temperature', 'a radical initiator throughout', 'exact 1:1 and high conversion'], a: 3, why: 'DP = 1/(1−p); even p = 0.99 gives only DP ≈ 100. Any stoichiometric imbalance caps the chain length, so monomer purity and balance are critical.', misconception: 'Step-growth polymerisation needs <em>exact</em> 1:1 stoichiometry, and this is not a nicety — an excess of one monomer caps the chain ends with the same group and stops growth dead. Combined with DP = 1/(1−p), which demands 99% conversion for a chain of only a hundred units, it explains why nylon is polymerised for hours under vacuum. A large excess of one monomer, the intuitive way to "drive it forward", makes the product worse.' , why2: 'Two numbers make the tyranny obvious. First conversion: DP = 1/(1 − p) gives DP = 10 at p = 0.90, 100 at p = 0.99, 1000 at p = 0.999. Nylon needs DP in the hundreds, so 99% conversion is the entry ticket, not a good result. Second, stoichiometry: with a monomer ratio r = N<sub>A</sub>/N<sub>B</sub>, the ceiling even at complete conversion is DP = (1 + r)/(1 − r) — so a mere 1% excess of one monomer (r = 0.99) caps the chain at 199 units however long you cook it. That is why step-growth polymerisation lives or dies on monomer purity and exact balance, and why chain-growth, where each individual chain reaches full length in seconds and unreacted monomer just sits there, has no equivalent constraint.' },
  { id: 'pol-025', topic: 'polymers', skill: 'organic/polymers', q: 'Copolymer types include block, alternating, random, and graft. A block copolymer consists of…', opts: ['long runs of one monomer, then another', 'a single monomer repeated', 'the two monomers mixed at random', 'a cross-linked three-dimensional network'], a: 0, why: 'Block copolymers (e.g. SBS rubber) join homopolymer segments end-to-end, giving materials with domains of each block\'s properties.' },
];
