// Quiz banks for the periodicity and polymers modules.
// 5 warm-ups then 20 CCC/CCO/USNCO-style. All original.
import type { QuizQ } from './framework';

export const PERIODICITY_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'per-001', topic: 'periodicity', q: 'Across a period (left → right), atomic radius generally…', opts: ['increases', 'decreases', 'stays constant', 'doubles'], a: 1, why: 'Rising effective nuclear charge pulls the same-shell electrons in tighter, so radius shrinks across a period.' },
  { id: 'per-002', topic: 'periodicity', q: 'Down a group, first ionization energy generally…', opts: ['increases', 'decreases', 'stays constant', 'is zero'], a: 1, why: 'Valence electrons occupy higher shells farther from the nucleus and are better shielded, so they are easier to remove.' },
  { id: 'per-003', topic: 'periodicity', q: 'The most electronegative element is…', opts: ['O', 'F', 'Cl', 'Cs'], a: 1, why: 'Fluorine (Pauling 4.0) tops the scale; electronegativity rises toward the top-right (excluding noble gases).' },
  { id: 'per-004', topic: 'periodicity', q: 'Which is the largest species?', opts: ['Na', 'Na⁺', 'Mg²⁺', 'Al³⁺'], a: 0, why: 'Neutral Na keeps its 3s electron and full shell; cations lose a shell and shrink further with charge.', misconception: 'A cation is always smaller than its parent atom and an anion always larger — the electron count, not the nuclear charge, is what changed. Na loses its entire 3s shell to become Na⁺, so the drop is a whole quantum level rather than a small contraction. Ranking these by "more charge, bigger ion" inverts the answer; ranking by electron configuration gets it right every time.' },
  { id: 'per-005', topic: 'periodicity', q: 'Metallic character generally increases…', opts: ['up and to the right', 'down and to the left', 'toward fluorine', 'toward helium'], a: 1, why: 'Elements lose electrons more readily down a group and to the left — the metals occupy the lower-left of the table.' },
  // ---- olympiad ----
  { id: 'per-006', topic: 'periodicity', q: 'First ionization energy dips from Be to B because…', opts: ['B is larger', 'the electron removed from B is in a higher-energy 2p orbital', 'B has more protons', 'Be is a metalloid'], a: 1, why: 'Be is 2s²; B\'s outermost electron is a single 2p, higher in energy and better shielded by the 2s pair — easier to remove despite the extra proton.' },
  { id: 'per-007', topic: 'periodicity', q: 'Ionization energy dips from N to O because…', opts: ['O is smaller', 'O\'s 2p⁴ has a paired electron whose repulsion aids removal', 'N has a full shell', 'O is more electronegative'], a: 1, why: 'N is 2p³ (half-filled, all unpaired, extra stable). O must pair a fourth 2p electron; that pairing repulsion lowers its IE below nitrogen\'s.' },
  { id: 'per-008', topic: 'periodicity', q: 'Electron affinity of fluorine is LESS exothermic than chlorine\'s because…', opts: ['F is less electronegative', 'F\'s small 2p shell has high electron–electron repulsion', 'Cl has more protons', 'F is a gas'], a: 1, why: 'Adding an electron to F\'s compact 2p subshell crowds it, so the energy released is smaller than for the roomier Cl — the classic F < Cl anomaly.' },
  { id: 'per-009', topic: 'periodicity', q: 'Using Slater\'s rules, the effective nuclear charge felt by a 3p electron in sulfur (Z = 16) is about…', opts: ['16.0', '5.5', '10.9', '1.0'], a: 2, why: 'S = 1s²2s²2p⁶3s²3p⁴. Same-shell (n=3) electrons shield 0.35 each (5 others → 1.75); n−1 shell (8 e⁻) shield 0.85 each (6.8); inner (2 e⁻) 1.00 (2.0). S = 10.55 → Z_eff ≈ 16 − 10.55 = 5.45 ≈ 5.5.', misconception: 'Slater\'s rules do not shield all inner electrons equally, and using Z minus the total electron count is the usual shortcut that fails. Same-shell electrons contribute 0.35 each, the (n−1) shell 0.85, and anything deeper 1.00 — which for sulfur\'s 3p electron gives Z_eff ≈ 5.45, not 16 and not 6. The graded values are the whole point of the rules.' },
  { id: 'per-010', topic: 'periodicity', q: 'Rank ionic radii: O²⁻, F⁻, Na⁺, Mg²⁺ (all 10 electrons)…', opts: ['Mg²⁺ > Na⁺ > F⁻ > O²⁻', 'O²⁻ > F⁻ > Na⁺ > Mg²⁺', 'all equal', 'F⁻ > O²⁻ > Mg²⁺ > Na⁺'], a: 1, why: 'Isoelectronic: more protons pull the same 10 electrons tighter. O (8p) is largest, Mg (12p) smallest.' },
  { id: 'per-011', topic: 'periodicity', q: 'The second ionization energy of sodium is enormously larger than its first because…', opts: ['Na⁺ is radioactive', 'the second electron comes from the filled n=2 (noble-gas) core', 'sodium is a metal', 'shielding increases'], a: 1, why: 'After losing 3s¹, Na⁺ has a neon core; removing a tightly held, unshielded 2p electron costs ~10× more. The jump reveals one valence electron → group 1.', misconception: 'The huge jump between successive ionisation energies is a <em>configuration</em> signal, not a size effect, and its position identifies the group. Sodium\'s first electron leaves the 3s; the second has to be torn out of a filled neon core, which costs almost ten times as much. Reading where the jump occurs — after one electron, after two, after three — is how an unknown element\'s group is deduced from an IE table.' },
  { id: 'per-012', topic: 'periodicity', q: 'Which pair shows a diagonal relationship?', opts: ['Na and K', 'Li and Mg', 'C and N', 'F and Cl'], a: 1, why: 'Li~Mg, Be~Al, B~Si: the diagonal neighbours have similar charge/size ratios and hence similar chemistry (e.g. both Li and Mg form nitrides and burn in N₂).' },
  { id: 'per-013', topic: 'periodicity', q: 'Which oxide is amphoteric?', opts: ['Na₂O', 'MgO', 'Al₂O₃', 'SO₃'], a: 2, why: 'Al₂O₃ reacts with both acids (→ Al³⁺) and bases (→ [Al(OH)₄]⁻). Amphoteric set: Al, Zn, Be, Sn, Pb oxides.', misconception: 'Amphoterism is not a property of "metal oxides" or "non-metal oxides" as blocks; it belongs to a specific short list — Al, Zn, Be, Sn, Pb — sitting on the metal/non-metal boundary. Al₂O₃ dissolves in acid to give Al³⁺ and in base to give the aluminate [Al(OH)₄]⁻. Assuming every metal oxide is basic gets Na₂O and MgO right and Al₂O₃ wrong.' },
  { id: 'per-014', topic: 'periodicity', q: 'Across period 3, the oxides change from…', opts: ['acidic to basic', 'basic (Na₂O) through amphoteric (Al₂O₃) to acidic (SO₃, Cl₂O₇)', 'all neutral', 'all basic'], a: 1, why: 'Metal oxides are basic, the metalloid oxide amphoteric, and non-metal oxides acidic — a periodic acid–base trend.' },
  { id: 'per-015', topic: 'periodicity', q: 'The inert-pair effect explains why…', opts: ['noble gases are inert', 'Tl⁺, Pb²⁺, Bi³⁺ (2 below the group max) are unusually stable', 'transition metals are colored', 'F is small'], a: 1, why: 'For heavy p-block elements the ns² pair resists ionization, favouring an oxidation state two below the group valence (Pb²⁺ over Pb⁴⁺).' },
  { id: 'per-016', topic: 'periodicity', q: 'Atomic radius depends on coordination/measurement, so quoted values can differ. Which comparison is still safe?', opts: ['metallic vs covalent radius of different elements', 'radii within one consistent trend/definition', 'cation vs anion of unrelated atoms', 'radius vs mass'], a: 1, why: 'Trends hold within a consistent definition; mixing metallic, covalent, and ionic radii across unrelated species is the trap.', misconception: 'Atomic radii are not a single measurable quantity: metallic, covalent, van der Waals and ionic radii are different definitions with different numbers for the same element. Comparisons are only meaningful within one consistent set, which is why tables always say which kind they list. Mixing a covalent radius with a van der Waals one can reverse an apparent trend entirely.' },
  { id: 'per-017', topic: 'periodicity', q: 'Electronegativity scales differ. Which is defined from ionization energy and electron affinity?', opts: ['Pauling', 'Mulliken (χ ≈ ½(IE + EA))', 'Allred–Rochow', 'Sanderson'], a: 1, why: 'Mulliken electronegativity is the average of IE and EA. Pauling uses bond energies; Allred–Rochow uses Z_eff/r².' },
  { id: 'per-018', topic: 'periodicity', q: 'Which has the highest first ionization energy?', opts: ['B', 'C', 'N', 'O'], a: 2, why: 'N (2p³ half-filled) exceeds O (which dips from pairing) — the local order across period 2 is B < C < O < N.' },
  { id: 'per-019', topic: 'periodicity', q: 'Which element has the most exothermic (most negative) electron affinity overall?', opts: ['F', 'Cl', 'O', 'S'], a: 1, why: 'Chlorine (~−349 kJ/mol) beats fluorine (~−328) because F\'s tiny shell suffers electron–electron repulsion on gaining an electron.', misconception: 'Electronegativity and electron affinity are different properties and they do not have to agree — which is exactly why this question catches people. <b>Electronegativity</b> is how strongly a <em>bonded</em> atom pulls on a shared pair; it is a relative scale with no units, and fluorine tops it. <b>Electron affinity</b> is a measured energy for an <em>isolated gaseous</em> atom accepting an electron, and chlorine wins it, because cramming an extra electron into fluorine\'s tiny 2p shell costs real repulsion energy. "F is the most electronegative" is true and simply does not settle this question.' },
  { id: 'per-020', topic: 'periodicity', q: 'Down group 1, reactivity with water increases because…', opts: ['atoms get smaller', 'ionization energy falls, so the metal loses its electron more easily', 'density rises', 'they gain protons'], a: 1, why: 'Lower IE down the group means Cs releases its valence electron most readily — Li fizzes, Na darts, K ignites, Cs explodes.' },
  { id: 'per-021', topic: 'periodicity', q: 'The lanthanide contraction causes…', opts: ['5d elements to be larger than 4d', 'Zr and Hf to have nearly identical radii', 'actinides to shrink', 'group 1 to expand'], a: 1, why: 'Poor 4f shielding shrinks the lanthanides so much that the following 5d element (Hf) matches its 4d congener (Zr) in size — hence their hard separation.' },
  { id: 'per-022', topic: 'periodicity', q: 'Why does electronegativity peak near fluorine and drop toward the bottom-left?', opts: ['mass increases', 'high Z_eff and small radius maximize an atom\'s pull on bonding electrons at the top-right', 'metals share electrons', 'noble gases interfere'], a: 1, why: 'Electronegativity tracks Z_eff/radius — greatest for small, highly-charged top-right atoms; large, well-shielded bottom-left metals hold shared electrons weakly.' },
  { id: 'per-023', topic: 'periodicity', q: 'The most metallic (largest, lowest-IE) stable element among these is…', opts: ['Li', 'Cs', 'F', 'C'], a: 1, why: 'Cs sits lowest-left among stable elements: largest radius, lowest ionization energy, most metallic character (Fr is radioactive/rare).' },
  { id: 'per-024', topic: 'periodicity', q: 'Which best explains why noble gases have very high ionization energies but near-zero electron affinity?', opts: ['they are radioactive', 'a filled valence shell is stable — hard to remove from, and no favourable orbital to add to', 'they are heavy', 'they are metals'], a: 1, why: 'The closed-shell octet resists both losing an electron (huge IE) and gaining one (the next electron would start a new, high-energy shell).', misconception: 'The noble gases\' inertness needs two separate statements, not one. A filled valence shell means the electrons are held very tightly (huge ionisation energy) <em>and</em> that there is no favourable low-energy orbital to accept another electron (electron affinity near zero, even slightly positive). Saying "they are stable" without splitting it into these two directions misses what a question about IE versus EA is asking.' },
  { id: 'per-025', topic: 'periodicity', q: 'A period-3 element forms an acidic oxide, a covalent chloride that hydrolyses, and a −3 hydride. It is likely…', opts: ['Na', 'Mg', 'P', 'Ar'], a: 2, why: 'Phosphorus: P₄O₁₀ (acidic), PCl₃/PCl₅ (hydrolyse to H₃PO₃/H₃PO₄), PH₃ (−3 hydride). Non-metal behaviour on the right of period 3.' },
];

export const POLYMERS_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'pol-001', topic: 'polymers', q: 'A polymer is a large molecule built from repeating units called…', opts: ['isotopes', 'monomers', 'isomers', 'ions'], a: 1, why: 'Monomers link covalently into a long chain; the repeat unit reflects the monomer(s).' },
  { id: 'pol-002', topic: 'polymers', q: 'Polyethylene is made from…', opts: ['ethene (ethylene)', 'ethanol', 'ethane', 'ethyne'], a: 0, why: 'Ethene\'s C=C opens in chain-growth addition polymerization to give –(CH₂CH₂)ₙ–.' },
  { id: 'pol-003', topic: 'polymers', q: 'Which is a condensation polymer?', opts: ['polyethylene', 'polystyrene', 'nylon-6,6', 'PVC'], a: 2, why: 'Nylon forms by amide linkages between a diamine and a diacid, expelling water — step-growth condensation.' },
  { id: 'pol-004', topic: 'polymers', q: 'Addition polymerization typically requires the monomer to have…', opts: ['a C=C double bond', 'two –OH groups', 'a ring', 'a metal'], a: 0, why: 'Chain-growth adds across the alkene π bond; vinyl monomers (ethene, styrene, vinyl chloride) are the classic feedstocks.' },
  { id: 'pol-005', topic: 'polymers', q: 'A thermoset plastic, once hardened…', opts: ['melts easily on heating', 'cannot be remelted (cross-linked network)', 'dissolves in water', 'conducts electricity'], a: 1, why: 'Cross-links lock the network; heating degrades rather than melts it. Thermoplastics (no cross-links) soften and reflow.' },
  // ---- olympiad ----
  { id: 'pol-006', topic: 'polymers', q: 'The by-product of forming a polyester from a diol and a diacid is…', opts: ['CO₂', 'water', 'HCl', 'none'], a: 1, why: 'Esterification of –OH with –COOH releases H₂O each linkage — the signature of step-growth condensation.' },
  { id: 'pol-007', topic: 'polymers', q: 'In chain-growth (addition) polymerization, high molecular weight is reached…', opts: ['only at very high conversion', 'early, even at low conversion', 'never', 'only by heating'], a: 1, why: 'Individual chains grow rapidly to full length while monomer remains; MW is high from the start. Step-growth MW rises only near complete conversion.', misconception: 'Chain-growth and step-growth reach high molar mass in completely different ways, and this is the fastest way to tell a mechanism from data. In chain growth, individual chains reach full length almost immediately, so high-MW polymer coexists with unreacted monomer from the start. In step growth, everything grows together and the molar mass only climbs at the very end — the Carothers relation DP = 1/(1−p) means 99% conversion gives just DP 100.' },
  { id: 'pol-008', topic: 'polymers', q: 'The radical initiator in addition polymerization functions by…', opts: ['removing water', 'generating a radical that adds to the monomer and starts a chain', 'cross-linking', 'lowering temperature'], a: 1, why: 'Peroxides/AIBN homolyse to radicals that attack the alkene, beginning propagation. Termination is by combination or disproportionation.' },
  { id: 'pol-009', topic: 'polymers', q: 'Which monomer pair makes a polyamide (nylon-6,6)?', opts: ['ethylene glycol + terephthalic acid', 'hexamethylenediamine + adipic acid', 'styrene alone', 'vinyl chloride alone'], a: 1, why: 'A diamine + a diacid form repeating amide bonds. (Ethylene glycol + terephthalic acid gives the polyester PET.)' },
  { id: 'pol-010', topic: 'polymers', q: 'PET (a polyester bottle plastic) is formed from…', opts: ['ethylene glycol + terephthalic acid', 'adipic acid + a diamine', 'propene', 'glucose'], a: 0, why: 'Terephthalic acid + ethylene glycol condense to poly(ethylene terephthalate), releasing water.' },
  { id: 'pol-011', topic: 'polymers', q: 'Number-average molar mass Mₙ = 20 000 and weight-average Mᵂ = 30 000. The polydispersity index (PDI) is…', opts: ['0.67', '1.5', '2.0', '10 000'], a: 1, why: 'PDI = Mᵂ/Mₙ = 30 000/20 000 = 1.5. PDI = 1 only for perfectly uniform chains; higher means a broader distribution.', misconception: 'PDI is M̄w/M̄n and can never be less than 1, because the weight average always over-counts the longer chains. Getting 0.67 means the ratio was taken upside down. A PDI of 1.5 is typical of radical polymerisation, 2.0 of step growth, and only living polymerisation — or a ribosome, where the chain length is transcribed rather than left to statistics — approaches exactly 1.' },
  { id: 'pol-012', topic: 'polymers', q: 'Isotactic polypropylene (all methyl groups on one side) is…', opts: ['amorphous and soft', 'highly crystalline and strong', 'water-soluble', 'a thermoset'], a: 1, why: 'Regular (isotactic) stereochemistry lets chains pack into crystallites → higher density, strength, and melting point. Atactic PP is soft and amorphous.' },
  { id: 'pol-013', topic: 'polymers', q: 'Cross-linking (e.g. vulcanizing rubber with sulfur) changes the material by…', opts: ['lowering its melting point', 'making it more rigid and elastic, resisting flow', 'dissolving it', 'making it a conductor'], a: 1, why: 'Sulfur bridges tie chains together, converting soft rubber into a tougher, elastic, thermoset network.' },
  { id: 'pol-014', topic: 'polymers', q: 'Bakelite (phenol + formaldehyde) is a…', opts: ['thermoplastic addition polymer', 'thermoset condensation polymer', 'linear polyester', 'natural polymer'], a: 1, why: 'Phenol–formaldehyde builds a heavily cross-linked 3-D network by condensation (losing water) — one of the first thermosets.' },
  { id: 'pol-015', topic: 'polymers', q: 'Nylon-6 and nylon-6,6 are both polyamides with almost identical properties, but only one of them is a condensation polymer. Which, and why?', opts: ['nylon-6, because it uses one monomer', 'nylon-6,6, because it condenses a diamine with a diacid and expels water', 'both, since both contain amide bonds', 'neither — polyamides are addition polymers'], a: 1, why: 'The linkage type does not decide the mechanism; the <b>by-product</b> does. Nylon-6,6 joins hexamethylenediamine to adipic acid and loses H₂O at every bond — step-growth condensation. Nylon-6 comes from ring-opening polymerisation of a single monomer, caprolactam: the ring simply opens and adds on, with <b>nothing expelled</b>, so the repeat unit has exactly the monomer\'s formula. <span class="trap">"Contains amide bonds" and "was made by condensation" are different claims — proteins and nylon-6 both have peptide/amide backbones and only one of them loses water on forming.</span>', misconception: 'Condensation and addition classify the <em>reaction</em>, not the product\'s linkage — which is why nylon-6 and nylon-6,6 are both polyamides but not both condensation polymers. Nylon-6,6 condenses a diamine with a diacid and expels water; nylon-6 is a ring-opening polymerisation of caprolactam, losing nothing at all. Classifying by the amide bond in the product would put both in the same box and be wrong.' },
  { id: 'pol-016', topic: 'polymers', q: 'The degree of polymerization is…', opts: ['the number of repeat units per chain (Mₙ/M_repeat)', 'the PDI', 'the melting point', 'the number of cross-links'], a: 0, why: 'DP = average chain length = number-average molar mass ÷ molar mass of the repeat unit.' },
  { id: 'pol-017', topic: 'polymers', q: 'Teflon (PTFE) is made from tetrafluoroethylene by…', opts: ['condensation', 'radical addition polymerization', 'ionic substitution', 'oxidation'], a: 1, why: 'F₂C=CF₂ undergoes chain-growth radical addition to –(CF₂CF₂)ₙ–; the strong C–F bonds make it inert and non-stick.' },
  { id: 'pol-018', topic: 'polymers', q: 'A polymer that softens and can be reshaped repeatedly on heating is a…', opts: ['thermoset', 'thermoplastic', 'elastomer network', 'cross-linked resin'], a: 1, why: 'Thermoplastics have no cross-links; chains slide past one another when heated, so they can be remelted and recycled.' },
  { id: 'pol-019', topic: 'polymers', q: 'From a backbone repeat unit –[CH₂–CHCl]–, the monomer is…', opts: ['vinyl chloride (CH₂=CHCl)', 'chloroethane', 'PVC', 'ethene'], a: 0, why: 'Reverse the addition: restore the C=C to get the vinyl monomer, chloroethene (vinyl chloride) → poly(vinyl chloride).' },
  { id: 'pol-020', topic: 'polymers', q: 'Cationic vs anionic vs radical addition polymerization differ mainly in…', opts: ['the monomer used', 'the nature of the reactive chain end (carbocation, carbanion, or radical)', 'the temperature only', 'whether water is released'], a: 1, why: 'Each mechanism propagates through a different reactive centre; monomer electronics dictate which works (electron-rich → cationic, electron-poor → anionic).' },
  { id: 'pol-021', topic: 'polymers', q: 'Which statement about step-growth polymerization is correct?', opts: ['high MW appears immediately', 'any two monomers/oligomers can react, and high MW needs near-complete conversion', 'it needs a radical initiator', 'it always makes addition polymers'], a: 1, why: 'Monomers, dimers, and longer oligomers all couple; the number-average chain length rises sharply only as conversion approaches 100% (Carothers equation).' },
  { id: 'pol-022', topic: 'polymers', q: 'Kevlar\'s exceptional strength comes from…', opts: ['cross-linking only', 'aligned aromatic amide chains with extensive interchain hydrogen bonding', 'metal reinforcement', 'high PDI'], a: 1, why: 'Rigid para-aramid chains H-bond into sheets that stack, giving very high tensile strength along the fibre.' },
  { id: 'pol-023', topic: 'polymers', q: 'Which behaviour is NOT expected of a typical polyalkene such as polyethylene?', opts: ['chemical inertness', 'electrical insulation', 'reacting readily with dilute acids or bases', 'flexibility'], a: 2, why: 'The backbone is a saturated hydrocarbon: no polar bonds, no lone pairs, no π system, nothing for an acid or base to attack — so it is inert, insulating and flexible. That inertness is exactly what makes polyethylene useful for containers and exactly why it persists in the environment: the same missing reactive site defeats both reagents and micro-organisms.', misconception: 'The polyethylene backbone is a saturated hydrocarbon, and saturated hydrocarbons are chemically dull — no polar bonds, no π system, nothing for an acid or base to attack. That inertness is the material property being sold (bottles, pipes, bags) and it is also the disposal problem. Expecting an "organic polymer" to be chemically reactive confuses functional-group chemistry with backbone chemistry.' },
  { id: 'pol-024', topic: 'polymers', q: 'The Carothers equation shows that to reach a high degree of polymerization in step-growth, you need…', opts: ['a large excess of one monomer', 'an exact 1:1 stoichiometry and very high conversion', 'a radical initiator', 'low temperature'], a: 1, why: 'DP = 1/(1−p); even p = 0.99 gives only DP ≈ 100. Any stoichiometric imbalance caps the chain length, so monomer purity and balance are critical.', misconception: 'Step-growth polymerisation needs <em>exact</em> 1:1 stoichiometry, and this is not a nicety — an excess of one monomer caps the chain ends with the same group and stops growth dead. Combined with DP = 1/(1−p), which demands 99% conversion for a chain of only a hundred units, it explains why nylon is polymerised for hours under vacuum. A large excess of one monomer, the intuitive way to "drive it forward", makes the product worse.' },
  { id: 'pol-025', topic: 'polymers', q: 'Copolymer types include block, alternating, random, and graft. A block copolymer consists of…', opts: ['a single monomer', 'long runs of one monomer joined to long runs of another', 'randomly mixed monomers', 'a cross-linked network'], a: 1, why: 'Block copolymers (e.g. SBS rubber) join homopolymer segments end-to-end, giving materials with domains of each block\'s properties.' },
];
