// Advanced (CCO) quiz banks: analytical & quantitative, spectroscopy + synthesis.
// 5 warm-ups then 20 CCO/IChO-level. All original.
import type { QuizQ } from './framework';

export const ANALYTICAL_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'ana-001', topic: 'analytical', skill: 'lab/titration-technique', q: 'A primary standard must be…', opts: ['a strong acid or base', 'volatile, for easy drying', 'coloured, to see the endpoint', 'pure, stable, known'], a: 3, why: 'Primary standards (KHP, Na₂CO₃, K₂Cr₂O₇) are pure, non-hygroscopic, and stoichiometrically exact so they can be weighed directly.' },
  { id: 'ana-002', topic: 'analytical', skill: 'lab/titration-technique', q: 'In a titration, the equivalence point is where…', opts: ['the indicator first changes colour', 'the pH reaches exactly 7, whatever acid and base are used', 'the moles of titrant stoichiometrically equal the moles of analyte', 'the burette has been emptied'], a: 2, why: 'The endpoint (indicator change) only approximates the true equivalence point.', misconception: 'The equivalence point and the endpoint are not the same thing, and the difference is a real source of error rather than pedantry. The equivalence point is where the stoichiometry balances; the endpoint is where the indicator you happened to choose changes colour. A well-chosen indicator makes the gap negligible, a badly chosen one does not — which is why indicator selection is decided by the <em>equivalence pH</em>, and why a blank titration is worth running.' },
  { id: 'ana-003', topic: 'analytical', skill: 'lab/titration-technique', q: 'EDTA forms complexes with metal ions in a ratio of…', opts: ['2:1', '1:1', '1:6', '3:1'], a: 1, why: 'EDTA is hexadentate — one molecule wraps a single metal ion, always 1:1 regardless of charge.' },
  { id: 'ana-004', topic: 'analytical', q: 'Gravimetric analysis determines an analyte by measuring…', opts: ['the mass of a precipitate', 'absorbance of the solution', 'the volume of titrant used', 'the pH at the endpoint'], a: 0, why: 'The analyte is converted to an insoluble compound of known formula, filtered, dried, and weighed.' },
  { id: 'ana-005', topic: 'analytical', skill: 'lab/titration-technique', q: 'A back-titration is used when…', opts: ['the analyte is too strongly coloured', 'the titrant is unstable in storage', 'no indicator exists that changes colour in acidic solution', 'the direct reaction is slow, or the analyte is volatile'], a: 3, why: 'Add a known excess of reagent, let it react fully, then titrate the leftover — used for antacids (CaCO₃), etc.' },
  // ---- CCO-level ----
  { id: 'ana-006', topic: 'analytical', skill: 'lab/titration-technique', q: 'EDTA titrations are buffered at high pH mainly to…', opts: ['speed the complexation reaction up', 'keep the indicator in solution', 'keep EDTA fully deprotonated as Y⁴⁻', 'prevent oxidation of the metal ion'], a: 2, why: 'The conditional constant K′ = α₄·K_f; at low pH most EDTA is protonated (small α₄), so K′ collapses and the endpoint blurs.', misconception: 'The buffer in an EDTA titration is doing chemistry, not housekeeping. Only the fully deprotonated Y⁴⁻ binds the metal, so pH sets α₄ and therefore K′ = α₄K_f — the constant that decides whether an endpoint break exists at all. Treating the buffer as merely "keeping conditions steady" misses that lowering the pH by three units can destroy the titration outright.' },
  { id: 'ana-007', topic: 'analytical', q: 'The conditional formation constant K′ for a metal–EDTA complex is defined as…', opts: ['K_f only', 'α₄·K_f', 'K_f/α₄', 'α₄/K_f'], a: 1, why: 'α₄ is the fraction of EDTA present as Y⁴⁻ at that pH; multiplying folds the pH dependence into one effective constant.' },
  { id: 'ana-008', topic: 'analytical', q: 'By the Debye–Hückel limiting law, increasing ionic strength causes the mean activity coefficient γ± of a salt to…', opts: ['decrease below 1', 'increase above 1', 'stay exactly 1', 'become negative'], a: 0, why: 'log γ± = −0.51 z₊|z₋|√I (at 25 °C, dilute): the ionic atmosphere screens the ions, lowering effective concentration.' },
  { id: 'ana-009', tier: 3, topic: 'analytical', q: 'Adding inert KNO₃ to a saturated AgCl solution causes its solubility to…', opts: ['decrease, by the common-ion effect', 'fall effectively to zero', 'stay exactly the same', 'increase slightly'], a: 3, why: 'Higher ionic strength lowers γ± of Ag⁺ and Cl⁻; since Ksp = γ²[Ag⁺][Cl⁻] is fixed, the concentrations must rise. The "diverse ion effect."', misconception: 'Adding an inert salt <em>increases</em> the solubility of AgCl, which looks like a violation of Le Chatelier until activities are put back in. Ksp is a product of activities, and raising the ionic strength lowers γ± — so the concentrations must rise to keep the product constant. This diverse-ion effect is the opposite of the common-ion effect, and confusing the two is the trap: KNO₃ shares no ion with AgCl.' , why2: 'Picture the ionic atmosphere. Every Ag⁺ in solution gathers a loose shell of the added NO₃⁻, and every Cl⁻ a shell of K⁺. Screened from each other, the two ions meet and stick to the lattice less readily than their concentrations suggest — that is precisely what γ± &lt; 1 means. Since the true equilibrium is fixed on <em>activities</em>, K<sub>sp</sub> = γ±²[Ag⁺][Cl⁻] must hold with γ± now smaller, so the concentrations have to rise: more AgCl dissolves. The general shape is worth remembering: an inert electrolyte always increases the solubility of a sparingly soluble salt, and only a <em>common</em> ion decreases it.' },
  { id: 'ana-010', topic: 'analytical', skill: 'lab/titration-technique', q: 'In a KMnO₄ titration, no external indicator is needed because…', opts: ['MnO₄⁻ is itself a primary standard', 'MnO₄⁻ is self-indicating', 'the analyte is strongly coloured', 'the endpoint always falls at pH 7'], a: 1, why: 'Deep-purple permanganate is decolorized as it reacts; one drop past equivalence tints the solution permanently pink.' },
  { id: 'ana-011', topic: 'analytical', skill: 'lab/titration-technique', q: 'A 0.1000 g sample needing 12.00 mL of 0.05000 M EDTA contains how many mmol of metal?', opts: ['1.20', '0.240', '0.600', '0.0600'], a: 2, why: '1:1 stoichiometry → mmol metal = 0.05000 M × 12.00 mL = 0.600 mmol.' },
  { id: 'ana-012', tier: 3, topic: 'analytical', q: 'Chloride is precipitated as AgCl (M = 143.3) and weighs 0.2870 g. The mass of Cl (M = 35.45) is…', opts: ['0.0355 g', '0.1435 g', '0.2870 g', '0.0710 g'], a: 3, why: 'Gravimetric factor = 35.45/143.3 = 0.2474 → 0.2870 × 0.2474 = 0.0710 g Cl.', misconception: 'The gravimetric factor is a MASS ratio of analyte to the whole weighed solid (35.45/143.3 = 0.2474), not "one atom out of two, so halve it". Halving 0.2870 g assumes a 1:1 atom ratio is a 1:1 mass ratio, but silver is four times heavier than chlorine, so chloride is only about a quarter of the precipitate.' },
  { id: 'ana-013', topic: 'analytical', q: 'The "5% rule" fails and a quadratic is needed when…', opts: ['ionisation exceeds 5%', 'Ka is extremely small', 'the acid happens to be diprotic', 'the temperature is unusually high'], a: 0, why: 'Neglecting x in (C₀ − x) is only safe when x is small; strong-ish weak acids or dilute solutions break it.' },
  { id: 'ana-014', topic: 'analytical', skill: 'lab/titration-technique', q: 'A Gran plot linearizes a titration curve to find the equivalence point by plotting…', opts: ['pH directly against volume', '(V₀+V)·[H⁺] against titrant volume', 'log V against pH', 'absorbance against volume'], a: 1, why: 'Gran functions turn the sigmoid into straight lines whose x-intercept gives V_eq precisely — robust when the endpoint break is weak.' },
  { id: 'ana-015', topic: 'analytical', skill: 'lab/titration-technique', q: 'In complexometric titration, Eriochrome Black T changes color because…', opts: ['the pH shifts at the endpoint', 'the indicator is oxidised', 'bound and free differ in colour', 'EDTA is itself an intensely coloured species'], a: 2, why: 'At the endpoint EDTA strips the metal from the (wine-red) MgIn complex, freeing the (blue) indicator.' },
  { id: 'ana-016', tier: 3, topic: 'analytical', skill: ['lab/titration-technique', 'equilibrium/ksp'], q: 'To determine water hardness, Ca²⁺ + Mg²⁺ are titrated with EDTA. Titrating at pH 12 (Mg(OH)₂ precipitated) gives…', opts: ['total hardness', 'neither', 'Mg²⁺ only', 'Ca²⁺ only'], a: 3, why: 'Masking Mg²⁺ as its hydroxide leaves only Ca²⁺ to react — the difference from the pH-10 total gives Mg²⁺.', misconception: 'Raising the pH to 12 takes Mg²⁺ OUT of the titration by dropping it as Mg(OH)₂, so what remains in solution for the EDTA to find is Ca²⁺. Reading the masking step as "this must be the magnesium determination" inverts the logic; magnesium is never titrated directly here, it comes out as the difference from the pH-10 total hardness.' },
  { id: 'ana-017', topic: 'analytical', skill: 'lab/error-analysis', q: 'The method of standard additions corrects for…', opts: ['matrix effects', 'random error in the readings', 'dilution errors alone', 'drift with temperature'], a: 0, why: 'Spiking the real sample with known analyte and extrapolating removes matrix-dependent slope errors that an external calibration misses.', misconception: 'Standard additions and an external calibration curve solve different problems. An external curve assumes the standards and the sample respond identically, which fails when the sample matrix changes the instrument\'s <em>sensitivity</em> — the slope, not the intercept. Spiking the real sample and extrapolating measures the slope in the matrix itself. Running more replicates does nothing for this class of error.' },
  { id: 'ana-018', topic: 'analytical', skill: 'lab/titration-technique', q: 'In iodometry, thiosulfate titrates I₂; starch is added…', opts: ['at the very start', 'near the endpoint', 'never — it interferes', 'only to buffer the solution'], a: 1, why: 'Added early, starch binds I₂ too tightly (irreversible blue). Near the end, the sharp blue→colourless flip marks the endpoint.' },
  { id: 'ana-019', topic: 'analytical', q: 'A weak acid HA (Ka = 1.8×10⁻⁵) is titrated with NaOH. The solution best resists pH change at…', opts: ['the very start', 'the equivalence point itself', 'half-equivalence', 'well past equivalence'], a: 2, why: 'Maximum buffer capacity occurs where [HA] = [A⁻], i.e. pH = pKa = 4.74 — the flattest part of the curve.' },
  { id: 'ana-020', topic: 'analytical', skill: 'lab/error-analysis', q: 'Coprecipitation in gravimetry leads to results that are typically…', opts: ['too low, from lost solid', 'unaffected either way', 'too high, from extra mass', 'negative after correction'], a: 2, why: 'Foreign ions adsorb/occlude onto the precipitate, adding mass → analyte overestimated. Digestion and reprecipitation reduce it.', misconception: 'Coprecipitation makes gravimetric results too HIGH, not too low, because the foreign ions adsorbed or occluded on the precipitate are weighed along with the analyte. The instinct that "some analyte was lost" points the error the wrong way. Digestion, reprecipitation and careful washing are the fixes; simply drying harder is not.' },
  { id: 'ana-021', topic: 'analytical', skill: 'lab/titration-technique', q: 'For the reaction 2S₂O₃²⁻ + I₂ → S₄O₆²⁻ + 2I⁻, 25.00 mL of 0.1000 M thiosulfate reacts with how many mmol I₂?', opts: ['2.500', '1.250', '5.000', '0.625'], a: 1, why: '2:1 ratio → mmol I₂ = (0.1000 × 25.00)/2 = 1.250 mmol.' },
  { id: 'ana-022', topic: 'analytical', q: 'The activity of pure water and pure solids is taken as…', opts: ['1, by definition', '0', 'their molarity', 'γ times concentration'], a: 0, why: 'Standard-state activity of a pure condensed phase is 1 — which is why they drop out of K and Ksp expressions.' },
  { id: 'ana-023', topic: 'analytical', skill: 'lab/titration-technique', q: 'Karl Fischer titration specifically determines…', opts: ['total acidity', 'dissolved oxygen', 'chloride ion', 'water, by the Karl Fischer reaction'], a: 3, why: 'The I₂/SO₂/pyridine reagent consumes water stoichiometrically — the standard method for trace moisture.' },
  { id: 'ana-024', topic: 'analytical', skill: 'lab/titration-technique', q: 'Fajans method uses an adsorption indicator; the endpoint color change occurs because…', opts: ['the pH changes sharply', 'the analyte is oxidised at the end', 'the surface charge flips', 'a coloured complex forms in solution'], a: 2, why: 'Just past equivalence, excess Ag⁺ makes the AgCl surface positive, adsorbing dichlorofluorescein (pink) — a surface phenomenon.' },
  { id: 'ana-025', topic: 'analytical', skill: 'lab/titration-technique', q: 'A titration curve\'s equivalence-point break is sharpest when…', opts: ['both analyte and titrant are weak ones', 'K is large, driving it to completion', 'the solution is as dilute as possible', 'the temperature is kept low throughout'], a: 1, why: 'A big K (strong acid/base, large K_f, large cell E°) gives a near-vertical jump; weak reactions and dilution flatten it.' },
];

export const SPECTROSCOPY_QUIZ: QuizQ[] = [
  // ---- warm-ups ----
  { id: 'spe-001', topic: 'spectroscopy', skill: 'lab/spectroscopy-ir', q: 'Infrared spectroscopy probes molecular…', opts: ['electronic transitions', 'ionization', 'nuclear spin flips', 'bond vibrations'], a: 3, why: 'IR photons excite stretching/bending vibrations; the frequency depends on bond strength and atom masses.' },
  { id: 'spe-002', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: '¹H NMR tells you about…', opts: ['the carbon skeleton alone', 'the molecular mass', 'H environments', 'the colour of the sample'], a: 2, why: 'Chemical shift = environment, integration = how many H, splitting = number of neighbouring H.' },
  { id: 'spe-003', topic: 'spectroscopy', skill: 'lab/spectroscopy-ms', q: 'In mass spectrometry, the M⁺ peak corresponds to…', opts: ['the base peak, always', 'the molecular ion', 'the largest fragment ion', 'the solvent peak'], a: 1, why: 'The molecular ion gives the molar mass; the base peak (100%) is the most abundant fragment, not necessarily M⁺.', misconception: 'The molecular ion and the base peak are different peaks, and they coincide only by luck. M⁺ is the intact molecule minus an electron and gives the molar mass; the base peak is whichever fragment happens to be most abundant, scaled to 100%. In many spectra M⁺ is small or missing altogether — a tertiary alcohol may show no molecular ion at all — so reading the tallest peak as the molar mass is a straightforward way to identify the wrong compound.' },
  { id: 'spe-004', topic: 'spectroscopy', skill: 'lab/spectroscopy-ir', q: 'A strong IR absorption near 1700 cm⁻¹ indicates a…', opts: ['C=O, a carbonyl stretch', 'O–H bond', 'C–H bond', 'C–C bond'], a: 0, why: 'The carbonyl stretch is intense and diagnostic around 1700–1750 cm⁻¹.' },
  { id: 'spe-005', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'In ¹H NMR, a triplet arises from a proton with…', opts: ['no neighbours at all', 'exactly one neighbour', 'three equivalent neighbours', 'two equivalent neighbours'], a: 3, why: 'n+1 rule: 2 neighbours → 3 peaks. The classic CH₃CH₂– ethyl pattern is triplet + quartet.' },
  // ---- CCO-level ----
  { id: 'spe-006', tier: 3, topic: 'spectroscopy', skill: 'lab/structure-elucidation', q: 'A compound C₄H₈O shows a strong IR band at 1715 cm⁻¹ and a ¹H NMR singlet near 2.1 ppm. It is likely…', opts: ['butanal', 'diethyl ether', 'butan-2-one', 'but-3-en-1-ol'], a: 2, why: 'Carbonyl (1715) + only a methyl-ketone singlet (no aldehyde H near 9.7) → butanone, (CH₃)COCH₂CH₃; the two CH₃ environments differ but 2.1 ppm is the acetyl methyl.', misconception: 'A band at 1715 cm⁻¹ establishes C=O but says nothing about aldehyde versus ketone — that call belongs to the NMR. An aldehyde would announce itself with a CHO proton near 9.7 ppm (and the twin C–H stretches near 2720 and 2820 cm⁻¹); their absence, alongside a 3H singlet at 2.1 ppm for an acetyl methyl, is what eliminates butanal.' },
  { id: 'spe-007', topic: 'spectroscopy', skill: 'lab/spectroscopy-ir', q: 'The IR O–H stretch of a carboxylic acid appears as…', opts: ['a sharp band at 3600 cm⁻¹', 'a very broad band', 'no O–H band at all', 'a single band at 1700 cm⁻¹'], a: 1, why: 'Strong hydrogen bonding in the acid dimer smears the O–H stretch into a broad hump overlapping the C–H region.' },
  { id: 'spe-008', topic: 'spectroscopy', skill: 'lab/structure-elucidation', q: 'Degrees of unsaturation for C₆H₅NO₂ (nitrobenzene) — using DoU = (2C+2+N−H)/2 — equals…', opts: ['5', '4', '3', '6'], a: 0, why: 'DoU = (2·6 + 2 + 1 − 5)/2 = 10/2 = <b>5</b> (oxygen is ignored). Structurally: benzene ring = 4, plus one N=O in the nitro group = 5.' },
  { id: 'spe-009', topic: 'spectroscopy', skill: 'lab/spectroscopy-ms', q: 'The "nitrogen rule" states that an odd molecular mass (M⁺) implies…', opts: ['an even number of N atoms', 'a halogen', 'no nitrogen', 'an odd number of N atoms'], a: 3, why: 'An odd nominal M⁺ means an odd count of nitrogen atoms — a fast MS diagnostic for amines/amides.' },
  { id: 'spe-010', topic: 'spectroscopy', skill: 'lab/spectroscopy-ms', q: 'A molecular ion cluster with M and M+2 peaks in ~1:1 ratio indicates…', opts: ['chlorine', 'bromine', 'nitrogen', 'sulfur'], a: 1, why: '⁷⁹Br and ⁸¹Br are ~50:50, giving the tell-tale 1:1 M/M+2. Chlorine (³⁵/³⁷ ≈ 3:1) gives 3:1.' },
  { id: 'spe-011', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'In ¹³C NMR, the number of signals equals the number of…', opts: ['carbon atoms present', 'hydrogen atoms present', 'inequivalent carbons', 'bonds to carbon'], a: 2, why: 'Symmetry-equivalent carbons overlap; p-xylene has eight carbons but only three signals — one methyl, one CH, one substituted ring carbon.', misconception: 'A ¹³C spectrum counts <em>inequivalent</em> carbons, not carbons. Symmetry collapses signals: p-xylene has eight carbons but shows three lines. Counting peaks and expecting the molecular formula to match is the error, and the mismatch is a gift — it tells you the molecule has symmetry, which is often the fastest route into a structure problem.' },
  { id: 'spe-012', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'An ethyl group (–CH₂CH₃) in ¹H NMR shows…', opts: ['two separate singlets', 'one broad unresolved peak', 'a doublet and a septet', 'a triplet and a quartet'], a: 3, why: 'CH₃ sees 2 H → triplet; CH₂ sees 3 H → quartet, with 3:2 integration.' },
  { id: 'spe-013', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'An isopropyl group (CH₃)₂CH– gives, for the methine CH, a…', opts: ['septet', 'quartet', 'triplet', 'singlet'], a: 0, why: 'The CH sees six equivalent methyl H → n+1 = 7 (septet); the two CH₃ appear as a doublet.' },
  { id: 'spe-014', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'Chemical shift (ppm) is independent of spectrometer field strength because it is defined as…', opts: ['the absolute frequency in Hz', 'Δν/frequency, ×10⁶', 'the coupling constant in Hz', 'the integrated peak area'], a: 1, why: 'Referencing to TMS and dividing by the instrument frequency cancels the field, so shifts are comparable across spectrometers.', misconception: 'Chemical shift in ppm is field-independent; the coupling constant J in Hz is not affected by field either, but the <em>separation in Hz</em> between two signals is. That is why a spectrum recorded at 500 MHz resolves multiplets that overlap at 60 MHz while every δ value stays exactly the same. Quoting a shift in Hz without the spectrometer frequency makes it meaningless.' },
  { id: 'spe-015', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'Coupling constant J is measured in Hz and, unlike chemical shift, is…', opts: ['field-dependent', 'always 7 Hz', 'field-independent', 'zero for aromatics'], a: 2, why: 'J reflects a through-bond interaction between nuclei — a real energy in Hz that does not scale with the applied field.' },
  { id: 'spe-016', topic: 'spectroscopy', skill: 'lab/spectroscopy-ir', q: 'A carbonyl stretch order C=O: which absorbs at the HIGHEST wavenumber?', opts: ['amide, ~1650', 'ketone, ~1715', 'ester, ~1740', 'acid chloride'], a: 3, why: 'Acyl chlorides ~1800 cm⁻¹ (strong EWG raises bond order); amides lowest ~1650 (N lone-pair donation). Frequency tracks C=O bond strength.', misconception: 'The carbonyl stretch is not a single "1700 cm⁻¹" fact — its position is a readout of C=O bond strength and is worth reading finely. Electron-withdrawing groups raise it (acid chloride ≈ 1800), nitrogen donation lowers it (amide ≈ 1650), conjugation lowers it by 20–40 cm⁻¹, and ring strain raises it (cyclopropanone ≈ 1815). Treating every peak near 1700 as simply "a carbonyl" throws away the information that distinguishes the derivative.' },
  { id: 'spe-017', topic: 'spectroscopy', skill: 'lab/spectroscopy-ms', q: 'Loss of 15 from M⁺ in a mass spectrum usually signals loss of…', opts: ['CH₃', 'OH', 'H₂O', 'CO'], a: 0, why: 'A methyl radical (mass 15). Loss of 18 = water, 28 = CO or C₂H₄, 29 = CHO or C₂H₅.' },
  { id: 'spe-018', topic: 'spectroscopy', q: 'Conjugation in a molecule shifts UV-Vis absorption to…', opts: ['shorter wavelength (blue shift)', 'longer wavelength (red shift)', 'no change', 'the IR', ], a: 1, why: 'Extended conjugation lowers the HOMO–LUMO gap → longer λ (bathochromic shift). β-carotene\'s 11 double bonds make it orange.', misconception: 'Conjugation shifts UV–Vis absorption to LONGER wavelength, not shorter. Extending the π system lowers the HOMO–LUMO gap, so less energy — and therefore a longer wavelength — is required. Reasoning "more bonds, more energy, shorter λ" inverts the relationship; the visible colour of β-carotene and of dyes generally exists because a long conjugated chain has pulled that gap down into the visible.' },
  { id: 'spe-019', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'A ¹H NMR peak that disappears on shaking with D₂O is a…', opts: ['a methyl CH₃', 'an aromatic CH', 'labile OH or NH', 'a methylene CH₂'], a: 2, why: 'Exchangeable O–H/N–H protons swap for D and vanish — a classic assignment trick.' },
  { id: 'spe-020', topic: 'spectroscopy', q: 'The Diels–Alder reaction is a [4+2] cycloaddition that is…', opts: ['radical in mechanism', 'photochemically allowed only', 'thermally allowed', 'ionic, via a zwitterion'], a: 2, why: 'Woodward–Hoffmann: 4n+2 π electrons → thermal supra-supra allowed. Forms a cyclohexene with defined stereochemistry.' },
  { id: 'spe-021', topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'Two isomeric alkenes both show a ¹H NMR pair of vinyl doublets. In one the coupling constant is J = 16 Hz, in the other J = 10 Hz. The J = 16 Hz isomer is…', opts: ['cis (Z)', 'trans (E)', 'the one measured at higher field', 'impossible to assign from J'], a: 1, why: 'Vicinal ³J across a double bond depends on the dihedral angle between the two C–H bonds: trans protons sit at 180° and couple strongly (12–18 Hz), cis protons at 0° and couple less (6–12 Hz). <span class="trap">This works because J is field-independent — 16 Hz is 16 Hz on any spectrometer, whereas the chemical-shift separation in Hz would change with the magnet. It is the reason J, not δ, is the quantity used for geometry.</span> The same dihedral dependence, generalised by the Karplus equation, is what fixes ring conformations and peptide backbone angles.' },
  { id: 'spe-022', topic: 'spectroscopy', q: 'The Wittig reaction converts a ketone/aldehyde plus a phosphorus ylide into…', opts: ['an alkene', 'an alcohol', 'a carboxylic acid', 'an ether'], a: 0, why: 'R₂C=O + Ph₃P=CR′₂ → R₂C=CR′₂ + Ph₃P=O. Reliable C=C formation at a defined position.' },
  { id: 'spe-023', tier: 3, topic: 'spectroscopy', skill: 'lab/spectroscopy-nmr', q: 'Peak areas in a routine ¹H NMR spectrum give reliable proton counts, but peak areas in a routine ¹³C spectrum must NOT be used to count carbons. Why?', opts: ['¹³C peaks are far too weak to integrate', 'carbon has only one isotope', '¹³C nuclei possess no nuclear spin', 'uneven NOE and slow relaxation'], a: 3, why: 'Two effects, both unequal across the molecule. Broadband proton decoupling gives a <b>nuclear Overhauser enhancement</b> that scales with how many protons are attached, so a CH₃ carbon is boosted far more than a quaternary one. And quaternary carbons have long <b>T₁</b> relaxation times, so at normal pulse rates they have not returned to equilibrium before the next pulse and are under-counted again. <span class="trap">The result is that a quaternary carbon can appear as a small peak next to a large CH₃ peak in a 1:1 compound. Quantitative ¹³C is possible — inverse-gated decoupling plus a long relaxation delay — but it is slow, and nobody does it by accident.</span>', misconception: 'Low ¹³C abundance (1.1%) makes the spectrum weak, but weakness by itself would not distort the RATIOS — every carbon in the molecule is equally 1.1% abundant, so a noisy spectrum is still a proportional one. What breaks proportionality is that the two distortions act UNEQUALLY between carbons: NOE boosts carbons according to how many protons they carry, and slow T₁ relaxation under-counts the quaternary ones on top of that.' , why2: 'Turn it into a prediction and check it against a real spectrum. Run routine ¹³C on 4-methylacetophenone: the two methyl carbons give tall peaks, while the carbonyl carbon and the two substituted ring carbons show up as stubs barely above the noise — yet each of those is exactly one carbon, the same as each methyl. The two causes both punish the same atoms, so the errors compound rather than cancel: signal is <em>borrowed from attached protons</em> (NOE, so more H attached = bigger boost), and carbons with no attached protons <em>relax slowly</em> (long T₁), so they have not recovered before the next pulse arrives. There is a usable corollary in the failure mode — a suspiciously small ¹³C peak is itself evidence that the carbon is quaternary.' },
  { id: 'spe-024', tier: 3, topic: 'spectroscopy', skill: 'lab/spectroscopy-ms', q: 'Several formulas share the nominal mass 60. High-resolution MS reads the molecular ion at m/z 60.0575. Given C = 12.0000, H = 1.00783, O = 15.9949, the compound is…', opts: ['C₂H₄O₂ (acetic acid)', 'CH₄N₂O (urea)', 'C₃H₈O (propan-1-ol)', 'either — the masses are identical'], a: 2, why: 'C₃H₈O = 3(12.0000) + 8(1.00783) + 15.9949 = 36.0000 + 8.0626 + 15.9949 = <b>60.0575</b> ✓. C₂H₄O₂ = 24.0000 + 4.0313 + 31.9898 = 60.0211 — the same nominal mass but 36 millimass units lighter. <span class="trap">Nominal masses collide constantly; exact masses almost never do, because hydrogen is the only common element whose exact mass lies appreciably ABOVE its integer value. More H in the formula means a higher exact mass, so the hydrogen-rich alcohol outweighs the oxygen-rich acid.</span> Four decimal places on the molecular ion is usually enough to fix the molecular formula outright, before any other spectrum is consulted.', misconception: 'Nominal mass and exact mass are different quantities, so "the masses are identical" mistakes a coincidence at 60 for an identity at 60.0575. The decimals come almost entirely from hydrogen, each atom of which adds 0.00783 above its integer value, so among isobars the hydrogen-rich formula is always the heavier one.' },
  { id: 'spe-025', topic: 'spectroscopy', q: 'An electrocyclic ring closure of a triene under thermal conditions proceeds…', opts: ['conrotatory (6 π e⁻)', 'disrotatory (6 π e⁻)', 'radically', 'never'], a: 1, why: 'Thermal 6-π-electron electrocyclizations are disrotatory (Woodward–Hoffmann); photochemical ones flip to conrotatory. Count the electrons, then apply the rule.' },
];
