/**
 * The glossary: one plain sentence per term, for a student meeting it for the
 * first time (plan3 §2.4, written to docs/STYLE.md).
 *
 * PURE DATA, NO IMPORTS — scripts/prerender.mjs loads this file in Node, and
 * every value import is another thing to stub there. Keep it that way.
 *
 * Keys are the DISPLAY FORM, lower case. `annotateTerms` matches them
 * case-insensitively on a word boundary and allows one trailing "s", so
 * "moles" and "Molar mass" both resolve without their own entry. A variant a
 * trailing "s" cannot reach gets its own key: irregular plurals (nuclei),
 * hyphenated plurals (half-lives), and the -ise/-ize spellings, both of which
 * the corpus already uses.
 *
 * Deliberately NOT here: words that are ordinary English before they are
 * chemistry (energy, heat, temperature, group, period, system, metal, atom).
 * Underlining those on every page is noise, not help.
 *
 * Definitions checked against a standard general-chemistry text. Every one is
 * a single sentence of 25 words or fewer, per docs/STYLE.md.
 */
export const GLOSSARY: Record<string, string> = {
  // ---- amount, mass and solutions (stoich) ----
  'mole': 'A fixed count of particles, 6.022 × 10²³ of them, the way a dozen is always 12.',
  "avogadro's number": 'The number of particles in one mole, 6.022 × 10²³.',
  'molar mass': 'The mass in grams of one mole of a substance, found by adding the atomic masses in its formula.',
  'atomic mass': 'The average mass of one atom of an element, in atomic mass units, as printed on the periodic table.',
  'molarity': 'The number of moles of dissolved substance in one litre of solution, written mol/L or M.',
  'molality': 'The number of moles of dissolved substance per kilogram of solvent, which does not change when the temperature does.',
  'concentration': 'How much of a substance is packed into a given volume of a mixture.',
  'stoichiometry': 'Working out how much of each substance a reaction uses and makes, using the balanced equation.',
  'balanced equation': 'A reaction written so that each element has the same number of atoms on both sides.',
  'coefficient': 'The number written in front of a formula in a balanced equation, giving its share in moles.',
  'limiting reagent': 'The reactant that runs out first, so it sets how much product the reaction can make.',
  'excess reagent': 'A reactant that is still left over once the limiting reagent has run out.',
  'theoretical yield': 'The largest mass of product a reaction could give if the limiting reagent were used up completely.',
  'actual yield': 'The mass of product actually collected from a reaction.',
  'percent yield': 'The actual yield divided by the theoretical yield, times 100.',
  'empirical formula': 'The formula giving the simplest whole-number ratio of atoms, so hydrogen peroxide H₂O₂ has empirical formula HO.',
  'molecular formula': 'The formula giving the actual number of each atom in one molecule, such as H₂O₂.',
  'percent composition': 'The percentage of a compound’s mass contributed by each element.',
  'formula unit': 'The smallest whole-number group of ions in an ionic compound, such as NaCl.',
  'hydrate': 'A solid that holds a fixed number of water molecules inside its crystal, such as CuSO₄·5H₂O.',
  'solute': 'The substance that is dissolved in a solution.',
  'solvent': 'The liquid that does the dissolving in a solution, most often water.',
  'aqueous': 'Dissolved in water, marked (aq) in an equation.',
  'dilution': 'Adding more solvent to a solution, which lowers the concentration but keeps the number of moles the same.',
  'precipitate': 'A solid that appears when two solutions are mixed and their ions form an insoluble compound.',
  'spectator ion': 'An ion that is present but unchanged through a reaction, so it is left out of the net ionic equation.',
  'net ionic equation': 'A reaction written with only the ions and molecules that actually change.',
  'solubility': 'The largest amount of a substance that will dissolve in a given amount of solvent.',

  // ---- atoms and electrons (quantum) ----
  'proton': 'A positively charged particle in the nucleus; the number of them decides which element an atom is.',
  'neutron': 'An uncharged particle in the nucleus, with almost the same mass as a proton.',
  'electron': 'A very light, negatively charged particle that occupies the space around the nucleus.',
  'nucleus': 'The tiny dense centre of an atom, holding the protons and neutrons.',
  'nuclei': 'The tiny dense centres of atoms, each holding protons and neutrons.',
  'atomic number': 'The number of protons in an atom, which fixes the element.',
  'mass number': 'The total number of protons and neutrons in one atom.',
  'isotope': 'One of two atoms of the same element that hold different numbers of neutrons.',
  'ion': 'An atom or group of atoms that has gained or lost electrons and so carries a charge.',
  'cation': 'A positively charged ion, made by losing electrons.',
  'anion': 'A negatively charged ion, made by gaining electrons.',
  'orbital': 'A region around a nucleus where an electron is likely to be found; each holds at most two electrons.',
  'node': 'A place in an orbital where the chance of finding the electron is exactly zero.',
  'shell': 'A set of orbitals at roughly the same distance from the nucleus, labelled by the number n.',
  'subshell': 'The orbitals of one shape within a shell, labelled s, p, d or f.',
  'valence electron': 'An electron in the outermost shell, which is the one that takes part in bonding.',
  'electron configuration': 'A list of which orbitals an atom’s electrons occupy, such as 1s²2s²2p⁶ for neon.',
  'ground state': 'The arrangement in which an atom’s electrons sit in the lowest orbitals available.',
  'excited state': 'A higher-energy arrangement, reached when an electron absorbs energy and moves up.',
  'photon': 'A single packet of light, carrying energy equal to Planck’s constant times the light’s frequency.',
  'wavelength': 'The distance between one wave crest and the next.',
  'frequency': 'The number of wave cycles passing a point each second, measured in hertz.',
  'emission spectrum': 'The set of specific colours an element gives out when its excited electrons drop back down.',
  'quantum number': 'One of four numbers that label an electron: its shell, orbital shape, orientation and spin.',
  'aufbau principle': 'Electrons fill the lowest-energy orbital available before moving to a higher one.',
  "hund's rule": 'Electrons spread out singly across orbitals of equal energy before any orbital takes a second electron.',
  'pauli exclusion principle': 'No two electrons in an atom can have all four quantum numbers the same.',
  'ionisation energy': 'The energy needed to pull one electron away from a gaseous atom.',
  'ionization energy': 'The energy needed to pull one electron away from a gaseous atom.',
  'electron affinity': 'The energy released when a gaseous atom gains one electron.',
  'effective nuclear charge': 'The pull an outer electron actually feels from the nucleus once inner electrons have screened part of it.',
  'shielding': 'The way inner electrons block outer ones from feeling the full pull of the nucleus.',

  // ---- the periodic table (periodicity) ----
  'periodic table': 'The chart of the elements, ordered by atomic number and arranged so that similar elements line up in columns.',
  'atomic radius': 'A measure of how big an atom is, taken as half the distance between two bonded identical atoms.',
  'ionic radius': 'A measure of how big an ion is; cations are smaller than their atoms, anions larger.',
  'electronegativity': 'How strongly an atom pulls on the shared electrons of a bond, on a scale where fluorine is highest.',
  'metalloid': 'An element such as silicon whose properties fall between those of a metal and a non-metal.',
  'alkali metal': 'An element of the first column, such as sodium, which is soft and reacts violently with water.',
  'halogen': 'An element of the second-to-last column, such as chlorine, which needs one more electron to fill its shell.',
  'noble gas': 'An element of the last column, such as neon, whose full outer shell makes it almost unreactive.',
  'transition metal': 'A metal from the middle block of the table, which uses d orbitals and often forms coloured compounds.',
  'lanthanide contraction': 'The steady shrinking across the lanthanides that leaves hafnium almost the same size as zirconium.',

  // ---- bonding and shape ----
  'ionic bond': 'The attraction holding a positive and a negative ion together after electrons have been transferred.',
  'covalent bond': 'A bond made by two atoms sharing a pair of electrons.',
  'metallic bond': 'The attraction between metal ions and the pool of electrons that moves freely between them.',
  'lewis structure': 'A drawing of a molecule showing every valence electron as a bonding pair or a lone pair.',
  'lone pair': 'A pair of valence electrons that sits on one atom instead of being shared in a bond.',
  'bonding pair': 'A pair of electrons shared between two atoms, making a covalent bond.',
  'sigma bond': 'A bond whose shared electrons lie straight along the line joining the two nuclei.',
  'pi bond': 'A bond whose shared electrons lie in two lobes above and below the line joining the nuclei.',
  'double bond': 'Two shared pairs between the same two atoms: one sigma bond and one pi bond.',
  'triple bond': 'Three shared pairs between the same two atoms: one sigma bond and two pi bonds.',
  'octet rule': 'Main-group atoms tend to end up with eight valence electrons, the count a noble gas has.',
  'formal charge': 'A bookkeeping charge on an atom in a Lewis structure, found from its valence electrons minus lone-pair and half its bonding electrons.',
  'resonance': 'When one Lewis structure is not enough, so the real molecule is an average of several.',
  'vsepr': 'The rule that electron groups around an atom spread as far apart as they can, which fixes the shape.',
  'bond angle': 'The angle between two bonds meeting at the same atom.',
  'hybridisation': 'Mixing an atom’s s and p orbitals into equal new ones that point where the bonds go.',
  'hybridization': 'Mixing an atom’s s and p orbitals into equal new ones that point where the bonds go.',
  'polar bond': 'A bond in which one atom pulls the shared electrons harder, giving each end a small charge.',
  'dipole moment': 'A measure of a molecule’s overall separation of charge; it is zero when the bond dipoles cancel.',
  'intermolecular force': 'An attraction between whole molecules, much weaker than the bonds inside them.',
  'hydrogen bond': 'A strong attraction between a hydrogen bonded to N, O or F and a lone pair on another such atom.',
  'london dispersion force': 'A weak attraction that arises when electron clouds flicker out of balance for an instant.',
  'molecular orbital': 'An orbital that spreads over a whole molecule, formed when atomic orbitals combine.',
  'bond order': 'Half the difference between bonding and antibonding electrons; higher means a shorter, stronger bond.',
  'paramagnetic': 'Having one or more unpaired electrons, so the substance is pulled into a magnetic field.',
  'diamagnetic': 'Having all electrons paired, so the substance is very slightly pushed out of a magnetic field.',
  'lattice energy': 'The energy released when gaseous ions come together to build one mole of an ionic solid.',
  'lattice': 'The repeating three-dimensional grid of ions or atoms that makes up a crystal.',
  'main-group': 'The elements of the tall columns at the left and right of the periodic table, which fill only s and p orbitals.',
  'trigonal planar': 'The flat triangular shape of an atom with three electron groups and no lone pairs, with 120° bond angles.',
  'trigonal pyramidal': 'The squashed pyramid shape of an atom with three bonds and one lone pair, as in ammonia, near 107°.',

  // ---- energy and spontaneity (thermo) ----
  'enthalpy': 'The heat content of a substance; the enthalpy change ΔH is the heat given out or taken in at constant pressure.',
  'entropy': 'A measure of how spread out a system’s energy and particles are; gases have more of it than solids.',
  'free energy': 'Gibbs free energy G combines enthalpy and entropy, and a reaction runs forward when its change ΔG is negative.',
  'gibbs free energy': 'The quantity G = H − TS, whose change decides whether a reaction runs forward on its own.',
  'exothermic': 'Giving out heat, so the surroundings warm up and ΔH is negative.',
  'endothermic': 'Taking in heat, so the surroundings cool down and ΔH is positive.',
  'spontaneous': 'Able to happen on its own once started, without a continuing push; it says nothing about speed.',
  'calorimeter': 'An insulated container used to measure the heat a reaction gives out or takes in.',
  'specific heat capacity': 'The heat needed to raise one gram of a substance by one degree; water’s is 4.18 J/g·K.',
  "hess's law": 'The enthalpy change of a reaction is the same whatever route it takes, so known steps can be added.',
  'standard state': 'The agreed reference condition for a substance: its stable form at 1 bar, and 1 mol/L for solutions.',
  'bond enthalpy': 'The average energy needed to break one mole of a particular bond in the gas phase.',
  'internal energy': 'The total energy stored inside a system, changed by the heat added and the work done on it.',

  // ---- equilibrium, acids and rates ----
  'equilibrium': 'The state a reversible reaction settles into, where forward and reverse reactions run at the same rate.',
  'dynamic equilibrium': 'Equilibrium seen up close: molecules keep converting both ways, but the amounts stay constant.',
  'equilibrium constant': 'The number K giving the ratio of product to reactant amounts once a reaction has settled, at one temperature.',
  'reaction quotient': 'The number Q, worked out like K but from the amounts present right now rather than at equilibrium.',
  "le chatelier's principle": 'Disturb a mixture at equilibrium and it shifts in the direction that partly undoes the disturbance.',
  "le châtelier's principle": 'Disturb a mixture at equilibrium and it shifts in the direction that partly undoes the disturbance.',
  'reversible reaction': 'A reaction that can run in both directions, written with a double arrow ⇌.',
  'reaction rate': 'How fast a reaction uses up reactant or makes product, measured as a change in concentration per second.',
  'rate constant': 'The number k in a rate law, fixed for one reaction at one temperature and rising sharply as it warms.',
  'rate law': 'The equation linking a reaction’s rate to the concentrations of its reactants, found by experiment.',
  'catalyst': 'A substance that speeds a reaction up by offering an easier route, and is not used up itself.',
  'activation energy': 'The minimum energy a collision needs before the reactants can turn into products.',
  'half-life': 'The time a sample takes to fall to half of its starting amount.',
  'half-lives': 'The times samples take to fall to half of their starting amounts.',
  'acid': 'A substance that gives away hydrogen ions, H⁺, in water.',
  'base': 'A substance that accepts hydrogen ions, H⁺, often by supplying hydroxide ions instead.',
  'ph': 'A scale of acidity: pH = −log[H⁺], so 7 is neutral, below 7 acidic and above 7 basic.',
  'poh': 'A scale of how basic a solution is: pOH = −log[OH⁻], and at 25 °C pH + pOH = 14.',
  'salt': 'The ionic compound left when an acid neutralises a base, such as the NaCl from HCl and NaOH.',
  'galvanic cell': 'Two metals in solution joined by a wire, so that electrons flow from one to the other; a battery.',
  'strong acid': 'An acid that gives up essentially all of its hydrogen ions in water, such as HCl.',
  'weak acid': 'An acid that gives up only a small fraction of its hydrogen ions in water, such as acetic acid.',
  'conjugate base': 'What is left of an acid after it has given away one hydrogen ion.',
  'conjugate acid': 'What a base becomes after it has accepted one hydrogen ion.',
  'buffer': 'A mixture of a weak acid and its conjugate base that keeps pH nearly steady when acid or base is added.',
  'titration': 'Adding a solution of known concentration from a burette until a reaction is exactly complete, to measure an unknown.',
  'indicator': 'A dye that changes colour over a narrow pH range, used to show when a titration is complete.',
  'equivalence point': 'The moment in a titration when exactly enough has been added to react with all of the unknown.',
  'end point': 'The moment the indicator changes colour, which is meant to fall as close as possible to the equivalence point.',
  'neutralisation': 'The reaction of an acid with a base, which for a strong pair gives water and a salt.',
  'neutralization': 'The reaction of an acid with a base, which for a strong pair gives water and a salt.',
  'amphoteric': 'Able to act as either an acid or a base, as water and aluminium hydroxide both do.',
  'solubility product': 'The equilibrium constant Ksp for a slightly soluble solid dissolving into its ions.',
  'common ion effect': 'A salt dissolves less in a solution that already contains one of its own ions.',
  'oxidation': 'Loss of electrons, which pushes an atom’s oxidation state up.',
  'reduction': 'Gain of electrons, which pulls an atom’s oxidation state down.',
  'oxidation state': 'A bookkeeping charge assigned to an atom as if every bond were fully ionic.',
  'redox reaction': 'A reaction in which electrons move from one substance to another, so one is oxidised and one reduced.',
  'oxidising agent': 'The substance that takes the electrons, and is itself reduced.',
  'reducing agent': 'The substance that gives the electrons away, and is itself oxidised.',
  'half-reaction': 'One side of a redox reaction, written on its own with the electrons shown.',

  // ---- the laboratory (labdata, labtech) ----
  'absorbance': 'A measure of how much light a solution soaks up, which rises as the solution gets more concentrated.',
  'calibration curve': 'A graph of signal against known concentration, used to read off the concentration of an unknown.',
  "beer's law": 'Absorbance is proportional to concentration and to the path length the light travels through the sample.',
  'significant figures': 'The digits in a measurement that were actually measured, which set how precisely an answer may be quoted.',
  'systematic error': 'An error that pushes every reading the same way, such as a balance that always reads high.',
  'random error': 'Scatter that pushes readings either way, which averaging over repeats reduces.',
  'accuracy': 'How close a measurement is to the true value.',
  'precision': 'How close repeated measurements are to each other, whether or not they are right.',
  'uncertainty': 'The range a measurement could reasonably lie in, quoted alongside the value.',
  'recrystallisation': 'Purifying a solid by dissolving it hot and letting clean crystals grow as the solution cools.',
  'recrystallization': 'Purifying a solid by dissolving it hot and letting clean crystals grow as the solution cools.',
  'distillation': 'Separating liquids by boiling the mixture and condensing the vapour, which is richer in the lower-boiling one.',
  'extraction': 'Separating a substance by shaking the mixture with a second liquid it dissolves in better.',
  'filtration': 'Separating a solid from a liquid by pouring the mixture through paper or a porous disc.',
  'chromatography': 'Separating a mixture by letting it travel through a material its components stick to by different amounts.',
  'reflux': 'Heating a reaction under a vertical condenser, so the vapour drips back and nothing boils away.',
  'melting point': 'The temperature at which a solid turns to liquid; a sharp one is evidence that a sample is pure.',
  'burette': 'A long graduated tube with a tap, used to add a measured volume of solution drop by drop.',
  'pipette': 'A glass tube that delivers one fixed, accurately known volume of liquid.',
  'volumetric flask': 'A flask with a single mark on its neck, used to make a solution up to an exact volume.',
  'meniscus': 'The curved liquid surface in a narrow tube, read at its lowest point for water.',
  'cuvette': 'The small clear cell a sample sits in while its absorbance is measured; its width is the path length.',
  'standard solution': 'A solution whose concentration is known accurately, used as the reference in a titration.',
  'serial dilution': 'Making a set of steadily weaker solutions by diluting each one from the last by a fixed factor.',
  'supernatant': 'The clear liquid left above a solid after it has settled or been spun down.',
  'aliquot': 'A measured portion taken from a larger sample.',
  'anhydrous': 'Containing no water.',
};
