// GENERATED by scripts/gen-page-questions.mjs — do not edit by hand.
//
// Which question ids each PAGE of a split module owns (plan3 Phase 6): the
// course page holds the first 20 of the module's bank, the contest page the rest.
// Ids, not questions — so `moduleProgress()` can count a page's solved
// fraction without the homepage or the menu importing the corpus (D.10).
//
// Re-generate with `node scripts/gen-page-questions.mjs`; `npm run audit`
// fails if this file has drifted from the banks.
export const PAGE_QUESTION_IDS: Record<string, readonly string[]> = {
  'stoich': [
    'sto-001', 'sto-002', 'sto-003', 'sto-004', 'sto-005', 'sto-026',
    'sto-027', 'sto-028', 'sto-029', 'sto-030', 'sto-006', 'sto-024',
    'sto-031', 'sto-032', 'sto-015', 'sto-009', 'sto-016', 'sto-010',
    'sto-018', 'sto-033',
  ],
  'stoich-contest': [
    'sto-007', 'sto-008', 'sto-011', 'sto-012', 'sto-013', 'sto-014',
    'sto-017', 'sto-019', 'sto-020', 'sto-021', 'sto-022', 'sto-023',
    'sto-025',
  ],
  'quantum': [
    'qua-001', 'qua-002', 'qua-003', 'qua-004', 'qua-005', 'qua-026',
    'qua-027', 'qua-028', 'qua-029', 'qua-030', 'qua-033', 'qua-031',
    'qua-034', 'qua-032', 'qua-038', 'qua-035', 'qua-013', 'qua-024',
    'qua-036', 'qua-037',
  ],
  'quantum-contest': [
    'qua-006', 'qua-007', 'qua-008', 'qua-009', 'qua-010', 'qua-011',
    'qua-012', 'qua-014', 'qua-015', 'qua-016', 'qua-017', 'qua-018',
    'qua-019', 'qua-020', 'qua-021', 'qua-022', 'qua-023', 'qua-025',
  ],
  'periodicity': [
    'per-001', 'per-002', 'per-003', 'per-004', 'per-005', 'per-026',
    'per-027', 'per-028', 'per-029', 'per-030', 'per-006', 'per-007',
    'per-018', 'per-008', 'per-019', 'per-010', 'per-020', 'per-023',
    'per-022', 'per-024',
  ],
  'periodicity-contest': [
    'per-009', 'per-011', 'per-012', 'per-013', 'per-014', 'per-015',
    'per-016', 'per-017', 'per-021', 'per-025',
  ],
  'bonding': [
    'bon-001', 'bon-002', 'bon-003', 'bon-004', 'bon-005', 'bon-036',
    'bon-037', 'bon-038', 'bon-039', 'bon-040', 'bon-041', 'bon-042',
    'bon-010', 'bon-011', 'bon-043', 'bon-044', 'bon-013', 'bon-016',
    'bon-045', 'bon-046',
  ],
  'bonding-contest': [
    'bon-006', 'bon-007', 'bon-008', 'bon-009', 'bon-012', 'bon-014',
    'bon-015', 'bon-017', 'bon-018', 'bon-019', 'bon-020', 'bon-021',
    'bon-022', 'bon-023', 'bon-024', 'bon-025', 'bon-026', 'bon-027',
    'bon-028', 'bon-029', 'bon-030', 'bon-031', 'bon-032', 'bon-033',
    'bon-034', 'bon-035',
  ],
  'thermo1': [
    'th1-001', 'th1-002', 'th1-003', 'th1-004', 'th1-005', 'th1-026',
    'th1-027', 'th1-028', 'th1-029', 'th1-030', 'th1-014', 'th1-009',
    'th1-013', 'th1-019', 'th1-020', 'th1-010', 'th1-023', 'th1-017',
    'th1-022', 'th1-025',
  ],
  'thermo1-contest': [
    'th1-006', 'th1-007', 'th1-008', 'th1-011', 'th1-012', 'th1-015',
    'th1-016', 'th1-018', 'th1-021', 'th1-024',
  ],
  'equilibrium': [
    'equ-001', 'equ-002', 'equ-003', 'equ-004', 'equ-005', 'equ-026',
    'equ-027', 'equ-028', 'equ-029', 'equ-030', 'equ-011', 'equ-012',
    'equ-018', 'equ-014', 'equ-006', 'equ-023', 'equ-010', 'equ-024',
    'equ-007', 'equ-021',
  ],
  'equilibrium-contest': [
    'equ-008', 'equ-009', 'equ-013', 'equ-015', 'equ-016', 'equ-017',
    'equ-019', 'equ-020', 'equ-022', 'equ-025',
  ],
  'aek': [
    'aek-001', 'aek-002', 'aek-003', 'aek-004', 'aek-005', 'aek-036',
    'aek-037', 'aek-038', 'aek-039', 'aek-040', 'aek-041', 'aek-012',
    'aek-014', 'aek-042', 'aek-043', 'aek-011', 'aek-044', 'aek-023',
    'aek-018', 'aek-019',
  ],
  'aek-contest': [
    'aek-006', 'aek-007', 'aek-008', 'aek-009', 'aek-010', 'aek-013',
    'aek-015', 'aek-016', 'aek-017', 'aek-020', 'aek-021', 'aek-022',
    'aek-024', 'aek-025', 'aek-026', 'aek-027', 'aek-028', 'aek-029',
    'aek-030', 'aek-031', 'aek-032', 'aek-033', 'aek-034', 'aek-035',
  ],
  'labdata': [
    'lbd-001', 'lbd-002', 'lbd-003', 'lbd-004', 'lbd-005', 'lbd-026',
    'lbd-027', 'lbd-028', 'lbd-029', 'lbd-030', 'lbd-007', 'lbd-012',
    'lbd-008', 'lbd-014', 'lbd-010', 'lbd-015', 'lbd-006', 'lbd-019',
    'lbd-013', 'lbd-017',
  ],
  'labdata-contest': [
    'lbd-009', 'lbd-011', 'lbd-016', 'lbd-018', 'lbd-020', 'lbd-021',
    'lbd-022', 'lbd-023', 'lbd-024', 'lbd-025',
  ],
  'labtech': [
    'lbt-001', 'lbt-002', 'lbt-003', 'lbt-004', 'lbt-005', 'lbt-030',
    'lbt-031', 'lbt-032', 'lbt-033', 'lbt-034', 'lbt-006', 'lbt-007',
    'lbt-009', 'lbt-035', 'lbt-014', 'lbt-015', 'lbt-017', 'lbt-021',
    'lbt-022', 'lbt-028',
  ],
  'labtech-contest': [
    'lbt-008', 'lbt-010', 'lbt-011', 'lbt-012', 'lbt-013', 'lbt-016',
    'lbt-018', 'lbt-019', 'lbt-020', 'lbt-023', 'lbt-024', 'lbt-025',
    'lbt-026', 'lbt-027', 'lbt-029',
  ],
};
